// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2 (2026-06-10): genOnOff lives on endpoint 2, not endpoint 1.
// z2m declares `endpoint: () => ({default: 2})`, so the controllable
// onOff cluster + its reporting binding belong on EP2. The auto-port
// bound genOnOff on EP1 and left default_endpoint=0, which routes
// outbound on/off frames to the wrong endpoint (dead toggle) and
// configures reporting on the wrong endpoint. Re-endpointed the binding
// ep1->ep2 and set default_endpoint=2 to mirror z2m.
// Tier 1: Ge PTAPT-WH02 — auto-generated.
// Quirky smart switch
// z2m-source: ge.ts #PTAPT-WH02 (endpoint default:2).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::ge {
namespace {
const FzConverter* const kFz_PTAPT_WH02[] = {
    &::zhc::generic::kFzOnOff,
};
const TzConverter* const kTz_PTAPT_WH02[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_PTAPT_WH02[] = { "Smart Switch" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {2, 0x0006},  // genOnOff on endpoint 2 (z2m endpoint default:2)
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_PTAPT_WH02{
    .zigbee_models=kModels_PTAPT_WH02, .zigbee_models_count=sizeof(kModels_PTAPT_WH02)/sizeof(kModels_PTAPT_WH02[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="PTAPT-WH02", .vendor="Ge",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_PTAPT_WH02, .from_zigbee_count=sizeof(kFz_PTAPT_WH02)/sizeof(kFz_PTAPT_WH02[0]),
    .to_zigbee=kTz_PTAPT_WH02, .to_zigbee_count=sizeof(kTz_PTAPT_WH02)/sizeof(kTz_PTAPT_WH02[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
.default_endpoint=2,
};

}  // namespace zhc::devices::ge
