// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Sengled E1D-G73WNA — hand-maintained parity override.
//
// Graduated from generated/Sen_E1D_G73WNA.cpp: the generated def lowered the
// generic kFzIasZone converter — which emits the bare key "alarm" — while
// z2m's m.iasZoneAlarm({zoneType: "contact"}) publishes the semantic key
// "contact". With no rename layer the primary contact state never reached
// the shadow. z2m decodes this via fz.ias_contact_alarm_1 (zoneStatus
// bit 0), so the typed kFzIasContactAlarm converter — which emits
// "contact" directly — is at parity. Mirrors the heiman HS1DS fix.
// Smart window and door sensor
// z2m-source: sengled.ts #E1D-G73WNA (extend: m.iasZoneAlarm({zoneType: "contact", zoneAttributes: ["alarm_1", "tamper", "battery_low"]}) + m.battery({voltage: true, voltageReporting: true})).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::sengled {
namespace {
const FzConverter* const kFz_E1D_G73WNA[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_E1D_G73WNA[] = { "E1D-G73" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_E1D_G73WNA{
    .zigbee_models=kModels_E1D_G73WNA, .zigbee_models_count=sizeof(kModels_E1D_G73WNA)/sizeof(kModels_E1D_G73WNA[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="E1D-G73WNA", .vendor="Sengled",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_E1D_G73WNA, .from_zigbee_count=sizeof(kFz_E1D_G73WNA)/sizeof(kFz_E1D_G73WNA[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::sengled
