// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Netvox ZB02A — wireless wall switch (remote/button).
// z2m role is `action: toggle` via genOnOff commandToggle (fz.command_toggle),
// NOT a controllable on/off switch. Was mis-ported as kFzOnOff + kTzOnOff with
// a dead `state` expose; corrected to kFzCommandToggle emitting `action`.
// z2m-source: netvox.ts #ZB02A (fromZigbee:[fz.command_toggle], toZigbee:[], exposes:[e.action(["toggle"])]).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::netvox {
namespace {
const FzConverter* const kFz_ZB02A[] = {
    &::zhc::generic::kFzCommandToggle,
};
constexpr const char* kModels_ZB02A[] = { "ZB02AE0ED" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZB02A{
    .zigbee_models=kModels_ZB02A, .zigbee_models_count=sizeof(kModels_ZB02A)/sizeof(kModels_ZB02A[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZB02A", .vendor="Netvox",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZB02A, .from_zigbee_count=sizeof(kFz_ZB02A)/sizeof(kFz_ZB02A[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::netvox
