// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Sercomm SZ-PIR04N — graduated override.
// PIR motion & temperature sensor.
// z2m-source: sercomm.ts #SZ-PIR04N.
//
// Bug fixed: z2m wires this PIR with `extend: [m.illuminance()]` on top of
// ias_occupancy_alarm_1 + temperature + battery, exposing `illuminance`
// (msIlluminanceMeasurement 0x0400 measuredValue). The auto-port dropped the
// illuminance channel entirely (no decoder, no expose, no 0x0400 binding), so
// ambient-light readings never reached the shadow. Wire the generic
// kFzIlluminance converter, add the `illuminance` expose, and bind 0x0400.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::sercomm {
namespace {
const FzConverter* const kFz_SZ_PIR04N[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzIlluminance,
    &::zhc::generic::kFzIasMotionAlarm,
};

constexpr const char* kModels_SZ_PIR04N[] = { "SZ-PIR04N", "SZ-PIR04N_EU" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"illuminance", ExposeType::Numeric, Access::State, "lx", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0400},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SZ_PIR04N{
    .zigbee_models=kModels_SZ_PIR04N, .zigbee_models_count=sizeof(kModels_SZ_PIR04N)/sizeof(kModels_SZ_PIR04N[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SZ-PIR04N", .vendor="Sercomm",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SZ_PIR04N, .from_zigbee_count=sizeof(kFz_SZ_PIR04N)/sizeof(kFz_SZ_PIR04N[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::sercomm
