// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Legrand 067776A — GRADUATED from generated/ for the v26.101.0
// moving-state rework. Netatmo wired shutter switch with level control (NLLV).
//
// z2m v26.101.0 replaced this entry's plain cover converters with a
// moving-state aware pair: `fzLegrand.cover_moving_state` decodes the Tuya
// manufacturer attribute `tuyaMovingState` (0xF000) against the reported lift
// to publish `moving` plus an action of opening / closing / stopped. The old
// action list ("identify", "open", "close", "stop", "moving", "stopped") is
// gone; the three travel states replace it.
//
// The stock position/state converters stay wired alongside — the new decoder
// only fires on frames carrying 0xF000, so ordinary position reports are
// unaffected.
//
// NOT ported: z2m also swapped `tz.cover_state` / `tz.cover_position_tilt` for
// `tzLegrand.cover_state_with_moving` / `cover_position_with_moving`. Those
// wrap the standard commands to optimistically publish `moving` on the way
// out; the device re-reports 0xF000 within a second anyway, so the wrapper
// buys an optimistic UI update this codebase would have to fake. Left on the
// stock tz until someone asks for the optimistic edge.
//
// z2m-source: legrand.ts #067776A, lib/legrand.ts fzLegrand.cover_moving_state.
#include "definitions/_generic/_shared.hpp"
#include "definitions/legrand/_shared.hpp"

namespace zhc::devices::legrand {
namespace {
const FzConverter* const kFz_D067776A[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzCoverPosition,
    &::zhc::legrand::kFzClusterFc01,
    &::zhc::legrand::kFzCoverMovingState,
};
const TzConverter* const kTz_D067776A[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzCoverPosition,
    &::zhc::legrand::kTzLedInDark,
    &::zhc::legrand::kTzLedIfOn,
};
constexpr const char* kModels_D067776A[] = { " Shutter SW with level control" };

constexpr const char* kActionValues_D067776A[] = { "opening", "closing", "stopped" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"led_in_dark", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"led_if_on",   ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"moving",      ExposeType::Binary, Access::State,    nullptr,
     "Indicates if the cover is currently moving", nullptr, 0},
    {"action",      ExposeType::Enum,   Access::State,    nullptr, nullptr,
     kActionValues_D067776A, sizeof(kActionValues_D067776A)/sizeof(kActionValues_D067776A[0])},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0102},
    {1, 0xFC01},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D067776A{
    .zigbee_models=kModels_D067776A, .zigbee_models_count=sizeof(kModels_D067776A)/sizeof(kModels_D067776A[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="067776A", .vendor="Legrand",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D067776A, .from_zigbee_count=sizeof(kFz_D067776A)/sizeof(kFz_D067776A[0]),
    .to_zigbee=kTz_D067776A, .to_zigbee_count=sizeof(kTz_D067776A)/sizeof(kTz_D067776A[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::legrand
