// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Lonsonho X701A — graduated from generated/ to fix a fingerprint gap.
// 1 gang switch with backlight
// z2m-source: lonsonho.ts #X701A —
//   tuya.fingerprint("TS0001", ["_TZ3000_t3s9qmmg", "_TZ3000_ehgouyvu"]).
// The generated def only carried "_TZ3000_t3s9qmmg"; "_TZ3000_ehgouyvu"
// was dropped, so that hardware variant never matched. Both manufacturer
// names are restored below.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::lonsonho {
namespace {
const FzConverter* const kFz_X701A[] = {
    &::zhc::generic::kFzOnOff,
};
const TzConverter* const kTz_X701A[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_X701A[] = { "TS0001" };
constexpr const char* kManus_X701A[] = { "_TZ3000_t3s9qmmg", "_TZ3000_ehgouyvu" };
}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_X701A{
    .zigbee_models=kModels_X701A, .zigbee_models_count=sizeof(kModels_X701A)/sizeof(kModels_X701A[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus_X701A, .manufacturer_names_count=sizeof(kManus_X701A)/sizeof(kManus_X701A[0]),
    .model="X701A", .vendor="Lonsonho",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_X701A, .from_zigbee_count=sizeof(kFz_X701A)/sizeof(kFz_X701A[0]),
    .to_zigbee=kTz_X701A, .to_zigbee_count=sizeof(kTz_X701A)/sizeof(kTz_X701A[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::lonsonho
