// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Vav VAV-256215-MOD1 — graduated from generated/.
// Pilot wire heating module.
// Gaps fixed vs the Tier-1 auto-port:
//   * power_on_behavior — z2m m.onOff({powerOnBehavior:true}) decodes
//     genOnOff 0x4003 startUpOnOff; was dropped. Wired generic
//     kFzPowerOnBehavior + kTzPowerOnBehavior1.
//   * pilot_wire_mode — z2m ...nodonPilotWire(true) decodes the NodOn
//     custom cluster 0xFC00 attr 0x0000 (mode) into a pilot_wire_mode
//     enum; was dropped entirely. Wired vav::kFzPilotWireMode.
// (metering uses cluster:"metering" = seMetering 0x0702 only, so the
//  Tier-1 kFzMetering / energy+power exposes are correct — no 0x0B04.)
// z2m-source: vav.ts #VAV-256215-MOD1 + lib/nodon.ts nodonPilotWire.
#include "definitions/_generic/_shared.hpp"
#include "definitions/vav/_shared.hpp"

namespace zhc::devices::vav {
namespace {
const FzConverter* const kFz_VAV_256215_MOD1[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzPowerOnBehavior,
    &::zhc::generic::kFzMetering,
    &::zhc::vav::kFzPilotWireMode,
};
const TzConverter* const kTz_VAV_256215_MOD1[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_VAV_256215_MOD1[] = { "VAV-256215-MOD1" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"pilot_wire_mode", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_VAV_256215_MOD1{
    .zigbee_models=kModels_VAV_256215_MOD1, .zigbee_models_count=sizeof(kModels_VAV_256215_MOD1)/sizeof(kModels_VAV_256215_MOD1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="VAV-256215-MOD1", .vendor="Vav",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_VAV_256215_MOD1, .from_zigbee_count=sizeof(kFz_VAV_256215_MOD1)/sizeof(kFz_VAV_256215_MOD1[0]),
    .to_zigbee=kTz_VAV_256215_MOD1, .to_zigbee_count=sizeof(kTz_VAV_256215_MOD1)/sizeof(kTz_VAV_256215_MOD1[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::vav
