// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: LivingWise LVS-SM10ZW — graduated from generated/ to fix the IAS key.
// Door or window contact switch
// z2m-source: livingwise.ts #LVS-SM10ZW (fz.ias_contact_alarm_1).
//
// The generated stub wired the generic kFzIasZone, which emits the bare
// key `alarm`. The expose set declares the semantic `contact` key (z2m
// e.contact()), so the alarm signal never reached the shadow — a dead
// IAS key. z2m decodes via fz.ias_contact_alarm_1 (zoneStatus bit 0 ->
// `contact`, bit 2 -> tamper, bit 3 -> battery_low). Swapped to the typed
// kFzIasContactAlarm converter (emits contact + tamper + battery_low) and
// renamed the expose `alarm` -> `contact`.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::livingwise {
namespace {
const FzConverter* const kFz_LVS_SM10ZW[] = {
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_LVS_SM10ZW[] = { "e70f96b3773a4c9283c6862dbafb6a99" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_LVS_SM10ZW{
    .zigbee_models=kModels_LVS_SM10ZW, .zigbee_models_count=sizeof(kModels_LVS_SM10ZW)/sizeof(kModels_LVS_SM10ZW[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="LVS-SM10ZW", .vendor="LivingWise",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_LVS_SM10ZW, .from_zigbee_count=sizeof(kFz_LVS_SM10ZW)/sizeof(kFz_LVS_SM10ZW[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::livingwise
