// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Jxuan DSZ01 — IAS dead-key fix.
// Door or window contact switch.
// z2m wires fz.ias_contact_alarm_1 (zoneStatus bit0, contact = !bit0) and
// exposes e.contact(); the generic kFzIasZone emitted bare alarm_1/alarm_2
// keys the expose never declared, so the `contact` state was dead. Wire the
// typed kFzIasContactAlarm — it emits `contact` already z2m-inverted
// (contact = !bit0) plus tamper/battery_low. Do NOT add extra inversion.
// z2m-source: jxuan.ts #DSZ01 + converters/fromZigbee.ts ias_contact_alarm_1.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::jxuan {
namespace {
const FzConverter* const kFz_DSZ01[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_DSZ01[] = { "door sensor" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_DSZ01{
    .zigbee_models=kModels_DSZ01, .zigbee_models_count=sizeof(kModels_DSZ01)/sizeof(kModels_DSZ01[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="DSZ01", .vendor="Jxuan",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_DSZ01, .from_zigbee_count=sizeof(kFz_DSZ01)/sizeof(kFz_DSZ01[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::jxuan
