// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Jxuan WSZ01 — phantom on/off + dead-action fix.
// Wireless switch (battery button, action role — NOT a controllable on/off).
// z2m wires fz.WSZ01_on_off_action (manuSpecific cluster 0xFE05, attr id 1 →
// action {0:release,1:single,2:double,3:hold}) + fz.battery, exposes
// e.action([...]) + e.battery(), and has an EMPTY toZigbee (no controllable
// state). The auto-port mis-rendered it as a controllable genOnOff switch:
// it wired kFzOnOff + kTzOnOff and exposed a `state` that never changes
// (phantom on/off), and dropped the action entirely. Wire the vendor
// kFzWsz01Action (emits `action`) + kFzBattery; drop the phantom on/off and
// its toZigbee. Model id restored to the full z2m form (the auto-port
// truncated at the embedded NUL escape).
// z2m-source: jxuan.ts #WSZ01 + converters/fromZigbee.ts WSZ01_on_off_action.
#include "definitions/_generic/_shared.hpp"
#include "definitions/jxuan/_shared.hpp"

namespace zhc::devices::jxuan {
namespace {
const FzConverter* const kFz_WSZ01[] = {
    &kFzWsz01Action,
    &::zhc::generic::kFzBattery,
};
constexpr const char* kModels_WSZ01[] = { "JD-SWITCH\\u000002" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_WSZ01{
    .zigbee_models=kModels_WSZ01, .zigbee_models_count=sizeof(kModels_WSZ01)/sizeof(kModels_WSZ01[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="WSZ01", .vendor="Jxuan",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_WSZ01, .from_zigbee_count=sizeof(kFz_WSZ01)/sizeof(kFz_WSZ01[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::jxuan
