// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Shinasystem GCM-300Z — graduated from generated/.
// SiHAS gas valve
//
// Generator misses (two real bugs):
//  1) `to_zigbee` was left null even though a kTz_GCM_300Z array was
//     emitted — so EVERY writable control (valve, close_timeout,
//     close_remain_timeout, volume, overheat_mode) was dead. Wired it.
//  2) The valve read/write rode the generic on/off `state` key, but the
//     device's primary control is exposed as `gas_valve_state`
//     ("OPEN"/"CLOSE"). The generic kFzOnOff/kTzOnOff (key "state")
//     never matched that expose, so valve status never reached the
//     shadow and valve commands were dropped. Swapped in the dedicated
//     kFzSihasGasValveState / kTzSihasGasValveState converters.
//
// z2m-source: shinasystem.ts #GCM-300Z.
#include "definitions/_generic/_shared.hpp"
#include "definitions/shinasystem/_shared.hpp"

namespace zhc::devices::shinasystem {
namespace {
const FzConverter* const kFz_GCM_300Z[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::shinasystem::kFzSihasGasValveState,
};
const TzConverter* const kTz_GCM_300Z[] = {
    &::zhc::shinasystem::kTzSihasGasValveState,
    &::zhc::shinasystem::kTzSihasCloseTimeout,
    &::zhc::shinasystem::kTzSihasCloseRemainTimeout,
    &::zhc::shinasystem::kTzSihasVolume,
    &::zhc::shinasystem::kTzSihasOverheatMode,
};

constexpr const char* kModels_GCM_300Z[] = { "GCM-300Z" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"gas_valve_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"close_timeout", ExposeType::Numeric, Access::StateSet, "min", nullptr, nullptr, 0},
    {"close_remain_timeout", ExposeType::Numeric, Access::StateSet, "min", nullptr, nullptr, 0},
    {"volume", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"overheat_mode", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_GCM_300Z{
    .zigbee_models=kModels_GCM_300Z, .zigbee_models_count=sizeof(kModels_GCM_300Z)/sizeof(kModels_GCM_300Z[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="GCM-300Z", .vendor="Shinasystem",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_GCM_300Z, .from_zigbee_count=sizeof(kFz_GCM_300Z)/sizeof(kFz_GCM_300Z[0]),
    .to_zigbee=kTz_GCM_300Z, .to_zigbee_count=sizeof(kTz_GCM_300Z)/sizeof(kTz_GCM_300Z[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::shinasystem
