// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Shinasystem OSM-300ZB — graduated from generated/.
// SiHAS Motion Sensor
//
// Generator miss: z2m's `extend: [m.occupancy(), m.battery(...)]` was
// lowered to battery only. The `occupancy` expose was emitted (and
// msOccupancySensing 0x0406 was bound) but had NO decoder, so the
// primary motion state never reached the shadow. Re-added kFzOccupancy.
// Same shape as heiman HS1MIS-3.0 (msOccupancySensing, not IAS).
//
// z2m-source: shinasystem.ts #OSM-300ZB.
#include "definitions/_generic/_shared.hpp"
#include "definitions/shinasystem/_shared.hpp"

namespace zhc::devices::shinasystem {
namespace {
const FzConverter* const kFz_OSM_300ZB[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzOccupancy,
};

constexpr const char* kModels_OSM_300ZB[] = { "OSM-300Z" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0406},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_OSM_300ZB{
    .zigbee_models=kModels_OSM_300ZB, .zigbee_models_count=sizeof(kModels_OSM_300ZB)/sizeof(kModels_OSM_300ZB[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="OSM-300ZB", .vendor="Shinasystem",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_OSM_300ZB, .from_zigbee_count=sizeof(kFz_OSM_300ZB)/sizeof(kFz_OSM_300ZB[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::shinasystem
