// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Visonic MCT-302 SMA — IAS dead-key + dropped temperature channel.
// Magnetic door & window contact sensor
// z2m-source: visonic.ts #MCT-302 SMA
//   (extend: [m.temperature(), m.battery(),
//             m.iasZoneAlarm({zoneType: "contact",
//                             zoneAttributes: ["alarm_1","tamper","battery_low"]})]).
// Two gaps in the generated def:
//   (1) lowered the generic kFzIasZone (bare key "alarm") while the expose
//       declared the semantic key -> contact never reached the shadow;
//       swapped to typed kFzIasContactAlarm (emits `contact` from bit 0).
//   (2) z2m's m.temperature() decodes msTemperatureMeasurement and exposes
//       e.temperature(), but the port dropped both the decoder and the
//       expose. Added kFzTemperature + the `temperature` expose + 0x0402 bind.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::visonic {
namespace {
const FzConverter* const kFz_MCT_302_SMA[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
    &::zhc::generic::kFzTemperature,
};

constexpr const char* kModels_MCT_302_SMA[] = { "MCT-302 SMA" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "\xc2\xb0""C", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MCT_302_SMA{
    .zigbee_models=kModels_MCT_302_SMA, .zigbee_models_count=sizeof(kModels_MCT_302_SMA)/sizeof(kModels_MCT_302_SMA[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MCT-302 SMA", .vendor="Visonic",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MCT_302_SMA, .from_zigbee_count=sizeof(kFz_MCT_302_SMA)/sizeof(kFz_MCT_302_SMA[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::visonic
