// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Visonic MP-840 — IAS dead-key + dropped temperature channel.
// Long range pet immune PIR motion sensor
// z2m-source: visonic.ts #MP-840
//   (fromZigbee: [fz.ias_occupancy_alarm_1, fz.temperature, fz.battery]).
// Two gaps in the generated def:
//   (1) lowered the generic kFzIasZone (bare key "alarm") while the expose
//       declared the semantic key -> occupancy never reached the shadow;
//       swapped to typed kFzIasMotionAlarm (emits `occupancy` from bit 0).
//   (2) z2m decodes msTemperatureMeasurement (fz.temperature) and exposes
//       e.temperature(), but the port dropped both the decoder and the
//       expose -> temperature was dead. Added kFzTemperature + the
//       `temperature` expose + the 0x0402 binding.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::visonic {
namespace {
const FzConverter* const kFz_MP_840[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasMotionAlarm,
    &::zhc::generic::kFzTemperature,
};

constexpr const char* kModels_MP_840[] = { "MP-840" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "\xc2\xb0""C", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MP_840{
    .zigbee_models=kModels_MP_840, .zigbee_models_count=sizeof(kModels_MP_840)/sizeof(kModels_MP_840[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MP-840", .vendor="Visonic",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MP_840, .from_zigbee_count=sizeof(kFz_MP_840)/sizeof(kFz_MP_840[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::visonic
