// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Visonic GB-540 — IAS dead-key fix.
// Glass break detector
// z2m-source: visonic.ts #GB-540 (fz.ias_vibration_alarm_1 -> zoneStatus
// bit0 = vibration). The generated def lowered the generic kFzIasZone (bare
// key "alarm") while the expose declared the semantic key, so the vibration
// state never reached the shadow. Swapped to the typed kFzIasVibrationAlarm
// (emits `vibration` from bit 0) and renamed the expose.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::visonic {
namespace {
const FzConverter* const kFz_GB_540[] = {
    &::zhc::generic::kFzIasVibrationAlarm,
};

constexpr const char* kModels_GB_540[] = { "GB-540" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"vibration", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_GB_540{
    .zigbee_models=kModels_GB_540, .zigbee_models_count=sizeof(kModels_GB_540)/sizeof(kModels_GB_540[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="GB-540", .vendor="Visonic",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_GB_540, .from_zigbee_count=sizeof(kFz_GB_540)/sizeof(kFz_GB_540[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::visonic
