// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Dqsmart dqhome.re4 — graduated from generated/.
// DQSmart Switch 4 Gang (DQHOME dqhome.re4).
// z2m-source: dqsmart.ts #dqhome.re4 —
//   m.deviceEndpoints({l1:1, l2:2, l3:3, l4:4}) +
//   m.onOff({powerOnBehavior:false, endpointNames:["l1","l2","l3","l4"]}).
//
// FIX: incomplete per-endpoint bindings. The auto-port bound genOnOff
// (0x0006) only on endpoint 1, so gangs l2/l3/l4 never got reporting
// configured and would not push their state changes. z2m's m.onOff with
// endpointNames runs setupAttributes() per endpoint carrying the cluster
// (getEndpointsWithCluster → ep1..ep4), binding + configuring 0x0006 on
// every gang. Bind 0x0006 on all four endpoints to match. Decode already
// works for every gang via the present endpoint_map (key suffixing
// state → state_l<n> by src_endpoint); only the binding table was short.
// powerOnBehavior:false → no power_on_behavior expose/converter (correct).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::dqsmart {
namespace {
const FzConverter* const kFz_dqhome_re4[] = {
    &::zhc::generic::kFzOnOff,
};
const TzConverter* const kTz_dqhome_re4[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_dqhome_re4[] = { "dqhome.re4" };

constexpr ::zhc::EndpointLabel kEndpoints_dqhome_re4[] = { {"l1", 1}, {"l2", 2}, {"l3", 3}, {"l4", 4} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

// FIX: bind genOnOff (0x0006) on all four gang endpoints (z2m parity),
// not just ep1. See header note.
constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006}, {2, 0x0006}, {3, 0x0006}, {4, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_dqhome_re4{
    .zigbee_models=kModels_dqhome_re4, .zigbee_models_count=sizeof(kModels_dqhome_re4)/sizeof(kModels_dqhome_re4[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="dqhome.re4", .vendor="Dqsmart",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_dqhome_re4, .from_zigbee_count=sizeof(kFz_dqhome_re4)/sizeof(kFz_dqhome_re4[0]),
    .to_zigbee=kTz_dqhome_re4, .to_zigbee_count=sizeof(kTz_dqhome_re4)/sizeof(kTz_dqhome_re4[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_dqhome_re4,
    .endpoint_map_count = sizeof(kEndpoints_dqhome_re4)/sizeof(kEndpoints_dqhome_re4[0]),
};

}  // namespace zhc::devices::dqsmart
