// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Quirky POFLW-WH02 — IAS dead-key fix.
// Smart water leak sensor.
// z2m-source: quirky.ts #POFLW-WH02 — m.iasZoneAlarm({zoneType:"water_leak",
//   zoneAttributes:["alarm_1","battery_low"]}). zoneType is not "generic" and
//   not bothAlarms, so the alarm is published under the semantic key
//   `water_leak` (zoneStatus bit 0), not the bare `alarm`. The auto-port wired
//   the generic kFzIasZone (which emits bare "alarm") against an `alarm` expose
//   the device never names. Swapped to the typed kFzIasWaterLeakAlarm so bit 0
//   decodes to `water_leak`; tamper (bit 2) + battery_low (bit 3) co-decode.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::quirky {
namespace {
const FzConverter* const kFz_POFLW_WH02[] = {
    &::zhc::generic::kFzIasWaterLeakAlarm,
};

constexpr const char* kModels_POFLW_WH02[] = { "Overflow" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"water_leak", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_POFLW_WH02{
    .zigbee_models=kModels_POFLW_WH02, .zigbee_models_count=sizeof(kModels_POFLW_WH02)/sizeof(kModels_POFLW_WH02[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="POFLW-WH02", .vendor="Quirky",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_POFLW_WH02, .from_zigbee_count=sizeof(kFz_POFLW_WH02)/sizeof(kFz_POFLW_WH02[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::quirky
