// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Enbrighten 43076 — hand-curated (was missing action channel).
// Zigbee in-wall smart switch. z2m drives it with
//   m.onOff(...) + m.commandsOnOff({commands:["on","off"], bind:true})
// i.e. besides the controllable on/off `state`, the switch binds genOnOff
// output and reports physical button presses as genOnOff commandOn /
// commandOff, surfaced by z2m as an `action` enum ["on","off"]. The auto-
// port kept only the controllable half (kFzOnOff) and dropped the command/
// action channel entirely. Added kFzCommandOn / kFzCommandOff + an `action`
// enum expose; the controllable on/off surface is unchanged.
// z2m-source: enbrighten.ts #43076 (commandsOnOff).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::enbrighten {
namespace {
const FzConverter* const kFz_D43076[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
};
const TzConverter* const kTz_D43076[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_D43076[] = { "43076", "43109", "43102", "43100", "43094", "43084" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D43076{
    .zigbee_models=kModels_D43076, .zigbee_models_count=sizeof(kModels_D43076)/sizeof(kModels_D43076[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="43076", .vendor="Enbrighten",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D43076, .from_zigbee_count=sizeof(kFz_D43076)/sizeof(kFz_D43076[0]),
    .to_zigbee=kTz_D43076, .to_zigbee_count=sizeof(kTz_D43076)/sizeof(kTz_D43076[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::enbrighten
