// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Enbrighten 43082 — hand-curated (was missing action channel).
// Zigbee in-wall smart dimmer with energy monitoring. z2m drives it with
//   m.light(...) + m.electricityMeter({cluster:"metering"})
//   + m.commandsOnOff({commands:["on","off"], bind:true})
//   + m.commandsLevelCtrl({commands:["brightness_move_up",
//       "brightness_move_down","brightness_stop"], bind:true})
// electricityMeter cluster:"metering" = seMetering 0x0702 only (energy +
// power) — already wired via kFzMetering, matches z2m. The auto-port
// dropped the command/action channel: the dimmer binds genOnOff +
// genLevelCtrl output and reports physical presses as genOnOff commandOn /
// commandOff and genLevelCtrl Move / Stop, surfaced as an `action` enum.
// Added kFzCommandOn / kFzCommandOff / kFzCommandMove / kFzCommandStop +
// an `action` expose; light + energy surfaces unchanged.
// z2m-source: enbrighten.ts #43082 (commandsOnOff + commandsLevelCtrl).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::enbrighten {
namespace {
const FzConverter* const kFz_D43082[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
const TzConverter* const kTz_D43082[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
};
constexpr const char* kModels_D43082[] = { "43082" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D43082{
    .zigbee_models=kModels_D43082, .zigbee_models_count=sizeof(kModels_D43082)/sizeof(kModels_D43082[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="43082", .vendor="Enbrighten",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D43082, .from_zigbee_count=sizeof(kFz_D43082)/sizeof(kFz_D43082[0]),
    .to_zigbee=kTz_D43082, .to_zigbee_count=sizeof(kTz_D43082)/sizeof(kTz_D43082[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::enbrighten
