// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Enbrighten 43080 — hand-curated (was missing action channel).
// Zigbee in-wall smart dimmer. z2m drives it with
//   m.light(...) + m.commandsOnOff({commands:["on","off"], bind:true})
//   + m.commandsLevelCtrl({commands:["brightness_move_up",
//       "brightness_move_down","brightness_stop"], bind:true})
// Besides the controllable light (state + brightness), it binds genOnOff +
// genLevelCtrl output and reports physical presses as genOnOff commandOn /
// commandOff and genLevelCtrl Move / Stop, surfaced as an `action` enum
// ["on","off","brightness_move_up","brightness_move_down",
// "brightness_stop"]. The auto-port kept only the controllable half and
// dropped the command/action channel. Added kFzCommandOn / kFzCommandOff /
// kFzCommandMove / kFzCommandStop + an `action` expose; the light surface
// is unchanged.
// z2m-source: enbrighten.ts #43080 (commandsOnOff + commandsLevelCtrl).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::enbrighten {
namespace {
const FzConverter* const kFz_D43080[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
const TzConverter* const kTz_D43080[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
};
constexpr const char* kModels_D43080[] = { "43080", "43113", "43090", "43096" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D43080{
    .zigbee_models=kModels_D43080, .zigbee_models_count=sizeof(kModels_D43080)/sizeof(kModels_D43080[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="43080", .vendor="Enbrighten",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D43080, .from_zigbee_count=sizeof(kFz_D43080)/sizeof(kFz_D43080[0]),
    .to_zigbee=kTz_D43080, .to_zigbee_count=sizeof(kTz_D43080)/sizeof(kTz_D43080[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::enbrighten
