// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: MatcallBv ZG430700 — LED dimmer driver, power_on_behavior restored.
// LED dimmer driver
// z2m-source: matcall_bv.ts #ZG430700 = m.light().
// m.light() with no color/colorTemp args exposes only on/off + brightness
// (no color/colorTemp axis — the "dropped color" suspicion is FALSE), but it
// defaults powerOnBehavior=true, wiring fz.power_on_behavior (genOnOff 0x4003
// startUpOnOff) + tz.power_on_behavior + the power_on_behavior enum expose.
// The Tier-1 auto-port dropped that axis; restored via kFzPowerOnBehavior /
// kTzPowerOnBehavior1. z2m's tz.effect (write-only command) has no generic
// converter and is deferred as INFRA.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::matcall_bv {
namespace {
const FzConverter* const kFz_ZG430700[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzPowerOnBehavior,
};
const TzConverter* const kTz_ZG430700[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_ZG430700[] = { "ZG 430700", "ZG  430700" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZG430700{
    .zigbee_models=kModels_ZG430700, .zigbee_models_count=sizeof(kModels_ZG430700)/sizeof(kModels_ZG430700[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZG430700", .vendor="MatcallBv",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZG430700, .from_zigbee_count=sizeof(kFz_ZG430700)/sizeof(kFz_ZG430700[0]),
    .to_zigbee=kTz_ZG430700, .to_zigbee_count=sizeof(kTz_ZG430700)/sizeof(kTz_ZG430700[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::matcall_bv
