// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 3: SlackyDiy TS0042-z-SlD — graduated from generated/.
// Tuya wireless switch with 2 buttons with custom firmware
//
// Parity (z2m v26.35->v26.76): the z2m fingerprint gained a new custom-firmware
// modelID "TS0042-M006-SlD" (added alongside the existing z/M003). Added it to the
// match list so M006 units bind to this def. The z2m commandsColorCtrl helper only
// enriches the generic `action` enum (already exposed) — no runtime change.
// z2m-source: slacky_diy.ts #TS0042-z-SlD.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::slacky_diy {
namespace {
const FzConverter* const kFz_TS0042_z_SlD[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBattery,
};
const TzConverter* const kTz_TS0042_z_SlD[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_TS0042_z_SlD[] = { "TS0042-z-SlD", "TS0042-M003-SlD", "TS0042-M006-SlD" };

constexpr ::zhc::EndpointLabel kEndpoints_TS0042_z_SlD[] = { {"1", 1}, {"2", 2} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_TS0042_z_SlD{
    .zigbee_models=kModels_TS0042_z_SlD, .zigbee_models_count=sizeof(kModels_TS0042_z_SlD)/sizeof(kModels_TS0042_z_SlD[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="TS0042-z-SlD", .vendor="SlackyDiy",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_TS0042_z_SlD, .from_zigbee_count=sizeof(kFz_TS0042_z_SlD)/sizeof(kFz_TS0042_z_SlD[0]),
    .to_zigbee=kTz_TS0042_z_SlD, .to_zigbee_count=sizeof(kTz_TS0042_z_SlD)/sizeof(kTz_TS0042_z_SlD[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_TS0042_z_SlD,
    .endpoint_map_count = sizeof(kEndpoints_TS0042_z_SlD)/sizeof(kEndpoints_TS0042_z_SlD[0]),
};

}  // namespace zhc::devices::slacky_diy
