// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Hoftronic HD300W-ZB — graduated from generated/ for parity fix.
// Rotary smart zigbee LED dimmer.
// z2m-source: hoftronic.ts #HD300W-ZB — m.light({powerOnBehavior:true,...}).
// Parity fix: z2m m.light() with powerOnBehavior:true exposes
// `power_on_behavior` and wires fz.power_on_behavior / tz.power_on_behavior
// (genOnOff 0x4003 startUpOnOff). The auto-port dropped this axis, reducing
// the dimmer to bare on/off + brightness. Restore the read+write converters
// (generic kFzPowerOnBehavior / kTzPowerOnBehavior1, both genOnOff 0x4003)
// and the enum expose. No color/colorTemp axis exists in z2m (m.light called
// without color/colorTemp args) — none added.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::hoftronic {
namespace {
const FzConverter* const kFz_HD300W_ZB[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzPowerOnBehavior,   // genOnOff 0x4003 startUpOnOff
};
const TzConverter* const kTz_HD300W_ZB[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzPowerOnBehavior1,  // genOnOff 0x4003 writeAttributes
};
constexpr const char* kModels_HD300W_ZB[] = { "HD300W-ZB" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_HD300W_ZB{
    .zigbee_models=kModels_HD300W_ZB, .zigbee_models_count=sizeof(kModels_HD300W_ZB)/sizeof(kModels_HD300W_ZB[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="HD300W-ZB", .vendor="Hoftronic",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_HD300W_ZB, .from_zigbee_count=sizeof(kFz_HD300W_ZB)/sizeof(kFz_HD300W_ZB[0]),
    .to_zigbee=kTz_HD300W_ZB, .to_zigbee_count=sizeof(kTz_HD300W_ZB)/sizeof(kTz_HD300W_ZB[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::hoftronic
