// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Nedis ZBHTR20WT TRV (fingerprint TS0601 / _TZE284_ne4pikwm).
// z2m-source: nedis.ts #ZBHTR20WT.
// Fix: DP27 local_temperature_calibration uses z2m valueConverter.localTempCalibration2
//      (from: v => v, no division). The auto-port baked divisor=100 → 100x scale
//      error. Corrected to 1 (raw int pass-through), matching z2m.
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"
namespace zhc::devices::nedis {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kEnum__TZE284_ne4pikwm_running_state_dp3[] = {
    { 1, "heat" },
    { 0, "idle" },
};

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries__TZE284_ne4pikwm[] = {
    { 3, "running_state", ::zhc::TuyaDpType::Enum, 1, kEnum__TZE284_ne4pikwm_running_state_dp3, sizeof(kEnum__TZE284_ne4pikwm_running_state_dp3)/sizeof(kEnum__TZE284_ne4pikwm_running_state_dp3[0]) },
    { 8, "open_window", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 10, "frost_protection", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 27, "local_temperature_calibration", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 40, "child_lock", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 102, "local_temperature", ::zhc::TuyaDpType::Numeric, 10, nullptr, 0, 0 },
    { 103, "current_heating_setpoint", ::zhc::TuyaDpType::Numeric, 10, nullptr, 0, 0 },
    { 105, "battery_low", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 106, "leave_home", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 108, "schedule_mode", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 130, "scale_protection", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap__TZE284_ne4pikwm{ kEntries__TZE284_ne4pikwm, 11 };
constexpr FzConverter kFzDp__TZE284_ne4pikwm{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap__TZE284_ne4pikwm,
};
const FzConverter* const kFz__TZE284_ne4pikwm[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDp__TZE284_ne4pikwm,
};
constexpr TzConverter kTzDp__TZE284_ne4pikwm{
    .key         = nullptr,                // wildcard — claims any mapped key
    .cluster     = "manuSpecificTuya",
    .cluster_id  = 0xEF00,
    .command_id  = 0x00,
    .fn          = &::zhc::tuya::tz_tuya_datapoints,
    .user_config = &kMap__TZE284_ne4pikwm,
};
const TzConverter* const kTz__TZE284_ne4pikwm[] = { &kTzDp__TZE284_ne4pikwm };
constexpr const char* kM__TZE284_ne4pikwm[] = { "TS0601" };
constexpr const char* kN__TZE284_ne4pikwm[] = { "_TZE284_ne4pikwm" };
}  // namespace

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"running_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"open_window", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"frost_protection", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"local_temperature_calibration", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"child_lock", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"local_temperature", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"current_heating_setpoint", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"leave_home", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"schedule_mode", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"scale_protection", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefNed__TZE284_ne4pikwm{
    .zigbee_models=kM__TZE284_ne4pikwm,.zigbee_models_count=sizeof(kM__TZE284_ne4pikwm)/sizeof(kM__TZE284_ne4pikwm[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kN__TZE284_ne4pikwm,.manufacturer_names_count=1,
    .model="TS0601__TZE284_ne4pikwm",.vendor="Nedis",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz__TZE284_ne4pikwm,
    .from_zigbee_count=sizeof(kFz__TZE284_ne4pikwm)/sizeof(kFz__TZE284_ne4pikwm[0]),
    .to_zigbee=kTz__TZE284_ne4pikwm,
    .to_zigbee_count=sizeof(kTz__TZE284_ne4pikwm)/sizeof(kTz__TZE284_ne4pikwm[0]),
    .configure=::zhc::tuya::extend::tuya_base_configure(),
    .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}  // namespace zhc::devices::nedis
