// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Sber SBDV-00029 — graduated from generated/ to fix a real parity gap.
// Smart motion sensor.
// z2m-source: sber.ts #SBDV-00029 — m.iasZoneAlarm({zoneType: "occupancy", ...}).
//
// PARITY FIX: the auto-generated port wired the generic kFzIasZone, which emits
// raw zoneStatus bits ("alarm_1"/"alarm_2"/"tamper"/"battery_low"). The expose
// list declared key "alarm" that no converter ever produces, so the motion
// state never reached the shadow. z2m's iasZoneAlarm with zoneType "occupancy"
// publishes the semantic key `occupancy`. There is no rename layer, so we wire
// the typed kFzIasMotionAlarm converter (zoneStatus bit 0 -> "occupancy", plus
// tamper + battery_low) and expose `occupancy` to match.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::sber {
namespace {
const FzConverter* const kFz_SBDV_00029[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasMotionAlarm,
};

constexpr const char* kModels_SBDV_00029[] = { "SM0202" };
constexpr const char* kManus_SBDV_00029[] = { "_TYZB01_2jzbhomb" };
}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SBDV_00029{
    .zigbee_models=kModels_SBDV_00029, .zigbee_models_count=sizeof(kModels_SBDV_00029)/sizeof(kModels_SBDV_00029[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus_SBDV_00029, .manufacturer_names_count=sizeof(kManus_SBDV_00029)/sizeof(kManus_SBDV_00029[0]),
    .model="SBDV-00029", .vendor="Sber",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SBDV_00029, .from_zigbee_count=sizeof(kFz_SBDV_00029)/sizeof(kFz_SBDV_00029[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::sber
