// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Soma SmartShades3 — graduated (cover tilt 0x0009 added).
// "Smart shades 3". z2m extend =
//   m.battery() + m.windowCovering({controls:["lift","tilt"]})
// One gap in the auto-port:
//   m.windowCovering({controls:["lift","tilt"]}) exposes BOTH position
//   (lift, attr 0x0008) AND tilt (currentPositionTiltPercentage, attr
//   0x0009), decodes both via fz.cover_position_tilt and writes both via
//   tz.cover_position_tilt. The port wired only kFzCoverPosition /
//   kTzCoverPosition (lift) and exposed only `position`, dropping the tilt
//   channel. Added kFzCoverTilt + kTzCoverPositionTilt + a `tilt` expose.
//   Lift and tilt both report on the same closuresWindowCovering (0x0102)
//   cluster, so the existing {1, 0x0102} bind already covers tilt.
//   Battery (battery + voltage via m.battery() / kFzBattery) was already
//   correctly ported — not a gap.
// z2m-source: soma.ts #SmartShades3.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::soma {
namespace {
const FzConverter* const kFz_SmartShades3[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
};
const TzConverter* const kTz_SmartShades3[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_SmartShades3[] = { "SmartShades3" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0102},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SmartShades3{
    .zigbee_models=kModels_SmartShades3, .zigbee_models_count=sizeof(kModels_SmartShades3)/sizeof(kModels_SmartShades3[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SmartShades3", .vendor="Soma",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SmartShades3, .from_zigbee_count=sizeof(kFz_SmartShades3)/sizeof(kFz_SmartShades3[0]),
    .to_zigbee=kTz_SmartShades3, .to_zigbee_count=sizeof(kTz_SmartShades3)/sizeof(kTz_SmartShades3[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::soma
