// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tnce TNCE_CLIMATE — hand-curated (was missing-decoder).
// Temperature and humidity sensor (TELINK TLSR82xx end-device). z2m wires
// m.temperature() + m.humidity() + m.battery() and the fingerprint declares
// inputClusters [0,3,32,1026,1029,1] (1026=msTemperatureMeasurement,
// 1029=msRelativeHumidity, 1=genPowerCfg). The auto-port lowered only
// kFzBattery, dropping BOTH environmental channels (their decoders, exposes
// and bindings). Added kFzTemperature (0x0402) + kFzHumidity (0x0405).
// z2m-source: tnce.ts #TNCE_CLIMATE.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tnce {
namespace {
const FzConverter* const kFz_TNCE_CLIMATE[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzHumidity,
};

constexpr const char* kModels_TNCE_CLIMATE[] = { "TLSR82xx" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0405},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_TNCE_CLIMATE{
    .zigbee_models=kModels_TNCE_CLIMATE, .zigbee_models_count=sizeof(kModels_TNCE_CLIMATE)/sizeof(kModels_TNCE_CLIMATE[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="TNCE_CLIMATE", .vendor="Tnce",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_TNCE_CLIMATE, .from_zigbee_count=sizeof(kFz_TNCE_CLIMATE)/sizeof(kFz_TNCE_CLIMATE[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tnce
