// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Futurehome TS0601 thermostat (Co020 / Heatit / FH-clones) —
// hand-ported from z2m's full DP map. Aggregates the three z2m
// fingerprints (`_TZE200_4hbx5cvx`, `_TZE200_e5hpkc6d`,
// `_TZE204_e5hpkc6d`) into one PreparedDefinition; the three per-manu
// `Fut__TZ*` Gen stubs are neutered.
//
// Parity fix: the original port dropped z2m DP 104 running_state
// (lookup{idle:false, heat:true}, exposed via withRunningState) — the
// thermostat declared a running-state surface that never decoded. Restored
// as a Bool→string lookup DP + running_state expose.
// z2m-source: futurehome.ts #TS0601_futurehome_thermostat.
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/dp.hpp"
#include "definitions/tuya/extend.hpp"
#include "definitions/tuya/factories.hpp"

namespace zhc::devices::futurehome {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kSystemMode[] = {
    { 0, "off" },
    { 1, "heat" },
};

constexpr ::zhc::tuya::TuyaEnumEntry kPreset[] = {
    { 0, "user" },
    { 1, "home" },
    { 2, "away" },
    { 3, "auto" },
};

constexpr ::zhc::tuya::TuyaEnumEntry kSensor[] = {
    { 0, "air_sensor" },
    { 1, "floor_sensor" },
    { 2, "max_guard" },
};

// z2m lookup({idle: false, heat: true}) over the boolean running_state DP
// (dp 104). Fanned to a string label via kTuyaDpFlagBoolEnum (keyed 0/1) so
// it decodes whether the device wire-types the DP as bool or enum.
constexpr ::zhc::tuya::TuyaEnumEntry kRunningState[] = {
    { 0, "idle" },
    { 1, "heat" },
};

struct cfg {
    static constexpr ::zhc::tuya::TuyaDpMapEntry e[] = {
        // dp 1 — system_mode (z2m: bool→enum lookup off/heat). We
        // emit it as an Enum DP since the wire payload is bool 0/1
        // and our extractor's enum decoder reads u8 values.
        ::zhc::tuya::dp::enum_lookup(1, "system_mode", kSystemMode, 2),
        ::zhc::tuya::dp::enum_lookup(2, "preset", kPreset, 4),
        ::zhc::tuya::dp::numeric(16, "current_heating_setpoint", 1),
        ::zhc::tuya::dp::numeric(24, "local_temperature", 1),
        ::zhc::tuya::dp::numeric(28, "local_temperature_calibration", 1),
        ::zhc::tuya::dp::binary(30, "child_lock"),
        ::zhc::tuya::dp::numeric(101, "local_temperature_floor", 1),
        ::zhc::tuya::dp::enum_lookup(102, "sensor", kSensor, 3),
        ::zhc::tuya::dp::numeric(103, "hysteresis", 1),
        // dp 104 — running_state (z2m: bool→string lookup idle/heat). Mapped
        // as a Bool DP fanned to a string label via kTuyaDpFlagBoolEnum so it
        // decodes regardless of the device wire-typing it bool or enum.
        { 104, "running_state", ::zhc::TuyaDpType::Bool, 1, kRunningState,
          sizeof(kRunningState) / sizeof(kRunningState[0]),
          ::zhc::tuya::kTuyaDpFlagBoolEnum },
        ::zhc::tuya::dp::binary(106, "window_detection"),
        ::zhc::tuya::dp::numeric(107, "max_temperature_protection", 1),
        // dp 123 — energy (kWh × 100). z2m wraps this in a custom
        // monotonic-counter guard host-side; we expose the raw
        // counter and let the shadow handle deduping.
        ::zhc::tuya::dp::numeric(123, "energy", 100),
    };
    static constexpr ::zhc::tuya::TuyaDatapointMap dp_map{ e, 13 };
};

using FX = ::zhc::tuya::factory::TuyaOnOff<cfg>;

constexpr const char* kModels[] = { "TS0601" };
constexpr const char* kManus[] = {
    "_TZE200_4hbx5cvx",
    "_TZE200_e5hpkc6d",
    "_TZE204_e5hpkc6d",
};

}  // namespace

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"system_mode", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"preset", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"current_heating_setpoint", ExposeType::Numeric, Access::StateSet, "°C", nullptr, nullptr, 0},
    {"local_temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"local_temperature_calibration", ExposeType::Numeric, Access::StateSet, "°C", nullptr, nullptr, 0},
    {"child_lock", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"local_temperature_floor", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"sensor", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"hysteresis", ExposeType::Numeric, Access::StateSet, "°C", nullptr, nullptr, 0},
    // z2m withRunningState(["idle","heat"], ea.STATE) — read-only enum.
    {"running_state", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"window_detection", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"max_temperature_protection", ExposeType::Numeric, Access::StateSet, "°C", nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0601_futurehome_thermostat[] = {
    {"Futurehome","Co020"},
};
extern const PreparedDefinition kDef_TS0601_futurehome_thermostat{
    .zigbee_models=kModels, .zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus, .manufacturer_names_count=sizeof(kManus)/sizeof(kManus[0]),
    .model="TS0601_futurehome_thermostat", .vendor="Futurehome",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0601_futurehome_thermostat, .white_labels_count=sizeof(kWhiteLabels_TS0601_futurehome_thermostat)/sizeof(kWhiteLabels_TS0601_futurehome_thermostat[0]),
    .from_zigbee=FX::fz_list, .from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list, .to_zigbee_count=FX::tz_count,
    .configure=::zhc::tuya::extend::tuya_base_configure(), .on_event=nullptr,
    .bindings=kAutoBindings, .bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::futurehome