// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Weten "PCI E" — Remote Control PCI E Card for PC (Tuya TS0601 DP).
//
// Consolidates what the generator emitted as three colliding artifacts for the
// single z2m "PCI E" device:
//   - Wet_PCI_E.cpp        : a MISROUTED bare genOnOff def (cluster 0x0006) for
//                            both _TZE* names — wrong for a 0xEF00 DP device.
//   - Wet__TZE204_6fk3gewc : correct DP map, but split into a model-only def
//   - Wet__TZE284_6fk3gewc : byte-identical DP map for the sibling mfr name
// into ONE def carrying both manufacturer names, the z2m white-label, the real
// model name "PCI E", and the full DP map.
//
// Real decode fix: DP101 restart_mode lost two of its three enum values. z2m
// wires {restart:0, "force restart":1, "–":2}; the generator emitted only
// {0:"restart"}, so a "force restart" (1) or "–" (2) report silently dropped.
//
// z2m-source: zigbee-herdsman-converters/src/devices/weten.ts #PCI E.
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"
namespace zhc::devices::weten {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kEnum_PCI_E_restart_mode_dp101[] = {
    { 0, "restart" },
    { 1, "force restart" },
    { 2, "\xe2\x80\x93" },  // z2m label "–" (U+2013 en dash), UTF-8.
};

constexpr ::zhc::tuya::TuyaEnumEntry kEnum_PCI_E_rf_remote_control_dp102[] = {
    { 0, "ON" },
    { 1, "OFF" },
};

constexpr ::zhc::tuya::TuyaEnumEntry kEnum_PCI_E_power_on_behavior_dp105[] = {
    { 0, "off" },
    { 1, "on" },
};

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries_PCI_E[] = {
    { 1, "state", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 101, "restart_mode", ::zhc::TuyaDpType::Enum, 1, kEnum_PCI_E_restart_mode_dp101, sizeof(kEnum_PCI_E_restart_mode_dp101)/sizeof(kEnum_PCI_E_restart_mode_dp101[0]) },
    { 102, "rf_remote_control", ::zhc::TuyaDpType::Enum, 1, kEnum_PCI_E_rf_remote_control_dp102, sizeof(kEnum_PCI_E_rf_remote_control_dp102)/sizeof(kEnum_PCI_E_rf_remote_control_dp102[0]) },
    { 103, "rf_pairing", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 104, "buzzer_feedback", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 105, "power_on_behavior", ::zhc::TuyaDpType::Enum, 1, kEnum_PCI_E_power_on_behavior_dp105, sizeof(kEnum_PCI_E_power_on_behavior_dp105)/sizeof(kEnum_PCI_E_power_on_behavior_dp105[0]) },
    { 106, "child_lock", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap_PCI_E{ kEntries_PCI_E, 7 };
constexpr FzConverter kFzDp_PCI_E{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap_PCI_E,
};
const FzConverter* const kFz_PCI_E[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDp_PCI_E,
};
constexpr TzConverter kTzDp_PCI_E{
    .key         = nullptr,                // wildcard — claims any mapped key
    .cluster     = "manuSpecificTuya",
    .cluster_id  = 0xEF00,
    .command_id  = 0x00,
    .fn          = &::zhc::tuya::tz_tuya_datapoints,
    .user_config = &kMap_PCI_E,
};
const TzConverter* const kTz_PCI_E[] = { &kTzDp_PCI_E };
constexpr const char* kM_PCI_E[] = { "TS0601" };
constexpr const char* kN_PCI_E[] = { "_TZE204_6fk3gewc", "_TZE284_6fk3gewc" };
}  // namespace

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"restart_mode", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"rf_remote_control", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"rf_pairing", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"buzzer_feedback", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"child_lock", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

constexpr WhiteLabel kWhiteLabels_PCI_E[] = {
    {"Weten","Tuya PRO"},
};

extern const PreparedDefinition kDef_PCI_E{
    .zigbee_models=kM_PCI_E,.zigbee_models_count=sizeof(kM_PCI_E)/sizeof(kM_PCI_E[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kN_PCI_E,.manufacturer_names_count=sizeof(kN_PCI_E)/sizeof(kN_PCI_E[0]),
    .model="PCI E",.vendor="Weten",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_PCI_E,.white_labels_count=sizeof(kWhiteLabels_PCI_E)/sizeof(kWhiteLabels_PCI_E[0]),
    .from_zigbee=kFz_PCI_E,
    .from_zigbee_count=sizeof(kFz_PCI_E)/sizeof(kFz_PCI_E[0]),
    .to_zigbee=kTz_PCI_E,
    .to_zigbee_count=sizeof(kTz_PCI_E)/sizeof(kTz_PCI_E[0]),
    .configure=::zhc::tuya::extend::tuya_base_configure(),
    .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}  // namespace zhc::devices::weten
