// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Imou ZTM1-EN — temperature/humidity sensor (missing-channel fix).
// Temperature and humidity sensor
// z2m-source: imou.ts #ZTM1-EN — m.battery() + m.temperature() + m.humidity().
//
// The generated def kept only m.battery() — it dropped the two primary
// channels (temperature via msTemperatureMeasurement 0x0402,
// humidity via msRelativeHumidity 0x0405), leaving a "temperature &
// humidity sensor" that reported neither. Wire the generic
// kFzTemperature + kFzHumidity decoders, add the exposes and the
// matching report bindings.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::imou {
namespace {
const FzConverter* const kFz_ZTM1_EN[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzHumidity,
};

constexpr const char* kModels_ZTM1_EN[] = { "ZTM1-EN" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0405},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZTM1_EN{
    .zigbee_models=kModels_ZTM1_EN, .zigbee_models_count=sizeof(kModels_ZTM1_EN)/sizeof(kModels_ZTM1_EN[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZTM1-EN", .vendor="Imou",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZTM1_EN, .from_zigbee_count=sizeof(kFz_ZTM1_EN)/sizeof(kFz_ZTM1_EN[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::imou
