// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: ThirdReality 3RSMR01067Z — graduated from generated/.
// Smart motion sensor R1.
// z2m-source: third_reality.ts #3RSMR01067Z —
// m.iasZoneAlarm({zoneType: "occupancy", zoneAttributes: ["alarm_1", "battery_low"]}).
// Parity fix: the generated def lowered the generic kFzIasZone (bare "alarm")
// for a motion sensor whose state must surface as "occupancy". Swapped to the
// typed kFzIasMotionAlarm (zoneStatus bit 0 → "occupancy", + tamper/battery_low)
// and renamed the expose key.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::third_reality {
namespace {
const FzConverter* const kFz_D3RSMR01067Z[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasMotionAlarm,
};

constexpr const char* kModels_D3RSMR01067Z[] = { "3RSMR01067Z" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D3RSMR01067Z{
    .zigbee_models=kModels_D3RSMR01067Z, .zigbee_models_count=sizeof(kModels_D3RSMR01067Z)/sizeof(kModels_D3RSMR01067Z[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="3RSMR01067Z", .vendor="ThirdReality",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D3RSMR01067Z, .from_zigbee_count=sizeof(kFz_D3RSMR01067Z)/sizeof(kFz_D3RSMR01067Z[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::third_reality
