// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: ThirdReality 3RSNL02043Z — graduated from generated/.
// Zigbee multi-function night light (dimmable light + motion sensor).
// z2m-source: third_reality.ts #3RSNL02043Z —
// fromZigbee: [fzLocal.thirdreality_private_motion_sensor, fz.ias_occupancy_alarm_1_report]
// → occupancy from ssIasZone zoneStatus bit 0.
// Parity fix: the generated def lowered the generic kFzIasZone (bare "alarm")
// while the motion half of this device must surface as "occupancy". Swapped to
// the typed kFzIasMotionAlarm (zoneStatus bit 0 → "occupancy", + tamper/
// battery_low) and renamed the expose key; the genOnOff/genLevelCtrl light path
// is unchanged.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::third_reality {
namespace {
const FzConverter* const kFz_D3RSNL02043Z[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzIasMotionAlarm,
};
const TzConverter* const kTz_D3RSNL02043Z[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
};
constexpr const char* kModels_D3RSNL02043Z[] = { "3RSNL02043Z" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D3RSNL02043Z{
    .zigbee_models=kModels_D3RSNL02043Z, .zigbee_models_count=sizeof(kModels_D3RSNL02043Z)/sizeof(kModels_D3RSNL02043Z[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="3RSNL02043Z", .vendor="ThirdReality",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D3RSNL02043Z, .from_zigbee_count=sizeof(kFz_D3RSNL02043Z)/sizeof(kFz_D3RSNL02043Z[0]),
    .to_zigbee=kTz_D3RSNL02043Z, .to_zigbee_count=sizeof(kTz_D3RSNL02043Z)/sizeof(kTz_D3RSNL02043Z[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::third_reality
