// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Yale LIA — auto-generated.
// Digital Lock Lia
// Parity fix: z2m lockExtend() bundles fz.battery + e.battery();
// generated def dropped it. Added kFzBattery + battery expose + genPowerCfg bind.
//
// z2m v26.115.0 (#13341) adds lia_action: the operation event notification
// (closuresDoorLock 0x20) -> action, action_source(_name), action_user. The
// frame fails herdsman's ZCL parse, so z2m reads it raw; here the event
// decoder reads the body by offset anyway. Source 4 is the fingerprint reader
// on this lock (the ZCL table calls it "indeterminate").
// z2m-source: yale.ts #LIA.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::yale {
namespace {
bool fz_lia_operation_event(const DecodedMessage& msg, const FzConverter& self, const PreparedDefinition& def,
                            RuntimeContext& ctx, FixedPayload<ZHC_FIXED_PAYLOAD_CAP>& out) {
    if (!::zhc::generic::kFzLockOperationEvent.fn.zcl_fn(msg, self, def, ctx, out)) return false;
    if (!msg.raw_body.empty() && msg.raw_body[0] == 4) {
        Value v{}; v.type = ValueType::StringRef; v.str = "fingerprint";
        out.put("action_source_name", v);
    }
    return true;
}
constexpr FzConverter kFzLiaAction{
    .family            = FrameFamily::Zcl,
    .cluster           = "closuresDoorLock",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = 0x20,   // operationEventNotification
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .zcl_fn = fz_lia_operation_event },
    .user_config       = nullptr,
};
const FzConverter* const kFz_LIA[] = {
    &::zhc::generic::kFzLock,
    &::zhc::generic::kFzBattery,
    &kFzLiaAction,
};
const TzConverter* const kTz_LIA[] = {
    &::zhc::generic::kTzLock,
};
constexpr const char* kModels_LIA[] = { "LIA" };

}  // namespace


constexpr const char* kSourceNames[] = { "keypad", "rf", "manual", "rfid", "fingerprint" };
// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"lock_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_source_name", ExposeType::Enum, Access::State, nullptr, nullptr, kSourceNames, 5},
    {"action_user", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0101},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_LIA{
    .zigbee_models=kModels_LIA, .zigbee_models_count=sizeof(kModels_LIA)/sizeof(kModels_LIA[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="LIA", .vendor="Yale",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_LIA, .from_zigbee_count=sizeof(kFz_LIA)/sizeof(kFz_LIA[0]),
    .to_zigbee=kTz_LIA, .to_zigbee_count=sizeof(kTz_LIA)/sizeof(kTz_LIA[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::yale
