// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Yale YMF40/YDM4109+/YDF40 — auto-generated.
// Real living lock / Intelligent biometric digital lock
// Parity fix: z2m lockExtend() bundles fz.battery + e.battery();
// generated def dropped it. Added kFzBattery + battery expose + genPowerCfg bind.
// z2m-source: yale.ts #YMF40/YDM4109+/YDF40.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::yale {
namespace {
const FzConverter* const kFz_YMF40_YDM4109__YDF40[] = {
    &::zhc::generic::kFzLock,
    &::zhc::generic::kFzBattery,
};
const TzConverter* const kTz_YMF40_YDM4109__YDF40[] = {
    &::zhc::generic::kTzLock,
};
constexpr const char* kModels_YMF40_YDM4109__YDF40[] = { "iZBModule01", "0700000001" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"lock_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0101},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_YMF40_YDM4109__YDF40{
    .zigbee_models=kModels_YMF40_YDM4109__YDF40, .zigbee_models_count=sizeof(kModels_YMF40_YDM4109__YDF40)/sizeof(kModels_YMF40_YDM4109__YDF40[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="YMF40/YDM4109+/YDF40", .vendor="Yale",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_YMF40_YDM4109__YDF40, .from_zigbee_count=sizeof(kFz_YMF40_YDM4109__YDF40)/sizeof(kFz_YMF40_YDM4109__YDF40[0]),
    .to_zigbee=kTz_YMF40_YDM4109__YDF40, .to_zigbee_count=sizeof(kTz_YMF40_YDM4109__YDF40)/sizeof(kTz_YMF40_YDM4109__YDF40[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::yale
