// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Yale YRD226/246 TSDB — auto-generated.
// Assure lock
// Parity fix: z2m lockExtend() bundles fz.battery + e.battery();
// generated def dropped it. Added kFzBattery + battery expose + genPowerCfg bind.
// z2m-source: yale.ts #YRD226/246 TSDB.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::yale {
namespace {
const FzConverter* const kFz_YRD226_246_TSDB[] = {
    &::zhc::generic::kFzLock,
    &::zhc::generic::kFzBattery,
};
const TzConverter* const kTz_YRD226_246_TSDB[] = {
    &::zhc::generic::kTzLock,
};
constexpr const char* kModels_YRD226_246_TSDB[] = { "YRD226/246 TSDB" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"lock_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0101},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_YRD226_246_TSDB{
    .zigbee_models=kModels_YRD226_246_TSDB, .zigbee_models_count=sizeof(kModels_YRD226_246_TSDB)/sizeof(kModels_YRD226_246_TSDB[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="YRD226/246 TSDB", .vendor="Yale",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_YRD226_246_TSDB, .from_zigbee_count=sizeof(kFz_YRD226_246_TSDB)/sizeof(kFz_YRD226_246_TSDB[0]),
    .to_zigbee=kTz_YRD226_246_TSDB, .to_zigbee_count=sizeof(kTz_YRD226_246_TSDB)/sizeof(kTz_YRD226_246_TSDB[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::yale
