// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Yale YAYRD256HA2619 — auto-generated.
// Assure lock SL
// Parity fix: z2m lockExtend() bundles fz.battery + e.battery();
// generated def dropped it. Added kFzBattery + battery expose + genPowerCfg bind.
// z2m-source: yale.ts #YAYRD256HA2619.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::yale {
namespace {
const FzConverter* const kFz_YAYRD256HA2619[] = {
    &::zhc::generic::kFzLock,
    &::zhc::generic::kFzBattery,
};
const TzConverter* const kTz_YAYRD256HA2619[] = {
    &::zhc::generic::kTzLock,
};
constexpr const char* kModels_YAYRD256HA2619[] = { "YRD256-TSDB" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"lock_state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0101},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_YAYRD256HA2619{
    .zigbee_models=kModels_YAYRD256HA2619, .zigbee_models_count=sizeof(kModels_YAYRD256HA2619)/sizeof(kModels_YAYRD256HA2619[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="YAYRD256HA2619", .vendor="Yale",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_YAYRD256HA2619, .from_zigbee_count=sizeof(kFz_YAYRD256HA2619)/sizeof(kFz_YAYRD256HA2619[0]),
    .to_zigbee=kTz_YAYRD256HA2619, .to_zigbee_count=sizeof(kTz_YAYRD256HA2619)/sizeof(kTz_YAYRD256HA2619[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::yale
