// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Lincukoo SZLMR10 radar for _TZE284_sndkanfr (z2m v26.115.1 window).
// The model's datapoints live in a per-manufacturer generated copy
// (_TZE204_sndkanfr); this is a hand-written copy of it for the new member.
// z2m-source: lincukoo.ts #SZLMR10.
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"
namespace zhc::devices::lincukoo {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kEnum__TZE284_sndkanfr_work_mode_dp104[] = {
    { 0, "pir_mode" },
    { 1, "radar_mode" },
    { 2, "combine_mode" },
};

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries__TZE284_sndkanfr[] = {
    { 1, "presence", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, ::zhc::tuya::kTuyaDpFlagInvertBool },
    { 20, "illuminance", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 13, "detection_distance", ::zhc::TuyaDpType::Numeric, 100, nullptr, 0, 0 },
    { 16, "radar_sensitivity", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 103, "fading_time", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 101, "indicator", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 102, "radar_switch", ::zhc::TuyaDpType::Bool, 1, nullptr, 0, 0 },
    { 104, "work_mode", ::zhc::TuyaDpType::Enum, 1, kEnum__TZE284_sndkanfr_work_mode_dp104, sizeof(kEnum__TZE284_sndkanfr_work_mode_dp104)/sizeof(kEnum__TZE284_sndkanfr_work_mode_dp104[0]) },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap__TZE284_sndkanfr{ kEntries__TZE284_sndkanfr, sizeof(kEntries__TZE284_sndkanfr)/sizeof(kEntries__TZE284_sndkanfr[0]) };
constexpr FzConverter kFzDp__TZE284_sndkanfr{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap__TZE284_sndkanfr,
};
const FzConverter* const kFz__TZE284_sndkanfr[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDp__TZE284_sndkanfr,
};
constexpr TzConverter kTzDp__TZE284_sndkanfr{
    .key         = nullptr,                // wildcard — claims any mapped key
    .cluster     = "manuSpecificTuya",
    .cluster_id  = 0xEF00,
    .command_id  = 0x00,
    .fn          = &::zhc::tuya::tz_tuya_datapoints,
    .user_config = &kMap__TZE284_sndkanfr,
};
const TzConverter* const kTz__TZE284_sndkanfr[] = { &kTzDp__TZE284_sndkanfr };
constexpr const char* kM__TZE284_sndkanfr[] = { "TS0601" };
constexpr const char* kN__TZE284_sndkanfr[] = { "_TZE284_sndkanfr" };
}  // namespace

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"presence", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"illuminance", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"detection_distance", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"radar_sensitivity", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"fading_time", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"indicator", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"radar_switch", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"work_mode", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SZLMR10_TZE284_sndkanfr{
    .zigbee_models=kM__TZE284_sndkanfr,.zigbee_models_count=sizeof(kM__TZE284_sndkanfr)/sizeof(kM__TZE284_sndkanfr[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kN__TZE284_sndkanfr,.manufacturer_names_count=sizeof(kN__TZE284_sndkanfr)/sizeof(kN__TZE284_sndkanfr[0]),
    .model="SZLMR10",.vendor="Lincukoo",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz__TZE284_sndkanfr,
    .from_zigbee_count=sizeof(kFz__TZE284_sndkanfr)/sizeof(kFz__TZE284_sndkanfr[0]),
    .to_zigbee=kTz__TZE284_sndkanfr,
    .to_zigbee_count=sizeof(kTz__TZE284_sndkanfr)/sizeof(kTz__TZE284_sndkanfr[0]),
    .configure=::zhc::tuya::extend::tuya_base_configure(),
    .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}  // namespace zhc::devices::lincukoo
