// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Ynoa 8718801528273 — hand-curated (CCT half was dead).
// Smart LED GU10 CCT. z2m `m.light({colorTemp:{range:[153,454]}})` — a
// tunable-white bulb. The auto-port wired only OnOff + Brightness and
// dropped the color-temperature axis (read + write). Added
// kFzColorTemperature / kTzColorTemp + the `color_temp` expose + the
// lightingColorCtrl (0x0300) binding.
// z2m-source: ynoa.ts #8718801528273.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::ynoa {
namespace {
const FzConverter* const kFz_D8718801528273[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzColorTemperature,
};
const TzConverter* const kTz_D8718801528273[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzColorTemp,
};
constexpr const char* kModels_D8718801528273[] = { "ZBT-CCTLight-GU100001" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"color_temp", ExposeType::Numeric, Access::StateSet, "mired", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0300},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D8718801528273{
    .zigbee_models=kModels_D8718801528273, .zigbee_models_count=sizeof(kModels_D8718801528273)/sizeof(kModels_D8718801528273[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="8718801528273", .vendor="Ynoa",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D8718801528273, .from_zigbee_count=sizeof(kFz_D8718801528273)/sizeof(kFz_D8718801528273[0]),
    .to_zigbee=kTz_D8718801528273, .to_zigbee_count=sizeof(kTz_D8718801528273)/sizeof(kTz_D8718801528273[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::ynoa
