// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara CTP-R01 cube T1 Pro.
//
// Similar to MFKZQ01LM but with its own per-value map: CTP-R01 sides are
// 1-based, adds `hold` / `1_min_inactivity` / `flip_to_side`.
//
// z2m-source: lumi.ts #CTP-R01 (lumi.remote.cagl02).

#include "definitions/lumi/_shared.hpp"
namespace zhc::devices::lumi {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::lumi::kFzLumiCTPR01Multistate,
    &::zhc::lumi::kFzLumiCubeAnalog,
};
constexpr const char* kModels[] = { "lumi.remote.cagl02" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0012},
    {1, 0x000C},
};
// --- end auto-generated block ---



constexpr WhiteLabel kWhiteLabels_CTPR01[] = {
    {"Aqara","MFCZQ12LM"},
};
extern const PreparedDefinition kDefCTPR01{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="CTP-R01",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=kWhiteLabels_CTPR01, .white_labels_count=sizeof(kWhiteLabels_CTPR01)/sizeof(kWhiteLabels_CTPR01[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
