// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Aqara GZCGQ01LM illuminance sensor.
// Standard msIlluminanceMeasurement attr 0x0000 (u16 lux log) via
// `m::Numeric` with divisor 1 — z2m applies a log transform later but
// raw lux pass-through is sufficient for v1.
// z2m-source: lumi.ts #GZCGQ01LM (lumi.sen_ill.mgl01).

#include "definitions/lumi/_shared.hpp"
#include "zhc/modern_extend.hpp"

namespace zhc::devices::lumi {
namespace {
struct illum_opts {
    static constexpr const char*   name    = "illuminance";
    static constexpr const char*   unit    = "lux";
    static constexpr const char*   cluster = "msIlluminanceMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 1;
};
using Lux = ::zhc::m::Numeric<illum_opts>;

const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &Lux::converter,
};
constexpr const char* kModels[] = { "lumi.sen_ill.mgl01" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefGZCGQ01LM{
    .zigbee_models = kModels, .zigbee_models_count = 1,
    .model = "GZCGQ01LM", .vendor = "Xiaomi",
    .meta = nullptr,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
