// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 3: Xiaomi JTYJ-GD-01LM/BW smoke sensor (Honeywell co-brand).
//
// Fire alarm arrives as an IAS zone status change: z2m lumi_smoke =
// ias_smoke_alarm_1 (+ a `test` bit, not ported). The note here said it was
// blocked on an IAS handler that has since landed, and no IAS converter was
// wired, so smoke alarms were never decoded. Battery comes in the Lumi TLV.
//
// z2m-source: lumi.ts #JTYJ-GD-01LM/BW (lumi.sensor_smoke).

#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"

namespace zhc::devices::lumi {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::generic::kFzIasSmokeAlarm,
};
constexpr const char* kModels[] = { "lumi.sensor_smoke" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"smoke", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefJTYJGD01LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .model = "JTYJGD01LM", .vendor = "Xiaomi",
    .meta = nullptr,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
