// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Aqara LLKZMK12LM — auto-generated stub.
// z2m-source: lumi.ts #LLKZMK12LM.
#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"
namespace zhc::devices::lumi {
namespace {
struct E { static constexpr ::zhc::lumi::DeviceEndpointLabel e[]={{1,"state_l1"}, {2,"state_l2"}};
          static constexpr ::zhc::lumi::DeviceEndpointLabels map{e,2}; };
// What z2m adds on top of the factory bundle (factories.hpp NoExtras).
struct X : ::zhc::lumi::factory::NoExtras {
    static constexpr std::array<const FzConverter*, 2> fz{{
        &::zhc::lumi::kFzLumiHeartbeat,
        &::zhc::lumi::kFzLumiOperationMode,
    }};
    static constexpr std::array<const TzConverter*, 2> tz{{
        &::zhc::lumi::kTzLumiOperationModeL1,
        &::zhc::lumi::kTzLumiOperationModeL2,
    }};
};
using FX = ::zhc::lumi::factory::LumiOnOff<E, X>;
constexpr const char* kModels[] = { "lumi.switch.acn047" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"operation_mode_l1", ExposeType::Enum, Access::StateSet, nullptr,
     "Decoupled mode for 1st relay",
     ::zhc::lumi::kLumiOperationModeValues, std::size(::zhc::lumi::kLumiOperationModeValues), ExposeCategory::Config},
    {"operation_mode_l2", ExposeType::Enum, Access::StateSet, nullptr,
     "Decoupled mode for 2nd relay",
     ::zhc::lumi::kLumiOperationModeValues, std::size(::zhc::lumi::kLumiOperationModeValues), ExposeCategory::Config},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_LLKZMK12LM[] = {
    {"Aqara","DCM-K01"},
};
extern const PreparedDefinition kDefLLKZMK12LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="LLKZMK12LM",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_LLKZMK12LM, .white_labels_count=sizeof(kWhiteLabels_LLKZMK12LM)/sizeof(kWhiteLabels_LLKZMK12LM[0]),
    .from_zigbee=FX::fz_list,.from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list,.to_zigbee_count=FX::tz_count,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
