// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Xiaomi Mi Cube MFKZQ01LM.
//
// Emits z2m-parity actions:
//   genMultistateInput attr 0x0055 — shake / throw / wakeup / fall
//     + flip90 (from_side/to_side) / flip180 / slide / tap (with `side`)
//   genAnalogInput   attr 0x0055  — rotate_left / rotate_right + angle.
//   genBasic         attr 0xFF01  — battery / voltage / device_temperature
//                                     via kFzLumiBasic.
//
// z2m-source: lumi.ts #MFKZQ01LM (lumi.sensor_cube).

#include "definitions/lumi/_shared.hpp"
namespace zhc::devices::lumi {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::lumi::kFzLumiCubeMultistate,
    &::zhc::lumi::kFzLumiCubeAnalog,
};
constexpr const char* kModels[] = { "lumi.sensor_cube", "lumi.sensor_cube.aqgl01" };
}

// --- auto-generated by emit_expose_bindings.py (manually extended:
//     action is Enum (not Binary), plus side / from_side / to_side /
//     action_* / angle / action_angle exposed by the cube converters
//     so the UI renders them as read-only labels) ---
constexpr const char* kActions_MFKZQ01LM[] = {
    "shake", "throw", "wakeup", "fall", "hold",
    "flip90", "flip180", "slide", "tap",
    "rotate_left", "rotate_right",
};

constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action",            ExposeType::Enum,    Access::State, nullptr, nullptr,
     kActions_MFKZQ01LM, sizeof(kActions_MFKZQ01LM)/sizeof(kActions_MFKZQ01LM[0])},
    {"side",              ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"from_side",         ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"to_side",           ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_from_side",  ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_to_side",    ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_side",       ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"angle",             ExposeType::Numeric, Access::State, "deg", nullptr, nullptr, 0},
    {"action_angle",      ExposeType::Numeric, Access::State, "deg", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0012},
    {1, 0x000C},
};
// --- end auto-generated block ---



constexpr WhiteLabel kWhiteLabels_MFKZQ01LM[] = {
    {"Xiaomi","MFKZQ01LM"},
};
extern const PreparedDefinition kDefMFKZQ01LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="MFKZQ01LM",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=kWhiteLabels_MFKZQ01LM, .white_labels_count=sizeof(kWhiteLabels_MFKZQ01LM)/sizeof(kWhiteLabels_MFKZQ01LM[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
