// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: uses shared lumi converters.
//
// z2m-source: zigbee-herdsman-converters/src/devices/lumi.ts —
// RTCGQ11LM ("Aqara human body sensor"). Second-device sanity port
// for Task 6; produced by walking the porter checklist without
// diverging from the cookbook-shaped translation steps.

#include "definitions/lumi/_shared.hpp"
#include "zhc/runtime/definition.hpp"

namespace zhc::devices::lumi {

namespace {

const char* const kZigbeeModels[] = { "lumi.sensor_motion.aq2" };

const FzConverter* const kFromZigbee[] = {
    &zhc::lumi::kFzLumiBasic,   // battery / voltage / device_temperature
    &zhc::lumi::kFzOccupancy,    // occupancy bool on msOccupancySensing
};

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0406},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefRTCGQ11LM{
    .zigbee_models       = kZigbeeModels,
    .zigbee_models_count = sizeof(kZigbeeModels) / sizeof(kZigbeeModels[0]),
    .model              = "RTCGQ11LM",
    .vendor             = "Aqara",
    .meta               = nullptr,
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels       = nullptr,
    .white_labels_count = 0,
    .from_zigbee        = kFromZigbee,
    .from_zigbee_count  = sizeof(kFromZigbee) / sizeof(kFromZigbee[0]),
    .to_zigbee          = nullptr,
    .to_zigbee_count    = 0,
    .configure          = nullptr,
    .on_event           = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::lumi
