// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara SP-EUC01 smart plug (EU, metering).
// z2m-source: lumi.ts #SP-EUC01 (lumi.plug.maeu03).
#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"
namespace zhc::devices::lumi {
namespace {
struct C { static constexpr ::zhc::lumi::LumiPowerCalibration power{1,1000,10};
           static constexpr ::zhc::lumi::LumiMeterCalibration meter{1000}; };
// What z2m adds on top of the factory bundle (factories.hpp NoExtras).
struct X : ::zhc::lumi::factory::NoExtras {
    static constexpr std::array<const FzConverter*, 2> fz{{
        &::zhc::lumi::kFzLumiHeartbeat,
        &::zhc::lumi::kFzLumiSettings,   // its settings read back, button_lock among them
    }};
    static constexpr std::array<const TzConverter*, 1> tz{{
        &::zhc::lumi::kTzLumiButtonLock,
    }};
};
using FX = ::zhc::lumi::factory::LumiPower<C, X>;
constexpr const char* kModels[] = { "lumi.plug.maeu01", "lumi.plug.maeu03" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"button_lock", ExposeType::Binary, Access::StateSet, nullptr,
     "Disables the physical switch button", nullptr, 0, ExposeCategory::Config},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
    {1, 0x0B04},
    {1, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefSPEUC01{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),.model="SP-EUC01",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=FX::fz_list,.from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list,.to_zigbee_count=FX::tz_count,
    .configure=nullptr,.on_event=nullptr,
    .bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    // z2m SP-EUC01 configure: reporting.bind(genOnOff) +
    // reporting.onOff(endpoint), plus a metering branch
    // reporting.bind(seMetering) + reporting.currentSummDelivered.
    // z2m deliberately does NOT configureReporting V/I/P here.
    .reports=::zhc::lumi::kReportsLumiOnOffEnergy,
    .reports_count=::zhc::lumi::kReportsLumiOnOffEnergyCount,
    // z2m: manuSpecificLumi mode (0x0009) = 1, "event", at configure.
    .config_steps = ::zhc::lumi::kConfigStepsLumiEventMode,
    .config_steps_count = std::size(::zhc::lumi::kConfigStepsLumiEventMode),
};
}
