// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 3: Aqara SP-PDC01 power-disable contactor.
// Simple on/off via generic path + lumi_basic.
// z2m-source: lumi.ts #SP-PDC01 (lumi.relay.pdc01).
#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"
namespace zhc::devices::lumi {
namespace {
const FzConverter* const kFz[] = { &::zhc::lumi::kFzLumiBasic, &::zhc::generic::kFzOnOff };
constexpr const char* kModels[] = { "lumi.relay.pdc01" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefSPPDC01{
    .zigbee_models=kModels,.zigbee_models_count=1,.model="SP-PDC01",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
