// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WSDCGQ11LM temperature/humidity/pressure sensor.
//
// Three streams land on standard ms-* clusters AND via lumi_specific
// TLV on genBasic. Both paths agree on scaling (/100) — we listen to
// both so reports from either direction don't get silently dropped.
//
// z2m-source: lumi.ts #WSDCGQ11LM (lumi.weather).

#include "definitions/lumi/_shared.hpp"
#include "zhc/modern_extend.hpp"

namespace zhc::devices::lumi {
namespace {

// Standard ms-cluster paths, via modern-extend Numeric helpers.
struct ms_temp_opts {
    static constexpr const char*   name    = "temperature";
    static constexpr const char*   unit    = "C";
    static constexpr const char*   cluster = "msTemperatureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct ms_humidity_opts {
    static constexpr const char*   name    = "humidity";
    static constexpr const char*   unit    = "%";
    static constexpr const char*   cluster = "msRelativeHumidity";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct ms_pressure_opts {
    static constexpr const char*   name    = "pressure";
    static constexpr const char*   unit    = "hPa";
    static constexpr const char*   cluster = "msPressureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 1;
};
using Temp     = ::zhc::m::Numeric<ms_temp_opts>;
using Humidity = ::zhc::m::Numeric<ms_humidity_opts>;
using Pressure = ::zhc::m::Numeric<ms_pressure_opts>;

// Lumi TLV path — covers the same three values on the consolidated
// 0xFF01 attr report.
constexpr ::zhc::lumi::LumiTagEntry kTagEntries[] = {
    { ::zhc::lumi::kLumiTagVoltage,     "voltage",            1   },
    { ::zhc::lumi::kLumiTagDeviceTemp,  "device_temperature", 1   },
    { ::zhc::lumi::kLumiTagOutageCount, "power_outage_count", 1   },
    { ::zhc::lumi::kLumiTagState,       "temperature",        100 },
    { ::zhc::lumi::kLumiTagHumidity,    "humidity",           100 },
    { ::zhc::lumi::kLumiTagPressure,    "pressure",           100 },
};
constexpr ::zhc::lumi::LumiTagMap kTagMap{
    kTagEntries, sizeof(kTagEntries)/sizeof(kTagEntries[0]),
};

const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::lumi::kFzLumiSpecific,
    &Temp::converter,
    &Humidity::converter,
    &Pressure::converter,
};

constexpr const char* kModels[] = { "lumi.weather" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefWSDCGQ11LM{
    .zigbee_models = kModels, .zigbee_models_count = 1,
    .model = "WSDCGQ11LM", .vendor = "Xiaomi",
    .meta = &kTagMap,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
