// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WSDCGQ21LM temp/humidity/pressure sensor (T1 Pro).
// Same shape as WSDCGQ12LM with a newer zigbeeModel.
// z2m-source: lumi.ts #WSDCGQ21LM (lumi.weather.agl01).
#include "definitions/lumi/_shared.hpp"
#include "zhc/modern_extend.hpp"
namespace zhc::devices::lumi {
namespace {
struct temp_opts {
    static constexpr const char*   name    = "temperature";
    static constexpr const char*   unit    = "C";
    static constexpr const char*   cluster = "msTemperatureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct humidity_opts {
    static constexpr const char*   name    = "humidity";
    static constexpr const char*   unit    = "%";
    static constexpr const char*   cluster = "msRelativeHumidity";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct pressure_opts {
    static constexpr const char*   name    = "pressure";
    static constexpr const char*   unit    = "hPa";
    static constexpr const char*   cluster = "msPressureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 1;
};
using Temp     = ::zhc::m::Numeric<temp_opts>;
using Humidity = ::zhc::m::Numeric<humidity_opts>;
using Pressure = ::zhc::m::Numeric<pressure_opts>;

constexpr ::zhc::lumi::LumiTagEntry kTagEntries[] = {
    { ::zhc::lumi::kLumiTagVoltage,    "voltage",     1   },
    { ::zhc::lumi::kLumiTagState,      "temperature", 100 },
    { ::zhc::lumi::kLumiTagHumidity,   "humidity",    100 },
    { ::zhc::lumi::kLumiTagPressure,   "pressure",    100 },
};
constexpr ::zhc::lumi::LumiTagMap kTagMap{ kTagEntries, 4 };

const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::lumi::kFzLumiSpecific,
    &Temp::converter,
    &Humidity::converter,
    &Pressure::converter,
};
constexpr const char* kModels[] = { "lumi.weather.agl01" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefWSDCGQ21LM{
    .zigbee_models = kModels, .zigbee_models_count = 1,
    .model = "WSDCGQ21LM", .vendor = "Xiaomi",
    .meta = &kTagMap,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
