// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WSDCGQ12LM temp/humidity/pressure sensor (T1).
// Same shape as WSDCGQ11LM with an updated zigbeeModel.
// z2m v26.110.0 (#13169) fixed "not reporting": temperature, humidity,
// pressure and battery are now bound and their reporting configured
// (m.temperature / m.humidity defaults, pressure 10 s .. 1 h change 5,
// battery voltage + percentage hourly); v26.114.0 publishes pressure in hPa
// (scale 1), which the divisor below already did.
// z2m-source: lumi.ts #WSDCGQ12LM (lumi.weather.v2).

#include "definitions/lumi/_shared.hpp"
#include "zhc/modern_extend.hpp"

namespace zhc::devices::lumi {
namespace {
struct temp_opts {
    static constexpr const char*   name    = "temperature";
    static constexpr const char*   unit    = "°C";
    static constexpr const char*   cluster = "msTemperatureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct humidity_opts {
    static constexpr const char*   name    = "humidity";
    static constexpr const char*   unit    = "%";
    static constexpr const char*   cluster = "msRelativeHumidity";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 100;
};
struct pressure_opts {
    static constexpr const char*   name    = "pressure";
    static constexpr const char*   unit    = "hPa";
    static constexpr const char*   cluster = "msPressureMeasurement";
    static constexpr std::uint16_t attr    = 0x0000;
    static constexpr std::uint32_t divisor = 1;
};
using Temp     = ::zhc::m::Numeric<temp_opts>;
using Humidity = ::zhc::m::Numeric<humidity_opts>;
using Pressure = ::zhc::m::Numeric<pressure_opts>;

constexpr ::zhc::lumi::LumiTagEntry kTagEntries[] = {
    { ::zhc::lumi::kLumiTagVoltage,    "voltage",     1   },
    { ::zhc::lumi::kLumiTagState,      "temperature", 100 },
    { ::zhc::lumi::kLumiTagHumidity,   "humidity",    100 },
    { ::zhc::lumi::kLumiTagPressure,   "pressure",    100 },
};
constexpr ::zhc::lumi::LumiTagMap kTagMap{ kTagEntries, 4 };

const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::lumi::kFzLumiManuTempHum,
    &::zhc::lumi::kFzLumiSpecific,
    &Temp::converter,
    &Humidity::converter,
    &Pressure::converter,
    &::zhc::lumi::kFzLumiHeartbeatBattery,
};
constexpr const char* kModels[] = { "lumi.sensor_ht.agl02", "lumi.weather.v2" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"pressure", ExposeType::Numeric, Access::State, "hPa", nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0402},
    {1, 0x0405},
    {1, 0x0403},
    {1, 0x0001},
};
constexpr ReportingSpec kReports[] = {
    {1, 0x0402, 0x0000, 0x29, 10, 3600, 100, 0},     // temperature
    {1, 0x0405, 0x0000, 0x21, 10, 3600, 100, 0},     // humidity
    {1, 0x0403, 0x0000, 0x29, 10, 3600, 5, 0},       // pressure
    {1, 0x0001, 0x0021, 0x20, 3600, 65000, 10, 0},   // batteryPercentageRemaining
    {1, 0x0001, 0x0020, 0x20, 3600, 65000, 10, 0},   // batteryVoltage
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefWSDCGQ12LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .model = "WSDCGQ12LM", .vendor = "Xiaomi",
    .meta = &kTagMap,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .reports=kReports, .reports_count=sizeof(kReports)/sizeof(kReports[0]),
};
}
