// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WXCJKG13LM wired scene switch 3-button (Opple).
// Emits `action = button_<ep>_<label>`; label set mirrors z2m.
// z2m-source: lumi.ts #WXCJKG13LM (lumi.remote.b486opcn01).
#include "definitions/lumi/_shared.hpp"
namespace zhc::devices::lumi {
namespace {
constexpr ::zhc::lumi::LumiActionEntry kEntries[] = {
    {0, "hold"}, {1, "single"}, {2, "double"}, {3, "triple"},
    {5, "quintuple"}, {6, "many"}, {255, "release"},
};
constexpr ::zhc::lumi::LumiActionMap kMap{ kEntries, 7 };
constexpr FzConverter kFzAction{
    .family            = FrameFamily::Zcl,
    .cluster           = "genMultistateInput",
    .type_mask         = type_bit(MessageType::AttributeReport) |
                         type_bit(MessageType::ReadResponse),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .zcl_fn = &::zhc::lumi::fz_lumi_action_opple },
    .user_config       = &kMap,
};
const FzConverter* const kFz[] = {
    &::zhc::lumi::kFzLumiBasic,
    &kFzAction,
};
constexpr const char* kModels[] = { "lumi.remote.b686opcn01" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---

// configure: force manuSpecificLumi `mode` (0x0009, uint8) = 1 ("event")
// with manufacturerCode 0x115F. z2m: endpoint.write("manuSpecificLumi",
// {mode: 1}, {manufacturerCode}). Field order: op, endpoint, cluster_id,
// cmd_id, flags, payload, payload_len, wait_ms, manu_code, attr_id,
// attr_type.
constexpr std::uint8_t kModeEvent[] = { 0x01 };
constexpr ConfigStep kConfigSteps[] = {
    { ConfigStepOp::Write, 1, 0xFCC0, 0, 0,
      kModeEvent, sizeof(kModeEvent),
      0, /*manu_code=*/0x115F, /*attr_id=*/0x0009, /*attr_type=*/0x20 },
};


extern const PreparedDefinition kDefWXCJKG13LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model = "WXCJKG13LM", .vendor = "Xiaomi",
    .meta = nullptr,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = kFz, .from_zigbee_count = sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee = nullptr, .to_zigbee_count = 0,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .config_steps = kConfigSteps,
    .config_steps_count = sizeof(kConfigSteps)/sizeof(kConfigSteps[0]),
};
}
