// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WXKG28LM wireless remote.
// z2m-source: lumi.ts #WXKG28LM (lumi.remote.acn015).
#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"
namespace zhc::devices::lumi {
namespace {
struct A { static constexpr ::zhc::lumi::LumiActionEntry e[] = {
    {0,"hold"},{1,"single"},{2,"double"},{255,"release"}};
    static constexpr ::zhc::lumi::LumiActionMap map{e,4}; };
using FX = ::zhc::lumi::factory::LumiAction<A>;
constexpr const char* kModels[] = { "lumi.remote.acn015" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0012},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefWXKG28LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .model = "WXKG28LM", .vendor = "Xiaomi",
    .meta = nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels = nullptr, .white_labels_count = 0,
    .from_zigbee = FX::fz_list, .from_zigbee_count = FX::fz_count,
    .to_zigbee = FX::tz_list, .to_zigbee_count = FX::tz_count,
    .configure = nullptr, .on_event = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
