// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: uses shared lumi converters.
//
// z2m-source: zigbee-herdsman-converters/src/devices/lumi.ts — WXKG01LM
// ("Mi wireless switch"). v1 slice: battery report via lumi_basic.
// Button-timing + click-counter come in a follow-up commit once
// RuntimeStore usage patterns are exercised.

#include "definitions/lumi/_shared.hpp"
#include "zhc/runtime/definition.hpp"

namespace zhc::devices::lumi {

namespace {

const char* const kZigbeeModels[] = { "lumi.sensor_switch" };

const FzConverter* const kFromZigbee[] = {
    &zhc::lumi::kFzLumiBasic,
    &zhc::lumi::kFzLumiActionWXKG01LM,
};

constexpr WhiteLabel kWhiteLabels[] = {
    {"Xiaomi", "YTC4040GL"},
    {"Xiaomi", "YTC4006CN"},
    {"Xiaomi", "YTC4017CN"},
    {"Xiaomi", "ZHTZ02LM"},
};

}  // namespace

// `extern const` on the definition: namespace-scope `const` otherwise
// defaults to internal linkage and the test TU can't reach it.

// --- auto-generated by emit_expose_bindings.py (manually extended with
//     action / duration / click_count exposed by fz_lumi_action_WXKG01LM
//     so the UI renders them as read-only labels) ---
constexpr const char* kActions_WXKG01LM[] = {
    "single", "double", "triple", "quadruple", "many", "hold",
};

constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action",   ExposeType::Enum,    Access::State, nullptr, nullptr,
     kActions_WXKG01LM, sizeof(kActions_WXKG01LM)/sizeof(kActions_WXKG01LM[0])},
    {"duration", ExposeType::Numeric, Access::State, "ms", nullptr, nullptr, 0},
    {"click_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
};
// --- end auto-generated block ---

// Lumi mfg-specific Read of Basic-cluster attr 0xFF01 — wakes old
// `lumi.sensor_switch` FW into emitting the packed struct (battery
// voltage, dev_temp, RSSI, …) that kFzLumiBasic decodes. Without this
// the device only ships 0xFF01 alongside button clicks; pure reporting
// devices would never surface battery.
constexpr std::uint8_t kReadFF01[] = { 0x01, 0xFF };
constexpr ConfigStep kConfigSteps[] = {
    {
        ConfigStepOp::Read,
        /*endpoint*/   1,
        /*cluster_id*/ 0x0000,
        /*cmd_id*/     0,
        /*flags*/      0,
        /*payload*/    kReadFF01,
        /*payload_len*/sizeof(kReadFF01),
        /*wait_ms*/    1500,
        /*manu_code*/  0x115F,
    },
};


extern const PreparedDefinition kDefWXKG01LM{
    .zigbee_models       = kZigbeeModels,
    .zigbee_models_count = sizeof(kZigbeeModels) / sizeof(kZigbeeModels[0]),
    .model              = "WXKG01LM",
    .vendor             = "Xiaomi",
    .meta               = nullptr,   // battery curve baked into fz_lumi_basic
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels       = kWhiteLabels,
    .white_labels_count = sizeof(kWhiteLabels) / sizeof(kWhiteLabels[0]),
    .from_zigbee        = kFromZigbee,
    .from_zigbee_count  = sizeof(kFromZigbee) / sizeof(kFromZigbee[0]),
    .to_zigbee          = nullptr,
    .to_zigbee_count    = 0,
    .configure          = nullptr,
    .on_event           = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .config_steps       = kConfigSteps,
    .config_steps_count = sizeof(kConfigSteps) / sizeof(kConfigSteps[0]),
};

}  // namespace zhc::devices::lumi
