// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WXKG11LM wireless switch (gen-1).
//
// Uses the generic fz_lumi_action_multistate on genMultistateInput
// attr 0x0055. Actions exposed by z2m: single / double / triple /
// quadruple / hold / release.
//
// z2m-source: zigbee-herdsman-converters/src/devices/lumi.ts
//             #WXKG11LM (2016 revision).

#include "definitions/lumi/_shared.hpp"

namespace zhc::devices::lumi {

namespace {

constexpr ::zhc::lumi::LumiActionEntry kWXKG11LMEntries[] = {
    {0, "hold"},
    {1, "single"},
    {2, "double"},
    {3, "triple"},
    {4, "quadruple"},
    {5, "release"},
};

constexpr ::zhc::lumi::LumiActionMap kWXKG11LMActionMap{
    .entries = kWXKG11LMEntries,
    .count   = sizeof(kWXKG11LMEntries) / sizeof(kWXKG11LMEntries[0]),
};

// Per-device FzConverter — reuses `fz_lumi_action_multistate` but binds
// this device's action map into `user_config`.
constexpr FzConverter kFzActionWXKG11LM{
    .family            = FrameFamily::Zcl,
    .cluster           = "genMultistateInput",
    .type_mask         = type_bit(MessageType::AttributeReport) |
                         type_bit(MessageType::ReadResponse),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .zcl_fn = &::zhc::lumi::fz_lumi_action_multistate },
    .user_config       = &kWXKG11LMActionMap,
};

const FzConverter* const kFzList[] = {
    &::zhc::lumi::kFzLumiBasic,
    &kFzActionWXKG11LM,
    // z2m also wires `lumi_action` on genOnOff attr 0x8000 so the
    // click-counter (double/triple/quadruple) fires when the device
    // sends its count attr instead of presentValue.
    &::zhc::lumi::kFzLumiAction,
};

constexpr const char* kZigbeeModels[] = {
    "lumi.sensor_switch.aq2",
    "lumi.remote.b1acn01",
};

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefWXKG11LM{
    .zigbee_models       = kZigbeeModels,
    .zigbee_models_count = 2,
    .model               = "WXKG11LM",
    .vendor              = "Xiaomi",
    .meta                = nullptr,
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels        = nullptr,
    .white_labels_count  = 0,
    .from_zigbee         = kFzList,
    .from_zigbee_count   = sizeof(kFzList) / sizeof(kFzList[0]),
    .to_zigbee           = nullptr,
    .to_zigbee_count     = 0,
    .configure           = nullptr,
    .on_event            = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::lumi
