// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara WXKG03LM single wireless button.
//
// Uses `factory::LumiAction` with a {1→single, 2→double, 0→hold} map
// on genMultistateInput attr 0x0055.
//
// z2m-source: zigbee-herdsman-converters/src/devices/lumi.ts
//             #WXKG03LM (lumi.sensor_86sw1).

#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"

namespace zhc::devices::lumi {

namespace {

struct WXKG03_Actions {
    static constexpr ::zhc::lumi::LumiActionEntry entries[] = {
        {0, "hold"},
        {1, "single"},
        {2, "double"},
    };
    static constexpr ::zhc::lumi::LumiActionMap map{ entries, 3 };
};

using FX = ::zhc::lumi::factory::LumiAction<WXKG03_Actions>;

constexpr const char* kZigbeeModels[] = { "lumi.remote.b186acn01", "lumi.sensor_86sw1" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0012},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefWXKG03LM{
    .zigbee_models=kZigbeeModels,.zigbee_models_count=sizeof(kZigbeeModels)/sizeof(kZigbeeModels[0]),
    .model               = "WXKG03LM",
    .vendor              = "Xiaomi",
    .meta                = nullptr,
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels        = nullptr,
    .white_labels_count  = 0,
    .from_zigbee         = FX::fz_list,
    .from_zigbee_count   = FX::fz_count,
    .to_zigbee           = FX::tz_list,
    .to_zigbee_count     = FX::tz_count,
    .configure           = nullptr,
    .on_event            = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::lumi
