// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara ZNCZ02LM smart plug (CN variant, lumi.plug).
//
// Wires:
//   genBasic         → fz_lumi_basic    (battery-less; voltage/dtemp tags
//                       appear for diagnostics only)
//   haElectricalMeasurement → fz_lumi_power
//                              with /10 divisor on power (typical Aqara quirk)
//   seMetering       → fz_lumi_electricity_meter with /1000 on energy
//   genOnOff         → fz_on_off (generic relay state)
//
// z2m-source: zigbee-herdsman-converters/src/devices/lumi.ts
//             #ZNCZ02LM.

#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"

namespace zhc::devices::lumi {

namespace {

constexpr ::zhc::lumi::LumiPowerCalibration kZNCZ02LMPower{
    .voltage_div = 1,     // raw integer V until interview lands
    .current_div = 1000,  // raw is mA → A
    .power_div   = 10,    // raw is deciwatts → W  (12.3 W ↔ raw 123)
};

constexpr ::zhc::lumi::LumiMeterCalibration kZNCZ02LMMeter{
    .energy_div = 1000,   // raw is Wh → kWh
};

constexpr FzConverter kFzPowerZNCZ02LM{
    .family            = FrameFamily::Zcl,
    .cluster           = "haElectricalMeasurement",
    .type_mask         = type_bit(MessageType::AttributeReport) |
                         type_bit(MessageType::ReadResponse),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .zcl_fn = &::zhc::lumi::fz_lumi_power },
    .user_config       = &kZNCZ02LMPower,
};

constexpr FzConverter kFzMeterZNCZ02LM{
    .family            = FrameFamily::Zcl,
    .cluster           = "seMetering",
    .type_mask         = type_bit(MessageType::AttributeReport) |
                         type_bit(MessageType::ReadResponse),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .zcl_fn = &::zhc::lumi::fz_lumi_electricity_meter },
    .user_config       = &kZNCZ02LMMeter,
};

const FzConverter* const kFzList[] = {
    &::zhc::lumi::kFzLumiBasic,
    &::zhc::generic::kFzOnOff,
    &kFzPowerZNCZ02LM,
    &kFzMeterZNCZ02LM,
};

constexpr const char* kZigbeeModels[] = { "lumi.plug" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
};
// --- end auto-generated block ---


extern const PreparedDefinition kDefZNCZ02LM{
    .zigbee_models=kZigbeeModels,.zigbee_models_count=sizeof(kZigbeeModels)/sizeof(kZigbeeModels[0]),
    .model               = "ZNCZ02LM",
    .vendor              = "Xiaomi",
    .meta                = nullptr,
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels        = nullptr,
    .white_labels_count  = 0,
    .from_zigbee         = kFzList,
    .from_zigbee_count   = sizeof(kFzList) / sizeof(kFzList[0]),
    .to_zigbee           = nullptr,
    .to_zigbee_count     = 0,
    .configure           = nullptr,
    .on_event            = nullptr,
    .bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    // z2m ZNCZ02LM configure: reporting.bind(genOnOff) +
    // reporting.onOff(endpoint). (Power/energy decode but z2m does not
    // configureReporting them for this SKU.)
    .reports=::zhc::lumi::kReportsLumiOnOff,
    .reports_count=::zhc::lumi::kReportsLumiOnOffCount,
};

}  // namespace zhc::devices::lumi
