// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Aqara ZNQBKG41LM — auto-generated stub.
// z2m-source: lumi.ts #ZNQBKG41LM.
#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"
namespace zhc::devices::lumi {
namespace {
struct E { static constexpr ::zhc::lumi::DeviceEndpointLabel e[]={{1,"state"}};
          static constexpr ::zhc::lumi::DeviceEndpointLabels map{e,1}; };
// What z2m adds on top of the factory bundle (factories.hpp NoExtras).
struct X : ::zhc::lumi::factory::NoExtras {
    static constexpr std::array<const FzConverter*, 3> fz{{
        &::zhc::lumi::kFzLumiHeartbeat,
        &::zhc::lumi::kFzLumiPreventReset,
        &::zhc::lumi::kFzLumiOperationMode,
    }};
    static constexpr std::array<const TzConverter*, 3> tz{{
        &::zhc::lumi::kTzLumiOperationModeTop,
        &::zhc::lumi::kTzLumiOperationModeCenter,
        &::zhc::lumi::kTzLumiOperationModeBottom3,
    }};
};
using FX = ::zhc::lumi::factory::LumiOnOff<E, X>;
constexpr const char* kModels[] = { "lumi.switch.acn055" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"operation_mode_top", ExposeType::Enum, Access::StateSet, nullptr,
     "Decoupled mode for top button",
     ::zhc::lumi::kLumiOperationModeValues, std::size(::zhc::lumi::kLumiOperationModeValues), ExposeCategory::Config},
    {"operation_mode_center", ExposeType::Enum, Access::StateSet, nullptr,
     "Decoupled mode for center button",
     ::zhc::lumi::kLumiOperationModeValues, std::size(::zhc::lumi::kLumiOperationModeValues), ExposeCategory::Config},
    {"operation_mode_bottom", ExposeType::Enum, Access::StateSet, nullptr,
     "Decoupled mode for bottom button",
     ::zhc::lumi::kLumiOperationModeValues, std::size(::zhc::lumi::kLumiOperationModeValues), ExposeCategory::Config},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefZNQBKG41LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="ZNQBKG41LM",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=FX::fz_list,.from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list,.to_zigbee_count=FX::tz_count,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    // z2m: manuSpecificLumi mode (0x0009) = 1, "event", at configure.
    .config_steps = ::zhc::lumi::kConfigStepsLumiEventMode,
    .config_steps_count = std::size(::zhc::lumi::kConfigStepsLumiEventMode),
};
}
