// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aqara ZNXNKG02LM rotary dimmer (dim only).
// z2m-source: lumi.ts #ZNXNKG02LM (lumi.dimmer.rcbac2).
#include "definitions/lumi/_shared.hpp"
#include "definitions/lumi/factories.hpp"
namespace zhc::devices::lumi {
namespace {
// What z2m adds on top of the factory bundle (factories.hpp NoExtras).
struct X : ::zhc::lumi::factory::NoExtras {
    static constexpr std::array<const FzConverter*, 2> fz{{
        &::zhc::lumi::kFzLumiBattery,
        &::zhc::lumi::kFzLumiPreventReset,
    }};
    static constexpr std::array<const TzConverter*, 1> tz{{
        &::zhc::lumi::kTzLumiCommandMode,
    }};
};
using FX = ::zhc::lumi::factory::LumiLight<::zhc::lumi::factory::LumiLightOpts{.level=true,.color_temp=false}, X>;
constexpr const char* kModels[] = { "lumi.dimmer.rcbac2", "lumi.remote.rkba01" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"power_outage_count", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"operation_mode", ExposeType::Enum, Access::StateSet, nullptr,
     "Command mode is useful for binding. Event mode is useful for processing.",
     ::zhc::lumi::kLumiCommandModeValues, std::size(::zhc::lumi::kLumiCommandModeValues), ExposeCategory::Config},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0000},
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefZNXNKG02LM{
    .zigbee_models=kModels,.zigbee_models_count=sizeof(kModels)/sizeof(kModels[0]),.model="ZNXNKG02LM",.vendor="Xiaomi",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=FX::fz_list,.from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list,.to_zigbee_count=FX::tz_count,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    // z2m: manuSpecificLumi mode (0x0009) = 1, "event", at configure.
    .config_steps = ::zhc::lumi::kConfigStepsLumiEventMode,
    .config_steps_count = std::size(::zhc::lumi::kConfigStepsLumiEventMode),
};
}
