// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Makegood MG-GPO01 — graduated from generated/.
// Double Zigbee power point
// z2m-source: makegood.ts #MG-GPO01.
//
// DEFERRED (INFRA, gap class f — dual-endpoint metering split): z2m declares
// two switch endpoints (right:1, left:2) via deviceEndpoints but keeps
// power/current/voltage/energy global through
// `meta.multiEndpointSkip: ["power","current","voltage","energy"]`, suffixing
// only the switch `state` per endpoint. The runtime suffix rewrite
// (src/runtime/dispatch.cpp) has no per-def "metering-skip" hook — keeping the
// endpoint_map {right:1,left:2} here would wrongly suffix power/current/energy
// to `_right` (only `voltage` is in kAlwaysGlobalKeys[]), diverging from z2m's
// bare keys. So the endpoint_map is dropped: the def ships a single bare
// `state` + a single (EP1) metering surface, identical to the
// structurally-equal MG-AUZG01 and Honyar U86Z223A10-ZJU01(GD) (HY0157). The
// second-gang state split waits on the dispatch infra.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::makegood {
namespace {
const FzConverter* const kFz_MG_GPO01[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
};
const TzConverter* const kTz_MG_GPO01[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_MG_GPO01[] = { "TS011F" };
constexpr const char* kManus_MG_GPO01[] = { "_TZ3210_bep7ccew" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0702},
    {1, 0x0B04},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MG_GPO01{
    .zigbee_models=kModels_MG_GPO01, .zigbee_models_count=sizeof(kModels_MG_GPO01)/sizeof(kModels_MG_GPO01[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus_MG_GPO01, .manufacturer_names_count=sizeof(kManus_MG_GPO01)/sizeof(kManus_MG_GPO01[0]),
    .model="MG-GPO01", .vendor="Makegood",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MG_GPO01, .from_zigbee_count=sizeof(kFz_MG_GPO01)/sizeof(kFz_MG_GPO01[0]),
    .to_zigbee=kTz_MG_GPO01, .to_zigbee_count=sizeof(kTz_MG_GPO01)/sizeof(kTz_MG_GPO01[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::makegood
