// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: SiliconLabs RB-ElectricityDsp-061-3 — restored the 0x0B04 half.
// Electricity meter
//
// z2m wires m.onOff() + m.electricityMeter(); electricityMeter() defaults to
// cluster:"both" → energy from seMetering (0x0702) AND power/voltage/current
// from haElectricalMeasurement (0x0B04, fz.electrical_measurement). The
// auto-generated port wired only kFzMetering (0x0702) and exposed only
// state/energy/power, dropping the 0x0B04 decoder plus the voltage/current
// exposes and the 0x0B04 binding. Without it RMSVoltage/RMSCurrent reports
// were never decoded and z2m's "both"-mode power (ActivePower 0x050B on
// 0x0B04) had no converter. Fixed by adding kFzElectricalMeasurement,
// publishing voltage+current exposes, and binding 0x0B04.
//
// z2m-source: silicon_labs.ts #RB-ElectricityDsp-061-3 (m.electricityMeter()
// → genericMeter cluster:"both").
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::silicon_labs {
namespace {
const FzConverter* const kFz_RB_ElectricityDsp_061_3[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,             // seMetering 0x0702 → energy (+power)
    &::zhc::generic::kFzElectricalMeasurement, // haElectricalMeasurement 0x0B04 → power/voltage/current
};
const TzConverter* const kTz_RB_ElectricityDsp_061_3[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_RB_ElectricityDsp_061_3[] = { "RB-ElectricityDsp-061-3" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0702},
    {1, 0x0B04},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_RB_ElectricityDsp_061_3{
    .zigbee_models=kModels_RB_ElectricityDsp_061_3, .zigbee_models_count=sizeof(kModels_RB_ElectricityDsp_061_3)/sizeof(kModels_RB_ElectricityDsp_061_3[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="RB-ElectricityDsp-061-3", .vendor="SiliconLabs",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_RB_ElectricityDsp_061_3, .from_zigbee_count=sizeof(kFz_RB_ElectricityDsp_061_3)/sizeof(kFz_RB_ElectricityDsp_061_3[0]),
    .to_zigbee=kTz_RB_ElectricityDsp_061_3, .to_zigbee_count=sizeof(kTz_RB_ElectricityDsp_061_3)/sizeof(kTz_RB_ElectricityDsp_061_3[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::silicon_labs
