// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Multir MIR-TE600 — temperature + humidity sensor.
// z2m extend: m.battery() + m.temperature() + m.humidity(). The auto-port
// lowered only kFzBattery, dropping BOTH the temperature (0x0402) and
// humidity (0x0405) channels. Added kFzTemperature + kFzHumidity and their
// bindings.
// z2m-source: multir.ts #MIR-TE600.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::multir {
namespace {
const FzConverter* const kFz_MIR_TE600[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzHumidity,
};

constexpr const char* kModels_MIR_TE600[] = { "MIR-TE600" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "\xC2\xB0""C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0405},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MIR_TE600{
    .zigbee_models=kModels_MIR_TE600, .zigbee_models_count=sizeof(kModels_MIR_TE600)/sizeof(kModels_MIR_TE600[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MIR-TE600", .vendor="Multir",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MIR_TE600, .from_zigbee_count=sizeof(kFz_MIR_TE600)/sizeof(kFz_MIR_TE600[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::multir
