// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Bega 13557 — color/colorTemp axis restored.
// LED lamp with adjustable LED color temperature (Tunable White - RGBW) for use in luminaires with E27 lamp base
// z2m-source: bega.ts #13557 —
//   m.light({colorTemp:{range:[153,556]}, color:true}).
// The auto-port dropped the 0x0300 lightingColorCtrl axis: color_temp +
// color_xy exposes and the cluster bind were missing, so colour and
// colour-temperature reports decoded to nothing. Wired the generic
// kFzColorTemperature/kFzColor decoders + kTzColorTemp/kTzColor setters
// and restored the color_temp/color_xy exposes and the {1,0x0300} bind.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::bega {
namespace {
const FzConverter* const kFz_D13557[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzColorTemperature,
    &::zhc::generic::kFzColor,
};
const TzConverter* const kTz_D13557[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzColorTemp,
    &::zhc::generic::kTzColor,
};
constexpr const char* kModels_D13557[] = { "BEGA 13557 bulb E27 RGBW 805lm" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
// z2m: m.light({colorTemp:{range:[153,556]}, color:true}) — RGBW+CW bulb
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"color_temp", ExposeType::Numeric, Access::StateSet, "mired", nullptr, nullptr, 0},
    {"color_xy", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0300},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D13557{
    .zigbee_models=kModels_D13557, .zigbee_models_count=sizeof(kModels_D13557)/sizeof(kModels_D13557[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="13557", .vendor="Bega",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D13557, .from_zigbee_count=sizeof(kFz_D13557)/sizeof(kFz_D13557[0]),
    .to_zigbee=kTz_D13557, .to_zigbee_count=sizeof(kTz_D13557)/sizeof(kTz_D13557[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::bega
