// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Ecolink 4655BC0-R — hand-curated (was IAS dead-key + missing-decoder).
// Contact sensor. z2m wires fz.temperature + fz.ias_contact_alarm_1 and exposes
// temperature/contact/battery_low/tamper, but the auto-port lowered only the
// generic kFzIasZone (emitting a bare `alarm` key) and dropped the temperature
// channel entirely. Switched to kFzIasContactAlarm (ssIasZone command 0x00 →
// z2m-polarity `contact` = !zoneStatus bit0, plus tamper/battery_low) and added
// kFzTemperature (msTemperatureMeasurement 0x0402), the temperature + contact
// exposes and the 0x0402 binding.
// z2m-source: ecolink.ts #4655BC0-R.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::ecolink {
namespace {
const FzConverter* const kFz_D4655BC0_R[] = {
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_D4655BC0_R[] = { "4655BC0-R" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0402},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D4655BC0_R{
    .zigbee_models=kModels_D4655BC0_R, .zigbee_models_count=sizeof(kModels_D4655BC0_R)/sizeof(kModels_D4655BC0_R[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="4655BC0-R", .vendor="Ecolink",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D4655BC0_R, .from_zigbee_count=sizeof(kFz_D4655BC0_R)/sizeof(kFz_D4655BC0_R[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::ecolink
