// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Scanproducts 12502 — Zigbee 3.0 switch, power_on_behavior restored.
// Zigbee 3.0 switch.
// z2m-source: scanproducts.ts #12502 = m.onOff().
// m.onOff() defaults powerOnBehavior=true, so z2m wires fz.power_on_behavior
// (genOnOff 0x4003 startUpOnOff) + tz.power_on_behavior + the power_on_behavior
// enum expose. The Tier-1 auto-port dropped that axis; restored via
// kFzPowerOnBehavior / kTzPowerOnBehavior1. On/off itself was already correct.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::scanproducts {
namespace {
const FzConverter* const kFz_D12502[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzPowerOnBehavior,
};
const TzConverter* const kTz_D12502[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_D12502[] = { "12502" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D12502{
    .zigbee_models=kModels_D12502, .zigbee_models_count=sizeof(kModels_D12502)/sizeof(kModels_D12502[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="12502", .vendor="Scanproducts",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D12502, .from_zigbee_count=sizeof(kFz_D12502)/sizeof(kFz_D12502[0]),
    .to_zigbee=kTz_D12502, .to_zigbee_count=sizeof(kTz_D12502)/sizeof(kTz_D12502[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::scanproducts
