// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Bubendorff MONO iD4 — hand-curated (was missing tilt).
// Roller shutter. z2m m.windowCovering({controls:["lift","tilt"]}) exposes
// both position AND tilt, but the auto-port wired only kFzCoverPosition /
// kTzCoverPosition (lift), dropping the tilt channel
// (currentPositionTiltPercentage 0x0009). Added kFzCoverTilt decoder +
// kTzCoverPositionTilt encoder + a `tilt` expose.
// z2m-source: bubendorff.ts #MONO iD4.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::bubendorff {
namespace {
const FzConverter* const kFz_MONO_iD4[] = {
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
};
const TzConverter* const kTz_MONO_iD4[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_MONO_iD4[] = { "Roller Shutter with RU motor" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0102},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MONO_iD4{
    .zigbee_models=kModels_MONO_iD4, .zigbee_models_count=sizeof(kModels_MONO_iD4)/sizeof(kModels_MONO_iD4[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MONO iD4", .vendor="Bubendorff",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MONO_iD4, .from_zigbee_count=sizeof(kFz_MONO_iD4)/sizeof(kFz_MONO_iD4[0]),
    .to_zigbee=kTz_MONO_iD4, .to_zigbee_count=sizeof(kTz_MONO_iD4)/sizeof(kTz_MONO_iD4[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::bubendorff
