// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2 (2026-06-11): graduated from generated/. The auto-port wired only
// kFzLock + kFzBattery and exposed battery/voltage/lock_state, dropping the
// z2m lock-action stream. z2m BE468 wires fz.lock_operation_event +
// fz.lock_programming_event (closuresDoorLock cmds 0x21/0x20, server->client)
// -> action / action_user / action_source / action_source_name, plus
// tz.pincode_lock -> pin_code (setPinCode 0x05). All three converters already
// exist generically (kwikset/onesti/datek precedent). Wired them + restored
// the action + pin_code exposes; lock_state corrected Binary->Enum (z2m emits
// the not_fully_locked/locked/unlocked enum, never a bool). Bindings stay on
// endpoint 1 (z2m device.endpoints[0]). PIN/user-code *read* response
// (fz.lock_pin_code_response -> users map) stays INFRA-deferred.
// Connect smart deadbolt
// z2m-source: schlage.ts #BE468.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::schlage {
namespace {
const FzConverter* const kFz_BE468[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzLock,
    &::zhc::generic::kFzLockProgrammingEvent,
    &::zhc::generic::kFzLockOperationEvent,
};
const TzConverter* const kTz_BE468[] = {
    &::zhc::generic::kTzLock,
    &::zhc::generic::kTzLockPinCode,
};
constexpr const char* kModels_BE468[] = { "BE468" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"lock_state", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"pin_code", ExposeType::String, Access::Set, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_user", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_source", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_source_name", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0101},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_BE468{
    .zigbee_models=kModels_BE468, .zigbee_models_count=sizeof(kModels_BE468)/sizeof(kModels_BE468[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="BE468", .vendor="Schlage",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_BE468, .from_zigbee_count=sizeof(kFz_BE468)/sizeof(kFz_BE468[0]),
    .to_zigbee=kTz_BE468, .to_zigbee_count=sizeof(kTz_BE468)/sizeof(kTz_BE468[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::schlage
