// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Spotmau SP-PS1-02 — graduated from generated/.
// Smart wall switch - 1 gang
// z2m-source: spotmau.ts #SP-PS1-02 — m.onOff(), endpoint:()=>({default:16}).
//
// Gap (control+read dead): z2m puts the single genOnOff on endpoint 16
// (endpoint:{default:16}, no endpointNames → bare `state`). The auto-port
// bound genOnOff on ep1 and left default_endpoint=0, so reporting was
// configured on the wrong endpoint (reads dead) and outbound on/off routed
// to ep1 (control dead). Fix: bind {16,0x0006} + default_endpoint=16. NO
// endpoint_map — the default endpoint is unsuffixed in z2m, and a 1-entry
// map would wrongly suffix `state`→`state_default` (dispatch does not
// special-case the "default" label). Same shape as the ge PTAPT-WH02 /
// frient SMRZB-153 default_endpoint fix.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::spotmau {
namespace {
const FzConverter* const kFz_SP_PS1_02[] = {
    &::zhc::generic::kFzOnOff,
};
const TzConverter* const kTz_SP_PS1_02[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_SP_PS1_02[] = { "1719SP-PS1-02" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {16, 0x0006},  // z2m endpoint:()=>({default:16}) — genOnOff on ep16
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SP_PS1_02{
    .zigbee_models=kModels_SP_PS1_02, .zigbee_models_count=sizeof(kModels_SP_PS1_02)/sizeof(kModels_SP_PS1_02[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SP-PS1-02", .vendor="Spotmau",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SP_PS1_02, .from_zigbee_count=sizeof(kFz_SP_PS1_02)/sizeof(kFz_SP_PS1_02[0]),
    .to_zigbee=kTz_SP_PS1_02, .to_zigbee_count=sizeof(kTz_SP_PS1_02)/sizeof(kTz_SP_PS1_02[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .default_endpoint = 16,  // outbound on/off → ep16 (z2m default endpoint)
};

}  // namespace zhc::devices::spotmau
