// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: uses shared meazon converters.
// Bizy plug meter
// z2m-source: meazon.ts #MEAZON_BIZY_PLUG (fz.meazon_meter).
//
// z2m drives power/voltage/current/energy via the vendor
// `fz.meazon_meter` (manufacturer-specific seMetering attrs 0x2001/
// 0x2004/0x2015/0x2007/0x2018/0x3000), NOT the standard metering path.
// The auto-generated port wired generic kFzMetering + kFzElectrical
// Measurement (standard 0x0702/0x0B04 attrs the device never reports),
// leaving every channel dead. Replaced with kFzMeazonMeter; bindings
// realigned to endpoint 10 (genOnOff + seMetering) per z2m configure.
#include "definitions/_generic/_shared.hpp"
#include "definitions/meazon/_shared.hpp"

namespace zhc::devices::meazon {
namespace {
const FzConverter* const kFz_MEAZON_BIZY_PLUG[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::meazon::kFzMeazonMeter,
};
const TzConverter* const kTz_MEAZON_BIZY_PLUG[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_MEAZON_BIZY_PLUG[] = { "101.301.001649", "101.301.001838", "101.301.001802", "101.301.001738", "101.301.001412", "101.301.001765", "101.301.001814" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {10, 0x0006},
    {10, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MEAZON_BIZY_PLUG{
    .zigbee_models=kModels_MEAZON_BIZY_PLUG, .zigbee_models_count=sizeof(kModels_MEAZON_BIZY_PLUG)/sizeof(kModels_MEAZON_BIZY_PLUG[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MEAZON_BIZY_PLUG", .vendor="Meazon",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MEAZON_BIZY_PLUG, .from_zigbee_count=sizeof(kFz_MEAZON_BIZY_PLUG)/sizeof(kFz_MEAZON_BIZY_PLUG[0]),
    .to_zigbee=kTz_MEAZON_BIZY_PLUG, .to_zigbee_count=sizeof(kTz_MEAZON_BIZY_PLUG)/sizeof(kTz_MEAZON_BIZY_PLUG[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::meazon
