// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: uses shared meazon converters.
// DinRail 1-phase meter
// z2m-source: meazon.ts #MEAZON_DINRAIL (fz.meazon_meter).
//
// z2m drives power/voltage/current via the vendor `fz.meazon_meter`
// (manufacturer-specific seMetering attrs 0x2001/0x2004/0x2015/0x2007/
// 0x2018), NOT the standard metering path. The auto-generated port
// wired generic kFzElectricalMeasurement (standard haElectricalMeasurement
// 0x0B04 attrs the device never reports), leaving every channel dead.
// Replaced with kFzMeazonMeter; bindings realigned to endpoint 10
// (genOnOff + seMetering) per z2m configure. (No energy expose — DINRAIL
// reports none.)
#include "definitions/_generic/_shared.hpp"
#include "definitions/meazon/_shared.hpp"

namespace zhc::devices::meazon {
namespace {
const FzConverter* const kFz_MEAZON_DINRAIL[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::meazon::kFzMeazonMeter,
};
const TzConverter* const kTz_MEAZON_DINRAIL[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_MEAZON_DINRAIL[] = { "102.106.000235", "102.106.001111", "102.106.000348", "102.106.000256", "102.106.001242", "102.106.000540" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {10, 0x0006},
    {10, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_MEAZON_DINRAIL{
    .zigbee_models=kModels_MEAZON_DINRAIL, .zigbee_models_count=sizeof(kModels_MEAZON_DINRAIL)/sizeof(kModels_MEAZON_DINRAIL[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="MEAZON_DINRAIL", .vendor="Meazon",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_MEAZON_DINRAIL, .from_zigbee_count=sizeof(kFz_MEAZON_DINRAIL)/sizeof(kFz_MEAZON_DINRAIL[0]),
    .to_zigbee=kTz_MEAZON_DINRAIL, .to_zigbee_count=sizeof(kTz_MEAZON_DINRAIL)/sizeof(kTz_MEAZON_DINRAIL[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::meazon
