// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Hommyn WS-20-Z — hand-maintained parity override (was IAS dead-key).
//
// Graduated from generated/Hom_WS_20_Z.cpp: the generated def lowered the
// generic kFzIasZone (which emits the bare key "alarm") while z2m decodes the
// leak state via fz.ias_water_leak_alarm_1 — zoneStatus bit 0 → semantic key
// "water_leak" (plus tamper bit2 / battery_low bit3). With no rename layer the
// primary sensor state never reached the shadow. Swapped to the typed
// kFzIasWaterLeakAlarm (emits "water_leak", bit 0) and repointed the expose
// "alarm" → "water_leak". z2m WS-20-Z carries no fz.battery (battery_low comes
// from the zoneStatus frame), so no kFzBattery is wired — at parity.
// Water leakage sensor
// z2m-source: hommyn.ts #WS-20-Z.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::hommyn {
namespace {
const FzConverter* const kFz_WS_20_Z[] = {
    &::zhc::generic::kFzIasWaterLeakAlarm,
};

constexpr const char* kModels_WS_20_Z[] = { "2f077707a13f4120846e0775df7e2efe" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"water_leak", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_WS_20_Z{
    .zigbee_models=kModels_WS_20_Z, .zigbee_models_count=sizeof(kModels_WS_20_Z)/sizeof(kModels_WS_20_Z[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="WS-20-Z", .vendor="Hommyn",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_WS_20_Z, .from_zigbee_count=sizeof(kFz_WS_20_Z)/sizeof(kFz_WS_20_Z[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::hommyn
