// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Swann SWO-KEF1PA — key fob remote (IAS ACE arm/panic action).
// Key fob remote
// z2m-source: swann.ts #SWO-KEF1PA —
//   fromZigbee: [fz.command_arm, fz.command_panic]; toZigbee: [];
//   exposes: [e.action(["home","sleep","away","panic"])].
//
// Fix (wrong default bundle / dead state, gap class e): the auto-port
// mis-ported this action-only key fob as a *controllable* on/off switch —
// kFzOnOff + kTzOnOff + a writable `state` expose + a genOnOff (0x0006)
// binding. The fob never speaks genOnOff; it is an ssIasAce (0x0501) source
// that sends commandArm (cmd 0x00) and commandPanic (cmd 0x04). The state
// channel and the on/off write path were both dead.
//
// Correct wiring mirrors z2m: kFzIasAceArm decodes commandArm →
// action(armMode LUT) + action_code + action_zone; kFzIasAcePanic decodes
// commandPanic → action="panic". No toZigbee (z2m toZigbee:[]). Bind ssIasAce
// instead of genOnOff. The friendly action labels home/sleep/away map to the
// ZCL armMode constants the decoder emits (arm_day_zones/arm_night_zones/...).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::swann {
namespace {
const FzConverter* const kFz_SWO_KEF1PA[] = {
    &::zhc::generic::kFzIasAceArm,
    &::zhc::generic::kFzIasAcePanic,
};

constexpr const char* kModels_SWO_KEF1PA[] = { "SWO-KEF1PA" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action",      ExposeType::Enum,    Access::State, nullptr, nullptr, nullptr, 0},
    {"action_code", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"action_zone", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0501},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SWO_KEF1PA{
    .zigbee_models=kModels_SWO_KEF1PA, .zigbee_models_count=sizeof(kModels_SWO_KEF1PA)/sizeof(kModels_SWO_KEF1PA[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SWO-KEF1PA", .vendor="Swann",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SWO_KEF1PA, .from_zigbee_count=sizeof(kFz_SWO_KEF1PA)/sizeof(kFz_SWO_KEF1PA[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::swann
