// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Swann SWO-WDS1PA — window/door sensor (typed IAS contact).
// Window/door sensor
// z2m-source: swann.ts #SWO-WDS1PA — fromZigbee: [fz.ias_contact_alarm_1].
//
// Fix (IAS dead-key, gap class c): the auto-port wired the generic
// kFzIasZone, which emits a bare `alarm` key while the declared expose is
// `contact` — so the contact channel was dead. z2m decodes via
// fz.ias_contact_alarm_1, which publishes contact = !(zoneStatus bit0)
// (closed door = magnet present = bit0 clear = contact:true). Wire the typed
// kFzIasContactAlarm, which applies the z2m inversion and also emits
// tamper(bit2) + battery_low(bit3).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::swann {
namespace {
const FzConverter* const kFz_SWO_WDS1PA[] = {
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_SWO_WDS1PA[] = { "SWO-WDS1PA" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SWO_WDS1PA{
    .zigbee_models=kModels_SWO_WDS1PA, .zigbee_models_count=sizeof(kModels_SWO_WDS1PA)/sizeof(kModels_SWO_WDS1PA[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SWO-WDS1PA", .vendor="Swann",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SWO_WDS1PA, .from_zigbee_count=sizeof(kFz_SWO_WDS1PA)/sizeof(kFz_SWO_WDS1PA[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::swann
