// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: TisControl BEE PIR 1 — IAS dead-key fix.
// PIR Sensor
// z2m-source: tis_control.ts #BEE PIR 1
//   extend: [m.battery(),
//            m.iasZoneAlarm({zoneType:"occupancy",
//                            zoneAttributes:["alarm_1","tamper","battery_low"]})]
//
// z2m's iasZoneAlarm with zoneType "occupancy" and NO alarm_2 (bothAlarms=false)
// collapses alarm_1 onto the SEMANTIC key "occupancy" (zoneStatus bit0), plus
// tamper (bit2) and battery_low (bit3). The auto-port lowered the generic
// kFzIasZone (bare "alarm") while the expose declared "alarm" — so the motion
// state never matched the semantic occupancy expose z2m publishes. Swap in
// kFzIasMotionAlarm (emits bare "occupancy" from bit0 + tamper + battery_low)
// and rename the expose "alarm" -> "occupancy". Battery (%/voltage via
// kFzBattery / m.battery()) was already wired and is preserved.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tis_control {
namespace {
const FzConverter* const kFz_BEE_PIR_1[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasMotionAlarm,
};

constexpr const char* kModels_BEE_PIR_1[] = { "ED6XX" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_BEE_PIR_1{
    .zigbee_models=kModels_BEE_PIR_1, .zigbee_models_count=sizeof(kModels_BEE_PIR_1)/sizeof(kModels_BEE_PIR_1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="BEE PIR 1", .vendor="TisControl",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_BEE_PIR_1, .from_zigbee_count=sizeof(kFz_BEE_PIR_1)/sizeof(kFz_BEE_PIR_1[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tis_control
