// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aeotec ZGA004 — graduated (cover tilt + device temp + actions).
// "Pico shutter". z2m extend =
//   m.deviceEndpoints({1..5}, multiEndpointSkip:[position,tilt,state])
//   m.deviceTemperature() + m.identify()
//   m.windowCovering({controls:["lift","tilt"]})  -> position + tilt (ep1)
//   m.commandsWindowCovering({endpointNames:["3"]})            -> action ep3
//   m.commandsOnOff({endpointNames:["4","5"]})                 -> action ep4/5
//   m.commandsLevelCtrl({endpointNames:["4","5"]})
// Three gaps in the auto-port:
//   (1) m.windowCovering({controls:["lift","tilt"]}) exposes BOTH position
//       (lift, 0x0008) AND tilt (0x0009). The port wired only
//       kFzCoverPosition / kTzCoverPosition (lift) and exposed only
//       position, dropping the tilt channel. Added kFzCoverTilt +
//       kTzCoverPositionTilt + a `tilt` expose.
//   (2) m.deviceTemperature() (0x0002) dropped — added kFzDeviceTemperature
//       + device_temperature expose + 0x0002 bind.
//   (3) commandsWindowCovering (ep3) + commandsOnOff/LevelCtrl (ep4/ep5)
//       are scene-button channels surfaced as `action`. The port dropped
//       them. Wired kFzCommandCoverOpen/Close/Stop + On/Off/Toggle/Move/Stop
//       + an `action` enum + endpoint_action_suffix (action_3 / action_4 /
//       action_5 via the endpoint_map). The ep1 cover position/tilt + state
//       stay bare (multiEndpointSkip; ep1 is not in the map).
//   The phantom `state` Binary (auto-port artefact for the cover) is
//   dropped — a shutter has no controllable on/off; control is via
//   position/tilt setters. genOnOff (0x0006) bind on ep1 is removed.
// z2m-source: aeotec.ts #ZGA004.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::aeotec {
namespace {
const FzConverter* const kFz_ZGA004[] = {
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
    &::zhc::generic::kFzDeviceTemperature,
    &::zhc::generic::kFzCommandCoverOpen,
    &::zhc::generic::kFzCommandCoverClose,
    &::zhc::generic::kFzCommandCoverStop,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandToggle,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
const TzConverter* const kTz_ZGA004[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_ZGA004[] = { "ZGA004" };

constexpr ::zhc::EndpointLabel kEndpoints_ZGA004[] = { {"3", 3}, {"4", 4}, {"5", 5} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0102},
    {1, 0x0002},
    {3, 0x0102},
    {4, 0x0006}, {5, 0x0006},
    {4, 0x0008}, {5, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZGA004{
    .zigbee_models=kModels_ZGA004, .zigbee_models_count=sizeof(kModels_ZGA004)/sizeof(kModels_ZGA004[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZGA004", .vendor="Aeotec",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZGA004, .from_zigbee_count=sizeof(kFz_ZGA004)/sizeof(kFz_ZGA004[0]),
    .to_zigbee=kTz_ZGA004, .to_zigbee_count=sizeof(kTz_ZGA004)/sizeof(kTz_ZGA004[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_ZGA004,
    .endpoint_map_count = sizeof(kEndpoints_ZGA004)/sizeof(kEndpoints_ZGA004[0]),
    .endpoint_action_suffix=true,
};

}  // namespace zhc::devices::aeotec
