// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aeotec ZGA002 — graduated (metering half + device temp + actions).
// "Pico switch with power meter". z2m extend =
//   m.deviceEndpoints({1,2,3}, multiEndpointSkip:[state,V,P,I,energy])
//   m.deviceTemperature() + m.identify()
//   m.onOff({powerOnBehavior:false})            -> controllable relay (ep1)
//   m.electricityMeter()                         -> cluster:"both" (ep1)
//   m.commandsOnOff({endpointNames:["2","3"]})   -> action (ep2/ep3)
//   m.commandsLevelCtrl({endpointNames:["2","3"]})
// Three gaps in the auto-port:
//   (1) m.electricityMeter() defaults to cluster:"both" -> seMetering
//       (0x0702: energy) AND haElectricalMeasurement (0x0B04:
//       power/voltage/current). The port wired only kFzMetering (0x0702)
//       and exposed energy/power, dropping the 0x0B04 half + its bind.
//       Power on cluster:"both" comes from electrical_measurement, so add
//       kFzElectricalMeasurement + voltage/current exposes + 0x0B04 bind.
//   (2) m.deviceTemperature() (genDeviceTempCfg 0x0002) was dropped — add
//       kFzDeviceTemperature + device_temperature expose + 0x0002 bind.
//   (3) commandsOnOff/LevelCtrl on ep2/ep3 are scene-button channels (the
//       device EMITS genOnOff/genLevelCtrl commands) surfaced as `action`.
//       The port dropped them. Wire kFzCommandOn/Off/Toggle/Move/Stop +
//       an `action` enum + endpoint_action_suffix (action_2 / action_3 via
//       the endpoint_map, which already lists ep2/ep3). ep1 relay state +
//       metering stay bare (multiEndpointSkip), as ep1 is not in the map.
// z2m-source: aeotec.ts #ZGA002.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::aeotec {
namespace {
const FzConverter* const kFz_ZGA002[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
    &::zhc::generic::kFzDeviceTemperature,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandToggle,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
const TzConverter* const kTz_ZGA002[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_ZGA002[] = { "ZGA002" };

constexpr ::zhc::EndpointLabel kEndpoints_ZGA002[] = { {"2", 2}, {"3", 3} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0702},
    {1, 0x0B04},
    {1, 0x0002},
    {2, 0x0006}, {3, 0x0006},
    {2, 0x0008}, {3, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZGA002{
    .zigbee_models=kModels_ZGA002, .zigbee_models_count=sizeof(kModels_ZGA002)/sizeof(kModels_ZGA002[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZGA002", .vendor="Aeotec",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZGA002, .from_zigbee_count=sizeof(kFz_ZGA002)/sizeof(kFz_ZGA002[0]),
    .to_zigbee=kTz_ZGA002, .to_zigbee_count=sizeof(kTz_ZGA002)/sizeof(kTz_ZGA002[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_ZGA002,
    .endpoint_map_count = sizeof(kEndpoints_ZGA002)/sizeof(kEndpoints_ZGA002[0]),
    .endpoint_action_suffix=true,
};

}  // namespace zhc::devices::aeotec
