// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aeotec ZGA003 — graduated (metering half + device temp + actions).
// "Pico switch duo with power meter". z2m extend =
//   m.deviceEndpoints({1,2,3,4})
//   m.deviceTemperature() + m.identify()
//   m.onOff({powerOnBehavior:false, endpointNames:["1","2"]})  -> 2 relays
//   m.electricityMeter({endpointNames:["1","2"]})              -> both, ep1/2
//   m.commandsOnOff({endpointNames:["3","4"]})                 -> action ep3/4
//   m.commandsLevelCtrl({endpointNames:["3","4"]})
// Same gap shape as ZGA002, but the relays + metering are per-endpoint on
// ep1 AND ep2 (so dispatch suffixes their runtime keys to state_1/state_2,
// energy_1/energy_2, etc. via the endpoint_map — exposes stay bare):
//   (1) m.electricityMeter() cluster:"both" — port wired only kFzMetering
//       (0x0702 energy), dropping haElectricalMeasurement (0x0B04
//       power/voltage/current). Added kFzElectricalMeasurement + V/I
//       exposes + 0x0B04 binds on ep1+ep2.
//   (2) m.deviceTemperature() (0x0002) dropped — added kFzDeviceTemperature
//       + device_temperature expose + 0x0002 bind (device_temperature is an
//       always-global key, not suffixed per endpoint).
//   (3) commandsOnOff/LevelCtrl on ep3/ep4 dropped — added kFzCommand*
//       + `action` enum + endpoint_action_suffix (action_3 / action_4).
// z2m-source: aeotec.ts #ZGA003.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::aeotec {
namespace {
const FzConverter* const kFz_ZGA003[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
    &::zhc::generic::kFzDeviceTemperature,
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandToggle,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
const TzConverter* const kTz_ZGA003[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_ZGA003[] = { "ZGA003" };

constexpr ::zhc::EndpointLabel kEndpoints_ZGA003[] = { {"1", 1}, {"2", 2}, {"3", 3}, {"4", 4} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
    {"device_temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006}, {2, 0x0006},
    {1, 0x0702}, {2, 0x0702},
    {1, 0x0B04}, {2, 0x0B04},
    {1, 0x0002},
    {3, 0x0006}, {4, 0x0006},
    {3, 0x0008}, {4, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZGA003{
    .zigbee_models=kModels_ZGA003, .zigbee_models_count=sizeof(kModels_ZGA003)/sizeof(kModels_ZGA003[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZGA003", .vendor="Aeotec",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZGA003, .from_zigbee_count=sizeof(kFz_ZGA003)/sizeof(kFz_ZGA003[0]),
    .to_zigbee=kTz_ZGA003, .to_zigbee_count=sizeof(kTz_ZGA003)/sizeof(kTz_ZGA003[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_ZGA003,
    .endpoint_map_count = sizeof(kEndpoints_ZGA003)/sizeof(kEndpoints_ZGA003[0]),
    .endpoint_action_suffix=true,
};

}  // namespace zhc::devices::aeotec
