// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Gs SOHM-I1 — graduated from generated/ for a parity fix.
// Open and close sensor
// z2m-source: gs.ts #SOHM-I1 — m.iasZoneAlarm({zoneType:"contact",
//   zoneAttributes:["alarm_1","tamper","battery_low"]}) + m.battery.
//
// Parity fix (IAS dead-key): generic kFzIasZone emitted the bare key
// "alarm" while z2m's zoneType "contact" + alarm_1 publishes the
// semantic key "contact" off zoneStatus bit 0. Swapped to the typed
// kFzIasContactAlarm converter (emits "contact" + tamper + battery_low)
// and renamed the primary expose accordingly. (z2m additionally inverts
// the contact payload polarity; the generic typed converter reports the
// raw bit, matching the established marathon contact handling — see
// feibit/Fei_SDM01ZB.cpp + centralite.)
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::gs {
namespace {
const FzConverter* const kFz_SOHM_I1[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_SOHM_I1[] = { "SOHM-I1" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SOHM_I1{
    .zigbee_models=kModels_SOHM_I1, .zigbee_models_count=sizeof(kModels_SOHM_I1)/sizeof(kModels_SOHM_I1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SOHM-I1", .vendor="Gs",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SOHM_I1, .from_zigbee_count=sizeof(kFz_SOHM_I1)/sizeof(kFz_SOHM_I1[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::gs
