// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: BouffaloLab RMC002 — US plug smart socket, power_on_behavior +
// power_source override restored.
// z2m-source: bouffalo_lab.ts #RMC002 =
//   [m.onOff(), m.forcePowerSource({powerSource: "Mains (single phase)"})].
// Two axes were dropped by the Tier-1 auto-port:
//   1. m.onOff() defaults powerOnBehavior=true, wiring fz.power_on_behavior
//      (genOnOff 0x4003 startUpOnOff) + tz.power_on_behavior + the
//      power_on_behavior enum expose. Restored via kFzPowerOnBehavior /
//      kTzPowerOnBehavior1.
//   2. m.forcePowerSource({powerSource:"Mains (single phase)"}) → ZCL Basic
//      0x0007 = 0x01. Restored via power_source_override.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::bouffalo_lab {
namespace {
const FzConverter* const kFz_RMC002[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzPowerOnBehavior,
};
const TzConverter* const kTz_RMC002[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_RMC002[] = { "Bouffalolab" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_RMC002{
    .zigbee_models=kModels_RMC002, .zigbee_models_count=sizeof(kModels_RMC002)/sizeof(kModels_RMC002[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="RMC002", .vendor="BouffaloLab",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_RMC002, .from_zigbee_count=sizeof(kFz_RMC002)/sizeof(kFz_RMC002[0]),
    .to_zigbee=kTz_RMC002, .to_zigbee_count=sizeof(kTz_RMC002)/sizeof(kTz_RMC002[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .power_source_override=0x01,  // ZCL Basic 0x0007 = Mains (single phase)
};

}  // namespace zhc::devices::bouffalo_lab
