// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya SM0202 — auto-generated.
// Motion sensor
// z2m-source: tuya.ts #SM0202.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz_SM0202[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasZone,
};

constexpr const char* kModels_SM0202[] = { "SM0202" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"alarm", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_SM0202[] = {
    {"Cleverio","SS200"},
    {"Marmitek","SM0202_1"},
};
extern const PreparedDefinition kDefSM0202{
    .zigbee_models=kModels_SM0202, .zigbee_models_count=sizeof(kModels_SM0202)/sizeof(kModels_SM0202[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SM0202", .vendor="Tuya",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_SM0202, .white_labels_count=sizeof(kWhiteLabels_SM0202)/sizeof(kWhiteLabels_SM0202[0]),
    .from_zigbee=kFz_SM0202, .from_zigbee_count=sizeof(kFz_SM0202)/sizeof(kFz_SM0202[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tuya
