// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya SM0212 — auto-generated.
// Gas sensor
// z2m-source: tuya.ts #SM0212.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz_SM0212[] = {
    &::zhc::generic::kFzIasZone,
};

constexpr const char* kModels_SM0212[] = { "SM0212" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"alarm", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefSM0212{
    .zigbee_models=kModels_SM0212, .zigbee_models_count=sizeof(kModels_SM0212)/sizeof(kModels_SM0212[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SM0212", .vendor="Tuya",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SM0212, .from_zigbee_count=sizeof(kFz_SM0212)/sizeof(kFz_SM0212[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tuya
