// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya SNTZ007 — auto-generated.
// Rechargeable Zigbee contact sensor
// z2m-source: tuya.ts #SNTZ007.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz_SNTZ007[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasZone,
};

constexpr const char* kModels_SNTZ007[] = { "RH3001" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"alarm", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefSNTZ007{
    .zigbee_models=kModels_SNTZ007, .zigbee_models_count=sizeof(kModels_SNTZ007)/sizeof(kModels_SNTZ007[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SNTZ007", .vendor="Tuya",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SNTZ007, .from_zigbee_count=sizeof(kFz_SNTZ007)/sizeof(kFz_SNTZ007[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tuya
