// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS004F 4-button scene remote.
// z2m-source: tuya.ts #TS004F.
#include "definitions/tuya/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
// TS004F is rotary-capable (4 buttons + clockwise/counter-clockwise wheel).
// In event-mode it emits cmd 0xFD `tuyaAction` (single/double/hold) and
// cmd 0xFC `tuyaAction2` (rotate_right/rotate_left). kFzTuyaMultiAction
// handles both. Bare action string (no endpoint prefix) — TS004F surfaces
// all buttons on EP1 so per-button differentiation needs a different
// mechanism (separate ticket).
const FzConverter* const kFz[] = { &::zhc::tuya::kFzTuyaMultiAction };
constexpr const char* kModels[] = { "TS004F" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS004F[] = {
    {"Zemismart","ZMR4"},
};
extern const PreparedDefinition kDefTS004F{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS004F",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS004F, .white_labels_count=sizeof(kWhiteLabels_TS004F)/sizeof(kWhiteLabels_TS004F[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
