// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0041 1-button scene remote. z2m-source: tuya.ts.
#include "definitions/tuya/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = { &::zhc::tuya::kFzTuyaOnOffAction };
constexpr const char* kModels[] = { "TS0041" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0041[] = {
    {"Tuya","SH-SC07"},
    {"Tuya","MINI-ZSB"},
    {"Nous","LZ4"},
    {"Marmitek","Push_LE"},
    {"Smart9","S9TSZGB"},
    {"Lonsonho","TS0041"},
    {"Benexmart","ZM-sui1"},
};
extern const PreparedDefinition kDefTS0041{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0041",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0041, .white_labels_count=sizeof(kWhiteLabels_TS0041)/sizeof(kWhiteLabels_TS0041[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
