// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0011 single wall-switch.
// z2m-source: tuya.ts #TS0011.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = { &::zhc::generic::kFzOnOff };
const TzConverter* const kTz[] = { &::zhc::generic::kTzOnOff };
constexpr const char* kModels[] = { "TS0011" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0011[] = {
    {"Nous","LZ3"},
    {"Vrey","VR-X712U-0013"},
    {"TUYATEC","GDKES-01TZXD"},
    {"Lonsonho","QS-Zigbee-S05-L"},
    {"Mercator Ikuü","SSW01"},
};
extern const PreparedDefinition kDefTS0011{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0011",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0011, .white_labels_count=sizeof(kWhiteLabels_TS0011)/sizeof(kWhiteLabels_TS0011[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
