// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tuya TS0121 smart plug with std haElectricalMeasurement + seMetering.
// z2m-source: tuya.ts #TS0121.
#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"
#include "definitions/tuya/_shared.hpp"   // kReportsPlugVIPE_1ep
namespace zhc::devices::tuya {
namespace {
constexpr ::zhc::lumi::LumiPowerCalibration kPower{1,1000,10};
constexpr ::zhc::lumi::LumiMeterCalibration kMeter{1000};
constexpr FzConverter kFzP{
    .family=FrameFamily::Zcl,.cluster="haElectricalMeasurement",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_power},.user_config=&kPower };
constexpr FzConverter kFzM{
    .family=FrameFamily::Zcl,.cluster="seMetering",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_electricity_meter},.user_config=&kMeter };
const FzConverter* const kFz[] = { &::zhc::generic::kFzOnOff, &kFzP, &kFzM };
const TzConverter* const kTz[] = { &::zhc::generic::kTzOnOff };
constexpr const char* kModels[] = { "TS0121" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

// Hand-written bindings (supersedes kAutoBindings): the auto block binds only
// genOnOff, but this plug also decodes + reports haElectricalMeasurement
// (0x0B04) and seMetering (0x0702). run_configure walks .bindings[]/.reports[]
// independently, so every reported cluster must be bound on EP1 or its reports
// have no route to the coordinator. z2m binds these clusters via tuyaOnOff.
constexpr BindingSpec kBindings[] = {
    {1, 0x0006},    // genOnOff
    {1, 0x0B04},    // haElectricalMeasurement (voltage/current/power)
    {1, 0x0702},    // seMetering (energy)
};

extern const PreparedDefinition kDefTS0121{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0121",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kBindings,.bindings_count=sizeof(kBindings)/sizeof(kBindings[0]),
.reports=::zhc::tuya::kReportsPlugVIPE_1ep,
.reports_count=::zhc::tuya::kReportsPlugVIPE_1ep_count,
};
}
