// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tuya TS011F smart plug with standard haElectricalMeasurement.
// z2m-source: tuya.ts #TS011F.
#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"
#include "definitions/tuya/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
// z2m TS011F_plug_1 configure saves acCurrentDivisor 1000 and seMetering
// divisor 100 (→ kWh); nothing for voltage/power, so
// tuya.fz.TS011F_electrical_measurement passes them through (factor 1).
// (_TZ3000_typdpbpg uses acCurrentDivisor 2000 — no ZHAC def for it yet.)
constexpr ::zhc::lumi::LumiPowerCalibration kPower{1, 1000, 1};
constexpr ::zhc::lumi::LumiMeterCalibration kMeter{100};

constexpr FzConverter kFzPowerBound{
    .family=FrameFamily::Zcl,.cluster="haElectricalMeasurement",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_power},.user_config=&kPower };
constexpr FzConverter kFzMeterBound{
    .family=FrameFamily::Zcl,.cluster="seMetering",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_electricity_meter},.user_config=&kMeter };

// z2m tuya.fz/tz power_on_behavior_1 (TS011F_plug_1): genOnOff 0x8002
// moesStartUpOnOff, off=0 / on=1 / previous=2. The shared
// kFzTuyaPowerOnBehavior / kTzTuyaPowerOnBehavior carry a 4-value table
// (2=toggle, 3=previous) that would mislabel this plug, hence a local pair.
constexpr const char* kPobOpts[] = { "off", "on", "previous" };

bool fz_power_on_behavior_1(const DecodedMessage& msg, const FzConverter&,
                            const PreparedDefinition&, RuntimeContext&,
                            FixedPayload<ZHC_FIXED_PAYLOAD_CAP>& out) {
    const Value* v = msg.payload.find("32770");   // 0x8002
    if (!v) return false;
    std::uint64_t raw;
    if      (v->type == ValueType::Uint) raw = v->u;
    else if (v->type == ValueType::Int)  raw = static_cast<std::uint64_t>(v->i);
    else return false;
    if (raw > 2) return false;
    Value o{}; o.type = ValueType::StringRef; o.str = kPobOpts[raw];
    out.put("power_on_behavior", o);
    return true;
}
constexpr FzConverter kFzPowerOnBehavior1{
    .family=FrameFamily::Zcl,.cluster="genOnOff",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&fz_power_on_behavior_1},.user_config=nullptr };
constexpr ::zhc::generic::ZclWriteLookup kPobLut[] = { {"off", 0}, {"on", 1}, {"previous", 2} };
constexpr ::zhc::generic::ZclWriteSpec kSpecPob{
    "power_on_behavior", 0x8002, 0x30, 0, kPobLut, 3 };
constexpr TzConverter kTzPowerOnBehavior1{
    "power_on_behavior", "genOnOff", 0x0006, 0x02,
    &::zhc::generic::tz_zcl_write_attr, &kSpecPob };

const FzConverter* const kFz[] = {
    &::zhc::generic::kFzOnOff,
    &kFzPowerBound,
    &kFzMeterBound,
    &kFzPowerOnBehavior1,
};
const TzConverter* const kTz[] = { &::zhc::generic::kTzOnOff, &kTzPowerOnBehavior1 };
constexpr const char* kModels[] = { "TS011F" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

// Hand-written exposes (supersede kAutoExposes): z2m tuyaOnOff
// electricalMeasurements adds power/current/voltage/energy; the auto block
// dropped them, so decoded metering never surfaced.
constexpr Expose kExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, kPobOpts, 3,
     ExposeCategory::Config},
    {"power",   ExposeType::Numeric, Access::State, "W",   nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V",   nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A",   nullptr, nullptr, 0},
    {"energy",  ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
};

// Hand-written bindings (supersedes kAutoBindings): the auto block binds only
// genOnOff, but this plug also decodes + reports haElectricalMeasurement
// (0x0B04) and seMetering (0x0702). run_configure walks .bindings[]/.reports[]
// independently, so every reported cluster must be bound on EP1 or its reports
// have no route to the coordinator. z2m binds these clusters via tuyaOnOff.
constexpr BindingSpec kBindings[] = {
    {1, 0x0006},    // genOnOff
    {1, 0x0B04},    // haElectricalMeasurement (voltage/current/power)
    {1, 0x0702},    // seMetering (energy)
};

// ── Elivco LSPA9 (`_TZ3000_okaz9tjs`) ─────────────────────────────────
// z2m TS011F_plug_1 whitelabel. Same converters (kFz/kTz) as the generic.
// configure: magic packet + bind genOnOff/haElectricalMeasurement/seMetering,
// and for this manufacturer NO reporting config at all (z2m #29034 —
// configureReporting breaks its metering). Matched by manufacturer name so
// it wins Pass 1 of find_definition over the bare-model kDefTS011F.
namespace {
constexpr const char* kManusOkaz[] = { "_TZ3000_okaz9tjs" };
constexpr WhiteLabel kWhiteLabelsOkaz[] = { {"Elivco", "LSPA9"} };

constexpr Expose kExposesOkaz[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, kPobOpts, 3,
     ExposeCategory::Config},
    {"power",   ExposeType::Numeric, Access::State, "W",   nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V",   nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A",   nullptr, nullptr, 0},
    {"energy",  ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
};

// z2m tuya.configureMagicPacket — genBasic read of manufacturerName,
// zclVersion, appVersion, modelId, powerSource, 0xFFFE (LE attr ids).
constexpr std::uint8_t kMagicAttrs[] = {
    0x04, 0x00,  0x00, 0x00,  0x01, 0x00,
    0x05, 0x00,  0x07, 0x00,  0xFE, 0xFF,
};
constexpr ConfigStep kConfigSteps[] = {
    { ConfigStepOp::Wait, 0, 0,      0x00, 0, nullptr, 0, 300 },
    { ConfigStepOp::Read, 1, 0x0000, 0x00, 0, kMagicAttrs, sizeof(kMagicAttrs), 0 },
};
}

extern const PreparedDefinition kDefTS011F_okaz9tjs{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManusOkaz,.manufacturer_names_count=1,
    .model="TS011F",.vendor="Tuya",
    .meta=nullptr,.exposes=kExposesOkaz,.exposes_count=sizeof(kExposesOkaz)/sizeof(kExposesOkaz[0]),
    .white_labels=kWhiteLabelsOkaz,.white_labels_count=1,
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
    .bindings=kBindings,.bindings_count=sizeof(kBindings)/sizeof(kBindings[0]),
    .reports=nullptr,.reports_count=0,
    .config_steps=kConfigSteps,
    .config_steps_count=sizeof(kConfigSteps)/sizeof(kConfigSteps[0]),
    // Never reports 0x0B04/0x0702 even bound (owner's hub, 3 days, zero
    // metering frames) and must not get configureReporting (#29034), so
    // the hub reads the meter itself. z2m's TS011F_plug_1 has no poll;
    // this is the electricityMeasurementPoll({metering:true}) shape.
    .meter_poll=kMeterPollElectrical|kMeterPollMetering,
};

extern const PreparedDefinition kDefTS011F{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS011F",.vendor="Tuya",
    .meta=nullptr,.exposes=kExposes,.exposes_count=sizeof(kExposes)/sizeof(kExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kBindings,.bindings_count=sizeof(kBindings)/sizeof(kBindings[0]),
.reports=::zhc::tuya::kReportsPlugVIPE_1ep,
.reports_count=::zhc::tuya::kReportsPlugVIPE_1ep_count,
    // Backstop for whitelabels that ignore configureReporting: a read
    // every poll interval costs two small frames per plug.
    .meter_poll=kMeterPollElectrical|kMeterPollMetering,
};
}
