// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tuya TS011F smart plug with standard haElectricalMeasurement.
// z2m-source: tuya.ts #TS011F.
#include "definitions/_generic/_shared.hpp"
#include "definitions/lumi/_shared.hpp"
#include "definitions/tuya/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
constexpr ::zhc::lumi::LumiPowerCalibration kPower{1, 1000, 10};
constexpr ::zhc::lumi::LumiMeterCalibration kMeter{1000};

constexpr FzConverter kFzPowerBound{
    .family=FrameFamily::Zcl,.cluster="haElectricalMeasurement",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_power},.user_config=&kPower };
constexpr FzConverter kFzMeterBound{
    .family=FrameFamily::Zcl,.cluster="seMetering",
    .type_mask=type_bit(MessageType::AttributeReport)|type_bit(MessageType::ReadResponse),
    .command_id=WILDCARD_CMD_ID,.attr_id=WILDCARD_ATTR_ID,.endpoint=WILDCARD_ENDPOINT,
    .frame_flags_mask=0,.frame_flags_value=0,.direction=Direction::ServerToClient,
    .fn={.zcl_fn=&::zhc::lumi::fz_lumi_electricity_meter},.user_config=&kMeter };

const FzConverter* const kFz[] = {
    &::zhc::generic::kFzOnOff,
    &kFzPowerBound,
    &kFzMeterBound,
    &::zhc::tuya::kFzTuyaPowerOnBehavior,
};
const TzConverter* const kTz[] = { &::zhc::generic::kTzOnOff };
constexpr const char* kModels[] = { "TS011F" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefTS011F{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS011F",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
