// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tuya TS0224 sound + flash siren — GRADUATED from generated/.
//
// z2m v26.99.0 parity: upstream added `m.iasWarningMaxDuration()` to this
// entry. Unlike the six other devices swept up in the same refactor, this
// one had NO prior max_duration surface at all (no fz.ias_wd, no
// tz.ias_max_duration, no numeric) — the modernExtend is a genuinely new
// control here, not a rename. It exposes `max_duration` (ea.ALL, 0..65534 s)
// backed by ssIasWd 0x0502 attribute maxDuration (0x0000).
//
// Graduated so the added expose survives the next generator run.
//
// FIXED IN PASSING: `.zigbee_models_count` was the literal `1` rather than a
// sizeof expression. Any future fingerprint appended to kModelsGen_TS0224
// would have been silently ignored — the same literal-count trap found on
// TS0601_6gang_switch during the v26.95 sweep.
//
// Also switched to the canonical action converter while graduating: the
// legacy alias this file used and kFzTuyaActionFlat are the same converter
// (see definitions/tuya/_shared.hpp), and the guard rejects the alias on
// files it has no baseline entry for.
//
// z2m-source: tuya.ts #TS0224.
#include "definitions/_generic/_shared.hpp"
#include "definitions/tuya/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFzGen_TS0224[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &::zhc::tuya::kFzTuyaActionFlat,
    &::zhc::generic::kFzIasWdMaxDuration,
};
const TzConverter* const kTzGen_TS0224[] = {
    &::zhc::generic::kTzIasWdMaxDuration,
};
constexpr const char* kModelsGen_TS0224[] = { "TS0224" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"max_duration", ExposeType::Numeric, Access::StateSet, "s",
     "Maximum time that the alarm will be active", nullptr, 0,
     ExposeCategory::Config, 0, 65534, 1},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
    {1, 0x0006},
    {1, 0x0502},   // ssIasWd — carries maxDuration
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefGen_TS0224{
    .zigbee_models=kModelsGen_TS0224,.zigbee_models_count=sizeof(kModelsGen_TS0224)/sizeof(kModelsGen_TS0224[0]),
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,
    .manufacturer_names_count=0,
    .model="TS0224",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFzGen_TS0224,.from_zigbee_count=sizeof(kFzGen_TS0224)/sizeof(kFzGen_TS0224[0]),
    .to_zigbee=kTzGen_TS0224,.to_zigbee_count=sizeof(kTzGen_TS0224)/sizeof(kTzGen_TS0224[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
