// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0202 IAS motion sensor. IAS alarm v2.
// z2m-source: tuya.ts #TS0202.
//   fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery,
//                fz.ias_occupancy_alarm_1_report]
//   exposes:    occupancy, battery_low, battery, battery_voltage, tamper
//   configure:  (none) — see IAS-enroll note below.
//
// IAS Zone enrollment is GLOBAL: the coordinator stack auto-enrolls any
// 0x0500 device reactively (writes attr 0x0010 IAS_CIE_Address + answers
// ZoneEnrollRequest with ZoneEnrollResponse) in
// zhac-components/components/zigbee_mgr/zigbee_mgr.cpp
// (zcl_maybe_respond_ias_enroll). z2m itself ships NO `configure:` for
// this device, so there is nothing to port and no per-def config_steps
// are needed — the binding below is the only join-time setup. ZHC's
// ConfigStepOp has no Write op precisely because IAS enroll never needs
// one. The `_report` (attribute-report) decode path that z2m adds is not
// expressible with the command-only fz_ias_typed primitive; ZHC decodes
// the ZoneStatusChangeNotification command (the post-enroll mechanism)
// via kFzIasMotionAlarm, matching the sibling Tuya IAS sensors.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::generic::kFzIasMotionAlarm,   // occupancy + tamper + battery_low
    &::zhc::generic::kFzBattery,          // battery (%) + voltage (mV)
};
constexpr const char* kModels[] = { "TS0202", "WHD02" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},   // genPowerCfg — battery reporting
    {1, 0x0500},   // ssIasZone — IAS zone status notifications
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0202[] = {
    {"MiBoxer","PIR1-ZB"},
    {"Tuya","ZMS01"},
    {"Nous","E2"},
    {"Tuya","809WZT"},
    {"Niceboy","ORBIS Motion Sensor"},
    {"Luminea","ZX-5311"},
    {"Tuya","ZP01"},
    {"Tuya","HW500A"},
    {"Nedis","ZBSM10WT"},
    {"Mercator Ikuü","SMA02P"},
    {"Tuya","TY-ZPR06"},
    {"Tesla Smart","TS0202"},
};
extern const PreparedDefinition kDefTS0202{
    .zigbee_models=kModels,.zigbee_models_count=2,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0202",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0202, .white_labels_count=sizeof(kWhiteLabels_TS0202)/sizeof(kWhiteLabels_TS0202[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
