// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0210 IAS vibration sensor.
// z2m-source: tuya.ts #TS0210.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = { &::zhc::generic::kFzBattery };
constexpr const char* kModels[] = { "TS0210" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0210[] = {
    {"Niceboy","ORBIS Vibration Sensor"},
    {"iHseno","_TZ3000_lzdjjfss"},
    {"ONENUO","TS0210_5oy7cysk"},
};
extern const PreparedDefinition kDefTS0210{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0210",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0210, .white_labels_count=sizeof(kWhiteLabels_TS0210)/sizeof(kWhiteLabels_TS0210[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
