// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0205 IAS smoke sensor. IAS alarm v2.
// z2m-source: tuya.ts #TS0205.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = { &::zhc::generic::kFzIgnoreIlluminanceReport };
constexpr const char* kModels[] = { "TS0205" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"illuminance", ExposeType::Numeric, Access::State, "lx", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0400},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0205[] = {
    {"Tuya","TS0205_smoke_2"},
    {"Nedis","ZBDS10WT"},
    {"Tesla Smart","TSL-SEN-SMOKE"},
    {"Dongguan Daying Electornics Technology","YG400A"},
};
extern const PreparedDefinition kDefTS0205{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0205",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0205, .white_labels_count=sizeof(kWhiteLabels_TS0205)/sizeof(kWhiteLabels_TS0205[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
