// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0203 IAS contact sensor (non-DP).
// z2m-source: tuya.ts #TS0203.
//   fromZigbee: [fz.ias_contact_alarm_1, fz.battery,
//                fz.ias_contact_alarm_1_report]
//   exposes:    contact, battery, battery_voltage, tamper, battery_low
//   configure:  (none) — see IAS-enroll note below.
//
// IAS Zone enrollment is GLOBAL: the coordinator stack auto-enrolls any
// 0x0500 device reactively (writes attr 0x0010 IAS_CIE_Address + answers
// ZoneEnrollRequest with ZoneEnrollResponse) in
// zhac-components/components/zigbee_mgr/zigbee_mgr.cpp
// (zcl_maybe_respond_ias_enroll). z2m itself ships NO `configure:` for
// this device, so there is nothing to port and no per-def config_steps
// are needed — the bindings below are the only join-time setup. ZHC's
// ConfigStepOp has no Write op precisely because IAS enroll never needs
// one. The `_report` (attribute-report) decode path that z2m adds is not
// expressible with the command-only fz_ias_typed primitive; ZHC decodes
// the ZoneStatusChangeNotification command (the post-enroll mechanism)
// via kFzIasContactAlarm, matching the sibling Tuya IAS sensors.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::generic::kFzIasContactAlarm,  // contact + tamper + battery_low
    &::zhc::generic::kFzBattery,          // battery (%) + voltage (mV)
};
constexpr const char* kModels[] = { "TS0203", "ZG-102Z" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},   // genPowerCfg — battery reporting
    {1, 0x0500},   // ssIasZone — IAS zone status notifications
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0203[] = {
    {"Niceboy","ORBIS Windows & Door Sensor"},
    {"Tuya","ZD06"},
    {"Tuya","ZD08"},
    {"Tuya","MC500A"},
    {"Tuya","19DZT"},
    {"Tuya","DS04"},
    {"Moes","ZSS-JM-GWM-C-MS"},
    {"Moes","ZSS-S01-GWM-C-MS"},
    {"Moes","ZSS-X-GWM-C"},
    {"Luminea","ZX-5232"},
    {"QA","QASD1"},
    {"Nous","E3"},
    {"Woox","R7047"},
    {"Wing","WZDA1"},
    {"CR Smart Home","TS0203"},
    {"Tuya","iH-F001"},
    {"Tesla Smart","TSL-SEN-DOOR"},
    {"Cleverio","SS100"},
    {"HOBEIAN","ZG-102ZA"},
};
extern const PreparedDefinition kDefTS0203{
    .zigbee_models=kModels,.zigbee_models_count=2,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0203",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0203, .white_labels_count=sizeof(kWhiteLabels_TS0203)/sizeof(kWhiteLabels_TS0203[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
