// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TS0203 IAS contact sensor (non-DP).
// z2m-source: tuya.ts #TS0203.
#include "definitions/_generic/_shared.hpp"
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = { &::zhc::generic::kFzBattery };
constexpr const char* kModels[] = { "TS0203", "ZG-102Z" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0203[] = {
    {"Niceboy","ORBIS Windows & Door Sensor"},
    {"Tuya","ZD06"},
    {"Tuya","ZD08"},
    {"Tuya","MC500A"},
    {"Tuya","19DZT"},
    {"Tuya","DS04"},
    {"Moes","ZSS-JM-GWM-C-MS"},
    {"Moes","ZSS-S01-GWM-C-MS"},
    {"Moes","ZSS-X-GWM-C"},
    {"Luminea","ZX-5232"},
    {"QA","QASD1"},
    {"Nous","E3"},
    {"Woox","R7047"},
    {"Wing","WZDA1"},
    {"CR Smart Home","TS0203"},
    {"Tuya","iH-F001"},
    {"Tesla Smart","TSL-SEN-DOOR"},
    {"Cleverio","SS100"},
    {"HOBEIAN","ZG-102ZA"},
};
extern const PreparedDefinition kDefTS0203{
    .zigbee_models=kModels,.zigbee_models_count=2,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0203",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0203, .white_labels_count=sizeof(kWhiteLabels_TS0203)/sizeof(kWhiteLabels_TS0203[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=nullptr,.to_zigbee_count=0,
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
