// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Tuya TS0502A tunable-white light. z2m-source: tuya.ts.
#include "definitions/_generic/_shared.hpp"
#include "definitions/tuya/_shared.hpp"   // kReportsLightCCT_1ep
namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz[] = {
    &::zhc::generic::kFzOnOff, &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzColorTemperature };
const TzConverter* const kTz[] = {
    &::zhc::generic::kTzOnOff, &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzColorTemp };
constexpr const char* kModels[] = { "TS0502A" };
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"color_temp", ExposeType::Numeric, Access::StateSet, "mired", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0300},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TS0502A[] = {
    {"Lidl","HG06492B/HG08130B"},
    {"Lidl","HG06492A/HG08130A"},
    {"Lidl","HG06492C/HG08130C/HG09154C"},
    {"Lidl","14147206L"},
    {"Lidl","14153905L"},
};
extern const PreparedDefinition kDefTS0502A{
    .zigbee_models=kModels,.zigbee_models_count=1,
    .manufacturer_name_prefix=nullptr,.manufacturer_names=nullptr,.manufacturer_names_count=0,
    .model="TS0502A",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_TS0502A, .white_labels_count=sizeof(kWhiteLabels_TS0502A)/sizeof(kWhiteLabels_TS0502A[0]),
    .from_zigbee=kFz,.from_zigbee_count=sizeof(kFz)/sizeof(kFz[0]),
    .to_zigbee=kTz,.to_zigbee_count=sizeof(kTz)/sizeof(kTz[0]),
    .configure=nullptr,.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
// Phase-2b Batch 3: CCT reporting (onOff + currentLevel + colorTemperature)
// mirroring z2m reporting.ts onOff/brightness/colorTemperature. kAutoBindings
// already binds genOnOff (0x0006) + genLevelCtrl (0x0008) + lightingColorCtrl
// (0x0300) on EP1, covering every reported cluster.
.reports=::zhc::tuya::kReportsLightCCT_1ep,
.reports_count=::zhc::tuya::kReportsLightCCT_1ep_count,
};
}
