// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 1: Tuya TT001ZAV20 — auto-generated.
// Temperature & humidity sensor
// z2m-source: tuya.ts #TT001ZAV20.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::tuya {
namespace {
const FzConverter* const kFz_TT001ZAV20[] = {
    &::zhc::generic::kFzBattery,
};

constexpr const char* kModels_TT001ZAV20[] = { "RH3052" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefTT001ZAV20{
    .zigbee_models=kModels_TT001ZAV20, .zigbee_models_count=sizeof(kModels_TT001ZAV20)/sizeof(kModels_TT001ZAV20[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="TT001ZAV20", .vendor="Tuya",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_TT001ZAV20, .from_zigbee_count=sizeof(kFz_TT001ZAV20)/sizeof(kFz_TT001ZAV20[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tuya
