// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: _TZE200_bjawzodf generic Tuya smart plug.
//
// Uses tuyaBase (cluster register + mcuSyncTime hook) plus a 3-entry
// DP map: dp1 state / dp18 current_mA /dp19 voltage_dV.
//
// z2m-source: tuya.ts #TZE200_bjawzodf (Tuya generic metering plug).

#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"

namespace zhc::devices::tuya {

namespace {

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries[] = {
    { 1,  "state",   ::zhc::TuyaDpType::Bool,    1,    nullptr, 0 },
    { 18, "current", ::zhc::TuyaDpType::Numeric, 1000, nullptr, 0 },
    { 19, "voltage", ::zhc::TuyaDpType::Numeric, 10,   nullptr, 0 },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap{ kEntries, 3 };

constexpr FzConverter kFzDpBound{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap,
};

const FzConverter* const kFz[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDpBound,
};

constexpr const char* kModels[] = { "TS0601" };
constexpr const char* kManuNames[] = { "_TZE200_bjawzodf" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefTZE200_bjawzodf{
    .zigbee_models            = kModels,
    .zigbee_models_count      = 1,
    .manufacturer_name_prefix = nullptr,
    .manufacturer_names       = kManuNames,
    .manufacturer_names_count = 1,
    .model                    = "TS0601_plug_bjawzodf",
    .vendor                   = "Tuya",
    .meta                     = nullptr,
    .exposes=kAutoExposes,
    .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels             = nullptr,
    .white_labels_count       = 0,
    .from_zigbee              = kFz,
    .from_zigbee_count        = sizeof(kFz) / sizeof(kFz[0]),
    .to_zigbee                = nullptr,
    .to_zigbee_count          = 0,
    .configure                = ::zhc::tuya::extend::tuya_base_configure(),
    .on_event                 = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::tuya
