// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: _TZE200_cpmgn2cf vibration.
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/dp.hpp"
#include "definitions/tuya/extend.hpp"
#include "definitions/tuya/factories.hpp"
namespace zhc::devices::tuya {
namespace {
struct cfg { static constexpr ::zhc::tuya::TuyaDpMapEntry e[]={
    ::zhc::tuya::dp::binary(1,"vibration"),::zhc::tuya::dp::numeric(15,"battery",1)};
    static constexpr ::zhc::tuya::TuyaDatapointMap dp_map{e,2}; };
using FX=::zhc::tuya::factory::TuyaOnOff<cfg>;
constexpr const char* kM[]={"TS0601"}; constexpr const char* kN[]={"_TZE200_cpmgn2cf"};
}

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_TZE200_cpmgn2cf[] = {
    {"Immax","07732L"},
    {"Emos","P5630S"},
    {"THALEOS","HY368"},
    {"Moes","HY368"},
    {"Moes","HY369RT"},
    {"SHOJZJ","378RT"},
    {"Silvercrest","TVR01"},
    {"Immax","07732B"},
    {"Evolveo","Heat M30"},
};
extern const PreparedDefinition kDefTZE200_cpmgn2cf{
    .zigbee_models=kM,.zigbee_models_count=1,.manufacturer_name_prefix=nullptr,
    .manufacturer_names=kN,.manufacturer_names_count=1,.model="TS0601_cpmgn2cf",.vendor="Tuya",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),.white_labels=kWhiteLabels_TZE200_cpmgn2cf, .white_labels_count=sizeof(kWhiteLabels_TZE200_cpmgn2cf)/sizeof(kWhiteLabels_TZE200_cpmgn2cf[0]),
    .from_zigbee=FX::fz_list,.from_zigbee_count=FX::fz_count,
    .to_zigbee=FX::tz_list,.to_zigbee_count=FX::tz_count,
    .configure=::zhc::tuya::extend::tuya_base_configure(),.on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}
