// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: _TZE200_0nmiizme generic 1-gang Tuya smart switch.
// Uses factory::TuyaOnOff with a 1-entry DP map.
// z2m-source: tuya.ts #_TZE200_0nmiizme.

#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/dp.hpp"
#include "definitions/tuya/extend.hpp"
#include "definitions/tuya/factories.hpp"

namespace zhc::devices::tuya {
namespace {

struct cfg {
    static constexpr ::zhc::tuya::TuyaDpMapEntry entries[] = {
        ::zhc::tuya::dp::binary(1, "state"),
    };
    static constexpr ::zhc::tuya::TuyaDatapointMap dp_map{ entries, 1 };
};
using FX = ::zhc::tuya::factory::TuyaOnOff<cfg>;

constexpr const char* kModels[]    = { "TS0601" };
constexpr const char* kManuNames[] = { "_TZE200_0nmiizme" };
}


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefTZE200_0nmiizme{
    .zigbee_models            = kModels,
    .zigbee_models_count      = 1,
    .manufacturer_name_prefix = nullptr,
    .manufacturer_names       = kManuNames,
    .manufacturer_names_count = 1,
    .model                    = "TS0601_switch_0nmiizme",
    .vendor                   = "Tuya",
    .meta                     = nullptr,
    .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels             = nullptr, .white_labels_count = 0,
    .from_zigbee              = FX::fz_list, .from_zigbee_count = FX::fz_count,
    .to_zigbee                = FX::tz_list, .to_zigbee_count = FX::tz_count,
    .configure                = ::zhc::tuya::extend::tuya_base_configure(),
    .on_event                 = nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}
