// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Echostar SAGE206611 — hand-curated (was wrong-bundle / dead state).
// SAGE by Hughes single gang light switch (battery remote). z2m role:
//   fromZigbee: [fz.command_on, fz.command_off]
//   exposes:    [e.action(["on", "off"])]   toZigbee: []  (uncontrollable)
// i.e. the switch is a CONTROLLER that EMITS genOnOff On/Off *commands*
// (device is the client), surfaced as `action="on"`/`action="off"`. The
// auto-port mis-modelled it as a settable on/off `state` (kFzOnOff +
// kTzOnOff) — a dead control that never reflected the button presses.
// Replaced with the generic command decoders (kFzCommandOn/Off, which emit
// the z2m-matching "on"/"off" action literals) + an `action` enum, and
// dropped the bogus to_zigbee. Single endpoint -> no endpoint_map.
// z2m-source: echostar.ts #SAGE206611.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::echostar {
namespace {
const FzConverter* const kFz_SAGE206611[] = {
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
};
constexpr const char* kModels_SAGE206611[] = { " Switch" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SAGE206611{
    .zigbee_models=kModels_SAGE206611, .zigbee_models_count=sizeof(kModels_SAGE206611)/sizeof(kModels_SAGE206611[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SAGE206611", .vendor="Echostar",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SAGE206611, .from_zigbee_count=sizeof(kFz_SAGE206611)/sizeof(kFz_SAGE206611[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::echostar
