// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Echostar SAGE206612 — hand-curated (was wrong-bundle / missing action).
// SAGE by Hughes doorbell sensor (battery). z2m role:
//   fromZigbee: [fz.SAGE206612_state, fz.battery]
//   exposes:    [e.battery(), e.action(["bell1", "bell2"])]   toZigbee: []
// i.e. the doorbell EMITS genOnOff On/Off *commands* (device is the client),
// which z2m remaps commandOn->"bell1" / commandOff->"bell2" and surfaces as
// `action`; plus a battery report. The auto-port mis-modelled it as a
// settable on/off `state` (kFzOnOff + kTzOnOff) — a dead control — and
// DROPPED the action entirely (the doorbell's only real signal). Replaced
// the on/off with the vendor kFzSageBellAction converter (echostar/_shared.cpp,
// the bell1/bell2 map), kept kFzBattery, swapped the `state` binary for an
// `action` enum, and dropped the bogus to_zigbee. Single endpoint -> no
// endpoint_map.
// z2m-source: echostar.ts #SAGE206612.
#include "definitions/_generic/_shared.hpp"
#include "definitions/echostar/_shared.hpp"

namespace zhc::devices::echostar {
namespace {
const FzConverter* const kFz_SAGE206612[] = {
    &kFzSageBellAction,
    &::zhc::generic::kFzBattery,
};
constexpr const char* kModels_SAGE206612[] = { "   Bell" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SAGE206612{
    .zigbee_models=kModels_SAGE206612, .zigbee_models_count=sizeof(kModels_SAGE206612)/sizeof(kModels_SAGE206612[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SAGE206612", .vendor="Echostar",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SAGE206612, .from_zigbee_count=sizeof(kFz_SAGE206612)/sizeof(kFz_SAGE206612[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::echostar
