// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Ihorn LH-09521 — graduated from generated/.
// Indoor siren
// z2m-source: ihorn.ts #LH-09521 (fz.ias_smoke_alarm_1 -> `smoke`, bit0; tz.warning).
// Fix: generic kFzIasZone emitted the bare key "alarm" — the z2m decoder
// publishes `smoke` (zoneStatus bit0). Swapped in typed kFzIasSmokeAlarm and
// renamed the expose from "alarm" to "smoke". The siren control write path
// (kTzWarning) is unchanged.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::ihorn {
namespace {
const FzConverter* const kFz_LH_09521[] = {
    &::zhc::generic::kFzIasSmokeAlarm,
};
const TzConverter* const kTz_LH_09521[] = {
    &::zhc::generic::kTzWarning,
};
constexpr const char* kModels_LH_09521[] = { "LH09521" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"smoke", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_LH_09521{
    .zigbee_models=kModels_LH_09521, .zigbee_models_count=sizeof(kModels_LH_09521)/sizeof(kModels_LH_09521[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="LH-09521", .vendor="Ihorn",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_LH_09521, .from_zigbee_count=sizeof(kFz_LH_09521)/sizeof(kFz_LH_09521[0]),
    .to_zigbee=kTz_LH_09521, .to_zigbee_count=sizeof(kTz_LH_09521)/sizeof(kTz_LH_09521[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::ihorn
