// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Ihorn LH03121 — graduated from generated/.
// Door contact DNAKE SH-DM-S01
// z2m-source: ihorn.ts #LH03121 (m.iasZoneAlarm zoneType:"contact" -> `contact`, bit0; m.battery).
// Fix: generic kFzIasZone emitted the bare key "alarm" while the expose
// declared the semantic key; swapped in typed kFzIasContactAlarm (emits `contact`).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::ihorn {
namespace {
const FzConverter* const kFz_LH03121[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
};

constexpr const char* kModels_LH03121[] = { "LH03121" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_LH03121{
    .zigbee_models=kModels_LH03121, .zigbee_models_count=sizeof(kModels_LH03121)/sizeof(kModels_LH03121[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="LH03121", .vendor="Ihorn",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_LH03121, .from_zigbee_count=sizeof(kFz_LH03121)/sizeof(kFz_LH03121[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::ihorn
