// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Novo C10-3E-1.2 — Tuya-DP curtain switch (graduated from generated/).
//
// The auto-port wired the GENERIC windowCovering (cluster 0x0102) converters
// kFzCoverPosition / kTzCoverPosition and bound endpoint 1 to 0x0102. But this
// is a TS0601 / _TZE200_swhwv3k3 Tuya-MCU device: it speaks ONLY the 0xEF00
// (manuSpecificTuya) datapoint stream. Nothing arrives on 0x0102, so position,
// state and the set path were all dead (classic Tuya-MCU misroute).
//
// z2m decodes this via legacy.fz.tuya_cover / legacy.tz.tuya_cover_control,
// i.e. the 0xEF00 DP map. Ported to the generic fz_tuya_datapoints DP table:
//
//   DP 1   state        Enum {0:OPEN, 1:STOP, 2:CLOSE}  (getCoverStateEnums
//                       default for this mfr; also the tz set-path enum order)
//   DP 2   position     Numeric 0..100 % (started moving / reported position)
//   DP 3   position     Numeric 0..100 % (coverArrived — same key)
//   DP 105 motor_speed  Numeric
//
// _TZE200_swhwv3k3 is NOT in z2m's coverPositionInvert list, so position is
// emitted as-is (no kTuyaDpFlagInvertPosition); the user invert_cover option is
// not modelled at the def layer. The set path (tz_tuya_datapoints) reuses the
// same map: "position" -> DP2 value, "state" -> DP1 enum (open/stop/close).
//
// z2m-source: novo.ts #C10-3E-1.2 ; lib/legacy.ts fz.tuya_cover /
//             tz.tuya_cover_control (dataPoints.state=1, coverPosition=2,
//             coverArrived=3, coverSpeed=105).
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"

namespace zhc::devices::novo {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kEnum_C10_3E_1_2_state_dp1[] = {
    { 0, "OPEN" },
    { 1, "STOP" },
    { 2, "CLOSE" },
};

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries_C10_3E_1_2[] = {
    { 1,   "state",       ::zhc::TuyaDpType::Enum,    1, kEnum_C10_3E_1_2_state_dp1,
        sizeof(kEnum_C10_3E_1_2_state_dp1)/sizeof(kEnum_C10_3E_1_2_state_dp1[0]) },
    { 2,   "position",    ::zhc::TuyaDpType::Numeric, 1, nullptr, 0 },
    { 3,   "position",    ::zhc::TuyaDpType::Numeric, 1, nullptr, 0 },
    { 105, "motor_speed", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0 },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap_C10_3E_1_2{ kEntries_C10_3E_1_2, 4 };

constexpr FzConverter kFzDp_C10_3E_1_2{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap_C10_3E_1_2,
};
const FzConverter* const kFz_C10_3E_1_2[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDp_C10_3E_1_2,
};

constexpr TzConverter kTzDp_C10_3E_1_2{
    .key         = nullptr,                // wildcard — claims any mapped key
    .cluster     = "manuSpecificTuya",
    .cluster_id  = 0xEF00,
    .command_id  = 0x00,
    .fn          = &::zhc::tuya::tz_tuya_datapoints,
    .user_config = &kMap_C10_3E_1_2,
};
const TzConverter* const kTz_C10_3E_1_2[] = { &kTzDp_C10_3E_1_2 };

constexpr const char* kModels_C10_3E_1_2[] = { "TS0601" };
constexpr const char* kManus_C10_3E_1_2[] = { "_TZE200_swhwv3k3" };
}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"motor_speed", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_C10_3E_1_2{
    .zigbee_models=kModels_C10_3E_1_2, .zigbee_models_count=sizeof(kModels_C10_3E_1_2)/sizeof(kModels_C10_3E_1_2[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus_C10_3E_1_2, .manufacturer_names_count=sizeof(kManus_C10_3E_1_2)/sizeof(kManus_C10_3E_1_2[0]),
    .model="C10-3E-1.2", .vendor="Novo",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_C10_3E_1_2, .from_zigbee_count=sizeof(kFz_C10_3E_1_2)/sizeof(kFz_C10_3E_1_2[0]),
    .to_zigbee=kTz_C10_3E_1_2, .to_zigbee_count=sizeof(kTz_C10_3E_1_2)/sizeof(kTz_C10_3E_1_2[0]),
    .configure=::zhc::tuya::extend::tuya_base_configure(), .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::novo
