// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Frient WISZB-131 temperature & contact sensor — graduated from generated.
// Temperature and contact sensor.
//
// Parity fix: the generated port wired the generic kFzIasZone, which emits
// the bare key "alarm", but z2m's m.iasZoneAlarm({zoneType:"contact",
// zoneAttributes:["alarm_1","battery_low"]}) publishes "contact" (zoneStatus
// bit 0) + "battery_low" (bit 3). It also dropped the msTemperatureMeasurement
// channel that z2m wires via m.temperature(). Frient is the Develco rebrand —
// this mirrors the develco WISZB-120 fix exactly: swap in the typed
// kFzIasContactAlarm and add kFzTemperature (0x0402, endpoint-agnostic so the
// Develco separate-endpoint temperature report still decodes).
//
// z2m-source: frient.ts #WISZB-131 — m.battery() +
//             m.iasZoneAlarm({zoneType:"contact",
//             zoneAttributes:["alarm_1","battery_low"]}) + m.temperature().
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::frient {
namespace {
const FzConverter* const kFz_WISZB_131[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasContactAlarm,
    &::zhc::generic::kFzTemperature,
};

constexpr const char* kModels_WISZB_131[] = { "WISZB-131" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"contact", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_WISZB_131{
    .zigbee_models=kModels_WISZB_131, .zigbee_models_count=sizeof(kModels_WISZB_131)/sizeof(kModels_WISZB_131[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="WISZB-131", .vendor="Frient",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_WISZB_131, .from_zigbee_count=sizeof(kFz_WISZB_131)/sizeof(kFz_WISZB_131[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::frient
