// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Frient SMRZB-153 smart cable — graduated from generated.
// Smart Cable - Power switch with power measurement.
//
// Parity fix: z2m wires m.electricityMeter() with no args, whose default
// cluster is "both" → fromZigbee = [fz.electrical_measurement (0x0B04),
// fz.metering (0x0702)] exposing power, voltage, current, energy. The
// generated port wired only kFzMetering (0x0702) so the 0x0B04 electrical
// half (voltage/current) was dead. Add kFzElectricalMeasurement plus the
// voltage/current exposes and the 0x0B04 binding.
//
// z2m-source: frient.ts #SMRZB-153 — m.onOff({configureReporting:false}) +
//             m.electricityMeter() (cluster default "both").
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::frient {
namespace {
const FzConverter* const kFz_SMRZB_153[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
};
const TzConverter* const kTz_SMRZB_153[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_SMRZB_153[] = { "SMRZB-153" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

// z2m endpoint:()=>({default:2}) — genOnOff + metering live on EP2, so bind
// there (and route outbound onOff via default_endpoint=2 below).
constexpr BindingSpec kAutoBindings[] = {
    {2, 0x0006},
    {2, 0x0702},
    {2, 0x0B04},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SMRZB_153{
    .zigbee_models=kModels_SMRZB_153, .zigbee_models_count=sizeof(kModels_SMRZB_153)/sizeof(kModels_SMRZB_153[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SMRZB-153", .vendor="Frient",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SMRZB_153, .from_zigbee_count=sizeof(kFz_SMRZB_153)/sizeof(kFz_SMRZB_153[0]),
    .to_zigbee=kTz_SMRZB_153, .to_zigbee_count=sizeof(kTz_SMRZB_153)/sizeof(kTz_SMRZB_153[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .default_endpoint = 2,  // z2m endpoint:()=>({default:2}); outbound onOff → EP2
};

}  // namespace zhc::devices::frient
