// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Frient EMIZB-151 P1 electricity-meter interface — graduated from generated.
// Electricity Meter Interface 2 P1.
//
// Parity fix: z2m wires m.electricityMeter({threePhase:true,
// producedEnergy:true, tariffs:true}) whose default cluster is "both" →
// fromZigbee = [fz.electrical_measurement (0x0B04), fz.metering (0x0702)]
// exposing power, voltage, current, energy. The generated port wired only
// kFzMetering (0x0702) so the 0x0B04 electrical half (voltage/current) was
// dead. Add kFzElectricalMeasurement plus the voltage/current exposes and
// the 0x0B04 binding.
//
// Deferred (INFRA): the threePhase phase-b/c attrs (haElectricalMeasurement
// 0x090x), the producedEnergy summation (seMetering currentSummReceived)
// and the tariff tiers (currentTier1/2 Summ*) have no generic decoder — the
// shared kFzElectricalMeasurement/kFzMetering converters only decode the
// single-phase power/voltage/current/energy core. Those extra channels stay
// dead pending dedicated converters.
//
// z2m-source: frient.ts #EMIZB-151 —
//             m.electricityMeter({threePhase:true, producedEnergy:true,
//             tariffs:true}) (cluster default "both").
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::frient {
namespace {
const FzConverter* const kFz_EMIZB_151[] = {
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
};

constexpr const char* kModels_EMIZB_151[] = { "EMIZB-151" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0702},
    {1, 0x0B04},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_EMIZB_151{
    .zigbee_models=kModels_EMIZB_151, .zigbee_models_count=sizeof(kModels_EMIZB_151)/sizeof(kModels_EMIZB_151[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="EMIZB-151", .vendor="Frient",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_EMIZB_151, .from_zigbee_count=sizeof(kFz_EMIZB_151)/sizeof(kFz_EMIZB_151[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::frient
