// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Smarli S-ZB-1RE1-R251 — 2ch relay + electricity meter.
// Zigbee 2ch smart relay
// z2m-source: smarli.ts #S-ZB-1RE1-R251 — m.onOff(ep 1/2) +
//             m.electricityMeter({endpointNames:["3"]}).
//
// Gap fixed: m.electricityMeter() defaults to cluster:"both" — seMetering
// 0x0702 (energy) PLUS haElectricalMeasurement 0x0B04 (power/voltage/
// current). The auto-port wired only kFzMetering (0x0702) and dropped the
// 0x0B04 half (current/voltage absent; "power" undecoded — in the "both"
// path power comes from haElectricalMeasurement). The meter lives on
// endpoint 3, so its bindings are on ep3; dispatch suffixes the runtime
// metering keys to <key>_3 via the endpoint_map (exposes stay bare).
// Add kFzElectricalMeasurement + current/voltage exposes + 0x0B04 binding.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::smarli {
namespace {
const FzConverter* const kFz_S_ZB_1RE1_R251[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzElectricalMeasurement,
    &::zhc::generic::kFzMetering,
};
const TzConverter* const kTz_S_ZB_1RE1_R251[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_S_ZB_1RE1_R251[] = { "S-ZB-1RE1-R251" };

constexpr ::zhc::EndpointLabel kEndpoints_S_ZB_1RE1_R251[] = { {"1", 1}, {"2", 2}, {"3", 3} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {3, 0x0B04},
    {3, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_S_ZB_1RE1_R251{
    .zigbee_models=kModels_S_ZB_1RE1_R251, .zigbee_models_count=sizeof(kModels_S_ZB_1RE1_R251)/sizeof(kModels_S_ZB_1RE1_R251[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="S-ZB-1RE1-R251", .vendor="Smarli",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_S_ZB_1RE1_R251, .from_zigbee_count=sizeof(kFz_S_ZB_1RE1_R251)/sizeof(kFz_S_ZB_1RE1_R251[0]),
    .to_zigbee=kTz_S_ZB_1RE1_R251, .to_zigbee_count=sizeof(kTz_S_ZB_1RE1_R251)/sizeof(kTz_S_ZB_1RE1_R251[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_S_ZB_1RE1_R251,
    .endpoint_map_count = sizeof(kEndpoints_S_ZB_1RE1_R251)/sizeof(kEndpoints_S_ZB_1RE1_R251[0]),
};

}  // namespace zhc::devices::smarli
