// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Smarli S-ZB-COV1-R251 — curtain (lift+tilt) + electricity meter.
// Zigbee curtain control module
// z2m-source: smarli.ts #S-ZB-COV1-R251 —
//   m.windowCovering({controls:["lift","tilt"], coverInverted:true}) +
//   m.electricityMeter({endpointNames:["3"]}).
//
// Gaps fixed:
//  (1) windowCovering declares BOTH lift and tilt controls — exposes
//      position AND tilt, decoded via fz.cover_position_tilt (attr 0x0008
//      lift + 0x0009 tilt). The auto-port wired only kFzCoverPosition and
//      dropped the tilt channel: add kFzCoverTilt + kTzCoverPositionTilt +
//      "tilt" expose.
//  (2) m.electricityMeter() defaults to cluster:"both" — seMetering 0x0702
//      (energy) PLUS haElectricalMeasurement 0x0B04 (power/voltage/current).
//      The auto-port wired only kFzMetering (0x0702); add
//      kFzElectricalMeasurement + current/voltage exposes + 0x0B04 binding.
//      The meter lives on endpoint 3 (cover on ep1); the endpoint_map {3}
//      suffixes meter runtime keys to <key>_3 while cover keys stay bare.
//      curtain_type enum (manuSpecific attr 0x1000) + sunricher.motorControl
//      remain INFRA (no generic converter) — deferred.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::smarli {
namespace {
const FzConverter* const kFz_S_ZB_COV1_R251[] = {
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
    &::zhc::generic::kFzElectricalMeasurement,
    &::zhc::generic::kFzMetering,
};
const TzConverter* const kTz_S_ZB_COV1_R251[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_S_ZB_COV1_R251[] = { "S-ZB-COV1-R251" };

constexpr ::zhc::EndpointLabel kEndpoints_S_ZB_COV1_R251[] = { {"3", 3} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0102},
    {3, 0x0B04},
    {3, 0x0702},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_S_ZB_COV1_R251{
    .zigbee_models=kModels_S_ZB_COV1_R251, .zigbee_models_count=sizeof(kModels_S_ZB_COV1_R251)/sizeof(kModels_S_ZB_COV1_R251[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="S-ZB-COV1-R251", .vendor="Smarli",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_S_ZB_COV1_R251, .from_zigbee_count=sizeof(kFz_S_ZB_COV1_R251)/sizeof(kFz_S_ZB_COV1_R251[0]),
    .to_zigbee=kTz_S_ZB_COV1_R251, .to_zigbee_count=sizeof(kTz_S_ZB_COV1_R251)/sizeof(kTz_S_ZB_COV1_R251[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_S_ZB_COV1_R251,
    .endpoint_map_count = sizeof(kEndpoints_S_ZB_COV1_R251)/sizeof(kEndpoints_S_ZB_COV1_R251[0]),
};

}  // namespace zhc::devices::smarli
