// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit SZT211_AW-P1 — hand-curated (was missing tilt).
// Curtain Motor. z2m m.windowCovering({controls:["lift","tilt"]}) exposes
// both position AND tilt, but the auto-port wired only kFzCoverPosition /
// kTzCoverPosition (lift), dropping the tilt channel
// (currentPositionTiltPercentage 0x0009). Added kFzCoverTilt decoder +
// kTzCoverPositionTilt encoder + a `tilt` expose.
// z2m-source: feibit.ts #SZT211_AW-P1.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_SZT211_AW_P1[] = {
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
};
const TzConverter* const kTz_SZT211_AW_P1[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_SZT211_AW_P1[] = { "FEB56-ZT21AAK1.6" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0102},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SZT211_AW_P1{
    .zigbee_models=kModels_SZT211_AW_P1, .zigbee_models_count=sizeof(kModels_SZT211_AW_P1)/sizeof(kModels_SZT211_AW_P1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SZT211_AW-P1", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SZT211_AW_P1, .from_zigbee_count=sizeof(kFz_SZT211_AW_P1)/sizeof(kFz_SZT211_AW_P1[0]),
    .to_zigbee=kTz_SZT211_AW_P1, .to_zigbee_count=sizeof(kTz_SZT211_AW_P1)/sizeof(kTz_SZT211_AW_P1[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::feibit
