// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit NZSN421W-Q — hand-curated (was wrong-bundle).
// Four-Gang Battery-Powered Scene Switch. z2m role:
//   m.deviceEndpoints({endpoints:{"1":1,"2":2,"3":3,"4":4}}) + m.battery()
//   + m.commandsOnOff({endpointNames:["1","2","3","4"]})
// i.e. each gang (EP1..4) emits genOnOff commands surfaced as `action`, plus
// genPowerCfg battery; toZigbee is empty (uncontrollable). The auto-port
// collapsed it into a single settable on/off `state` (kFzOnOff + kTzOnOff),
// a dead control. Replaced with kFzCommandOn/Off/Toggle + kFzBattery, an
// `action` enum + endpoint_action_suffix (action_1..action_4), and dropped
// the bogus to_zigbee.
// z2m-source: feibit.ts #NZSN421W-Q.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_NZSN421W_Q[] = {
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandToggle,
    &::zhc::generic::kFzBattery,
};
constexpr const char* kModels_NZSN421W_Q[] = { "FNB56-ZSN21YM1.0" };

constexpr ::zhc::EndpointLabel kEndpoints_NZSN421W_Q[] = { {"1", 1}, {"2", 2}, {"3", 3}, {"4", 4} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006}, {2, 0x0006}, {3, 0x0006}, {4, 0x0006},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_NZSN421W_Q{
    .zigbee_models=kModels_NZSN421W_Q, .zigbee_models_count=sizeof(kModels_NZSN421W_Q)/sizeof(kModels_NZSN421W_Q[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="NZSN421W-Q", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_NZSN421W_Q, .from_zigbee_count=sizeof(kFz_NZSN421W_Q)/sizeof(kFz_NZSN421W_Q[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_NZSN421W_Q,
    .endpoint_map_count = sizeof(kEndpoints_NZSN421W_Q)/sizeof(kEndpoints_NZSN421W_Q[0]),
    .endpoint_action_suffix=true,
};

}  // namespace zhc::devices::feibit
