// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit SSS401ZB — hand-curated (was missing action).
// Smart 4 key scene wall switch. z2m role:
//   fromZigbee:[fz.command_recall], toZigbee:[tz.on_off],
//   exposes:[e.action(["recall_*"]), e.switch()]
// i.e. it is BOTH a controllable on/off switch AND emits genScenes Recall
// (cmd 0x05) commands surfaced as `action` = recall_<scene>. The auto-port
// kept the switch half (kFzOnOff + kTzOnOff + `state`) but dropped the
// command_recall decoder, so the scene buttons never produced an action.
// Added kFzCommandRecall + an `action` enum + the genScenes (0x0005) bind;
// the switch half is preserved as a regression guard.
// z2m-source: feibit.ts #SSS401ZB.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_SSS401ZB[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzCommandRecall,
};
const TzConverter* const kTz_SSS401ZB[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_SSS401ZB[] = { "FB56+ZSN08KJ2.2" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0005},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SSS401ZB{
    .zigbee_models=kModels_SSS401ZB, .zigbee_models_count=sizeof(kModels_SSS401ZB)/sizeof(kModels_SSS401ZB[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SSS401ZB", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SSS401ZB, .from_zigbee_count=sizeof(kFz_SSS401ZB)/sizeof(kFz_SSS401ZB[0]),
    .to_zigbee=kTz_SSS401ZB, .to_zigbee_count=sizeof(kTz_SSS401ZB)/sizeof(kTz_SSS401ZB[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::feibit
