// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit SEB01ZB — hand-curated (was IAS dead-key).
// z2m fz.ias_sos_alarm_2 (zoneStatus bit 1) -> semantic key `sos`;
// generic kFzIasZone read bit 0 + bare "alarm". Swapped to kFzIasSosAlarm2.
// SOS button
// z2m-source: feibit.ts #SEB01ZB.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_SEB01ZB[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasSosAlarm2,
};

constexpr const char* kModels_SEB01ZB[] = { "FNB56-SOS03FB1.5" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"sos", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SEB01ZB{
    .zigbee_models=kModels_SEB01ZB, .zigbee_models_count=sizeof(kModels_SEB01ZB)/sizeof(kModels_SEB01ZB[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SEB01ZB", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SEB01ZB, .from_zigbee_count=sizeof(kFz_SEB01ZB)/sizeof(kFz_SEB01ZB[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::feibit
