// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit SZSN325W-Q — hand-curated (was wrong-bundle).
// Three-Gang Scene Switch. z2m role is action-only:
//   fromZigbee:[fz.command_recall], toZigbee:[], exposes:[e.action(["recall_*"])]
// i.e. the device emits genScenes Recall (cmd 0x05) commands, surfaced as
// `action` = recall_<scene>. The auto-port mis-modelled it as a controllable
// on/off switch (kFzOnOff + kTzOnOff + settable `state`), which is a dead
// control — the device cannot be switched. Replaced with kFzCommandRecall +
// an `action` enum, dropped the bogus to_zigbee, and bound genScenes (0x0005).
// z2m-source: feibit.ts #SZSN325W-Q.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_SZSN325W_Q[] = {
    &::zhc::generic::kFzCommandRecall,
};
constexpr const char* kModels_SZSN325W_Q[] = { "FEB56-ZSN25YS1.3" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0005},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SZSN325W_Q{
    .zigbee_models=kModels_SZSN325W_Q, .zigbee_models_count=sizeof(kModels_SZSN325W_Q)/sizeof(kModels_SZSN325W_Q[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SZSN325W-Q", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SZSN325W_Q, .from_zigbee_count=sizeof(kFz_SZSN325W_Q)/sizeof(kFz_SZSN325W_Q[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::feibit
