// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Feibit TCUR218W-V1 — hand-curated (was missing tilt + wrong EPs).
// Dual Track Curtain Panel. z2m wires
//   m.deviceEndpoints({endpoints:{top:15, bottom:14}})
//   + m.windowCovering({controls:["lift","tilt"], endpointNames:["top","bottom"]})
// so each track exposes position AND tilt on endpoints 15/14. The auto-port
// dropped the tilt channel (kFzCoverTilt / kTzCoverPositionTilt) and used
// the wrong endpoint IDs {top:1, bottom:2}, so per-track binds + key
// suffixing landed on the wrong endpoints. Restored EPs {15,14} and added
// the tilt decode/encode.
// z2m-source: feibit.ts #TCUR218W-V1.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::feibit {
namespace {
const FzConverter* const kFz_TCUR218W_V1[] = {
    &::zhc::generic::kFzCoverPosition,
    &::zhc::generic::kFzCoverTilt,
};
const TzConverter* const kTz_TCUR218W_V1[] = {
    &::zhc::generic::kTzCoverPosition,
    &::zhc::generic::kTzCoverPositionTilt,
};
constexpr const char* kModels_TCUR218W_V1[] = { "FB56+CUR18SB2.0" };

constexpr ::zhc::EndpointLabel kEndpoints_TCUR218W_V1[] = { {"top", 15}, {"bottom", 14} };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"tilt", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {15, 0x0102},
    {14, 0x0102},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_TCUR218W_V1{
    .zigbee_models=kModels_TCUR218W_V1, .zigbee_models_count=sizeof(kModels_TCUR218W_V1)/sizeof(kModels_TCUR218W_V1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="TCUR218W-V1", .vendor="Feibit",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_TCUR218W_V1, .from_zigbee_count=sizeof(kFz_TCUR218W_V1)/sizeof(kFz_TCUR218W_V1[0]),
    .to_zigbee=kTz_TCUR218W_V1, .to_zigbee_count=sizeof(kTz_TCUR218W_V1)/sizeof(kTz_TCUR218W_V1[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .endpoint_map       = kEndpoints_TCUR218W_V1,
    .endpoint_map_count = sizeof(kEndpoints_TCUR218W_V1)/sizeof(kEndpoints_TCUR218W_V1[0]),
};

}  // namespace zhc::devices::feibit
