// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Nexelec Open'R — graduated from generated/.
// Open'R CO2, Temperature and Humidity sensor.
//
// z2m extend = [m.temperature(), m.humidity(), m.co2(), m.battery(),
// m.identify()] → msTemperatureMeasurement (0x0402) /100,
// msRelativeHumidity (0x0405) /100, msCO2 (0x040D) ppm, genPowerCfg
// (0x0001) battery. The auto-port wired ONLY kFzBattery, so temperature,
// humidity and CO2 were dead. Re-wire the three dropped sensor channels.
//
// z2m-source: nexelec.ts #Open'R.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::nexelec {
namespace {
const FzConverter* const kFz_Open_R[] = {
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzHumidity,
    &::zhc::generic::kFzCO2,
    &::zhc::generic::kFzBattery,
};

constexpr const char* kModels_Open_R[] = { "Air Quality Sensor Nexelec" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py (exposes/bindings
//     extended for the re-wired temperature/humidity/co2 channels) ---
constexpr Expose kAutoExposes[] = {
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"co2", ExposeType::Numeric, Access::State, "ppm", nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0402},  // msTemperatureMeasurement
    {1, 0x0405},  // msRelativeHumidity
    {1, 0x040D},  // msCO2
    {1, 0x0001},  // genPowerCfg
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_Open_R{
    .zigbee_models=kModels_Open_R, .zigbee_models_count=sizeof(kModels_Open_R)/sizeof(kModels_Open_R[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="Open'R", .vendor="Nexelec",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_Open_R, .from_zigbee_count=sizeof(kFz_Open_R)/sizeof(kFz_Open_R[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::nexelec
