// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Xal 050-1212558H — graduated from generated/.
// Opal floodlight for Just MOVE IT 25 track
// z2m-source: xal.ts #050-1212558H (m.light(), no color/colorTemp args).
//
// z2m's bare m.light() exposes state + brightness + power_on_behavior
// (e.power_on_behavior(["off","on","toggle","previous"]) backed by
// fz/tz.power_on_behavior on genOnOff attr 0x4003 startUpOnOff). The
// auto-port dropped that decodable channel; restored via the generic
// kFz/kTzPowerOnBehavior1 pair. No color/colorTemp axis exists — bare
// m.light() omits both (the dimmable-only luminaire is NOT RGBW/CCT).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::xal {
namespace {
const FzConverter* const kFz_D050_1212558H[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzPowerOnBehavior1,
};
const TzConverter* const kTz_D050_1212558H[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_D050_1212558H[] = { "050-1212558H" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D050_1212558H{
    .zigbee_models=kModels_D050_1212558H, .zigbee_models_count=sizeof(kModels_D050_1212558H)/sizeof(kModels_D050_1212558H[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="050-1212558H", .vendor="Xal",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D050_1212558H, .from_zigbee_count=sizeof(kFz_D050_1212558H)/sizeof(kFz_D050_1212558H[0]),
    .to_zigbee=kTz_D050_1212558H, .to_zigbee_count=sizeof(kTz_D050_1212558H)/sizeof(kTz_D050_1212558H[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::xal
