// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Xenon Smart X7726 — Tuya TS0601 / _TZE284_hbjwgkdh curtain motor.
// Parity pass: this device is a Tuya-MCU (0xEF00) DP device; the sibling
// generated stub Xen_X7726.cpp misrouted the same fingerprint to
// genWindowCovering (0x0102) — a dead route since the firmware only emits DPs —
// and dropped state/calibration/temperature. That stub was removed; this def is
// the single correct port, renamed to the z2m identity (X7726 / Xenon Smart),
// with the phantom `action` expose dropped and exposes typed to match z2m
// (state/calibration as enums, position/temperature as numerics).
// z2m-source: devices/xenon.ts #X7726 (TS0601 / _TZE284_hbjwgkdh).
#include "definitions/tuya/_shared.hpp"
#include "definitions/tuya/extend.hpp"
namespace zhc::devices::xenon {
namespace {

constexpr ::zhc::tuya::TuyaEnumEntry kEnum__TZE284_hbjwgkdh_state_dp1[] = {
    { 0, "OPEN" },
    { 1, "STOP" },
    { 2, "CLOSE" },
};

constexpr ::zhc::tuya::TuyaEnumEntry kEnum__TZE284_hbjwgkdh_calibration_dp102[] = {
    { 0, "start" },
    { 1, "finish" },
};

constexpr ::zhc::tuya::TuyaDpMapEntry kEntries__TZE284_hbjwgkdh[] = {
    { 1, "state", ::zhc::TuyaDpType::Enum, 1, kEnum__TZE284_hbjwgkdh_state_dp1, sizeof(kEnum__TZE284_hbjwgkdh_state_dp1)/sizeof(kEnum__TZE284_hbjwgkdh_state_dp1[0]) },
    { 2, "position", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 3, "position", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
    { 102, "calibration", ::zhc::TuyaDpType::Enum, 1, kEnum__TZE284_hbjwgkdh_calibration_dp102, sizeof(kEnum__TZE284_hbjwgkdh_calibration_dp102)/sizeof(kEnum__TZE284_hbjwgkdh_calibration_dp102[0]) },
    { 103, "temperature", ::zhc::TuyaDpType::Numeric, 1, nullptr, 0, 0 },
};
constexpr ::zhc::tuya::TuyaDatapointMap kMap__TZE284_hbjwgkdh{ kEntries__TZE284_hbjwgkdh, 5 };
constexpr FzConverter kFzDp__TZE284_hbjwgkdh{
    .family            = FrameFamily::TuyaDp,
    .cluster           = "manuSpecificTuya",
    .type_mask         = type_bit(MessageType::Command),
    .command_id        = WILDCARD_CMD_ID,
    .attr_id           = WILDCARD_ATTR_ID,
    .endpoint          = WILDCARD_ENDPOINT,
    .frame_flags_mask  = 0,
    .frame_flags_value = 0,
    .direction         = Direction::ServerToClient,
    .fn                = { .tuya_fn = &::zhc::tuya::fz_tuya_datapoints },
    .user_config       = &kMap__TZE284_hbjwgkdh,
};
const FzConverter* const kFz__TZE284_hbjwgkdh[] = {
    &::zhc::tuya::kFzTuyaMcuSyncTime,
    &kFzDp__TZE284_hbjwgkdh,
};
constexpr TzConverter kTzDp__TZE284_hbjwgkdh{
    .key         = nullptr,                // wildcard — claims any mapped key
    .cluster     = "manuSpecificTuya",
    .cluster_id  = 0xEF00,
    .command_id  = 0x00,
    .fn          = &::zhc::tuya::tz_tuya_datapoints,
    .user_config = &kMap__TZE284_hbjwgkdh,
};
const TzConverter* const kTz__TZE284_hbjwgkdh[] = { &kTzDp__TZE284_hbjwgkdh };
constexpr const char* kM__TZE284_hbjwgkdh[] = { "TS0601" };
constexpr const char* kN__TZE284_hbjwgkdh[] = { "_TZE284_hbjwgkdh" };
}  // namespace

// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    // z2m cover_position(position STATE_SET) + state enum {OPEN/STOP/CLOSE}.
    {"state", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"position", ExposeType::Numeric, Access::StateSet, "%", nullptr, nullptr, 0},
    {"calibration", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0xEF00},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefXen__TZE284_hbjwgkdh{
    .zigbee_models=kM__TZE284_hbjwgkdh,.zigbee_models_count=sizeof(kM__TZE284_hbjwgkdh)/sizeof(kM__TZE284_hbjwgkdh[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kN__TZE284_hbjwgkdh,.manufacturer_names_count=1,
    .model="X7726",.vendor="Xenon Smart",
    .meta=nullptr,.exposes=kAutoExposes,.exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr,.white_labels_count=0,
    .from_zigbee=kFz__TZE284_hbjwgkdh,
    .from_zigbee_count=sizeof(kFz__TZE284_hbjwgkdh)/sizeof(kFz__TZE284_hbjwgkdh[0]),
    .to_zigbee=kTz__TZE284_hbjwgkdh,
    .to_zigbee_count=sizeof(kTz__TZE284_hbjwgkdh)/sizeof(kTz__TZE284_hbjwgkdh[0]),
    .configure=::zhc::tuya::extend::tuya_base_configure(),
    .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};
}  // namespace zhc::devices::xenon
