// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Prolight 5412748727388 — remote re-mapped to action stream.
// Remote control
// z2m-source: prolight.ts #5412748727388 —
//   toZigbee: []   (action-only, NOT a controllable on/off switch)
//   fromZigbee: [command_on, command_off, command_move_to_level,
//                command_move, command_stop, command_move_to_color_temp,
//                command_move_to_color, command_move_color_temperature,
//                battery]
//   exposes: action([...]) + battery()
// The auto-port mis-ported this remote as a controllable on/off switch
// (kFzOnOff + kTzOnOff + a `state` expose) — the `state` never updated
// (a remote is the *client* of genOnOff) and the action stream was dead.
// Wired the generic Client→Server command converters + an `action` enum;
// dropped the phantom on/off state and the to_zigbee setter.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::prolight {
namespace {
const FzConverter* const kFz_D5412748727388[] = {
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandMoveToLevel,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
    &::zhc::generic::kFzCommandMoveToColorTemp,
    &::zhc::generic::kFzCommandMoveToColor,
    &::zhc::generic::kFzCommandMoveColorTemperature,
    &::zhc::generic::kFzBattery,
};
constexpr const char* kModels_D5412748727388[] = { "PROLIGHT REMOTE CONTROL" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
// z2m: action(...) + battery() — battery-powered ZLL transmitter.
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D5412748727388{
    .zigbee_models=kModels_D5412748727388, .zigbee_models_count=sizeof(kModels_D5412748727388)/sizeof(kModels_D5412748727388[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="5412748727388", .vendor="Prolight",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D5412748727388, .from_zigbee_count=sizeof(kFz_D5412748727388)/sizeof(kFz_D5412748727388[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::prolight
