// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Aldi 141L100RC — hand-curated (was wrong-bundle).
// MEGOS switch and dimming light remote control. z2m role:
//   exposes: e.action([on, off, brightness_stop, brightness_step_up/down,
//                       brightness_move_up/down])
//   fromZigbee: command_on, command_off, command_step, command_move,
//               command_stop  (genOnOff + genLevelCtrl COMMANDS -> action)
//   toZigbee: []  (uncontrollable — it is a remote, not a controllable load)
// The auto-port mis-modelled it as a settable on/off `state` (kFzOnOff +
// kTzOnOff), a dead control whose button presses produced no `action`.
// Replaced with the command decoder set (On/Off + Move/Step/Stop) + an
// `action` enum, and dropped the bogus to_zigbee. No toggle and no battery
// (z2m wires neither). Single endpoint -> no endpoint_map.
// z2m-source: aldi.ts #141L100RC.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::aldi {
namespace {
const FzConverter* const kFz_D141L100RC[] = {
    &::zhc::generic::kFzCommandOn,
    &::zhc::generic::kFzCommandOff,
    &::zhc::generic::kFzCommandStep,
    &::zhc::generic::kFzCommandMove,
    &::zhc::generic::kFzCommandStop,
};
constexpr const char* kModels_D141L100RC[] = { "TS1001" };
constexpr const char* kManus_D141L100RC[] = { "_TZ3000_ztrfrcsu" };
}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_D141L100RC{
    .zigbee_models=kModels_D141L100RC, .zigbee_models_count=sizeof(kModels_D141L100RC)/sizeof(kModels_D141L100RC[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=kManus_D141L100RC, .manufacturer_names_count=sizeof(kManus_D141L100RC)/sizeof(kManus_D141L100RC[0]),
    .model="141L100RC", .vendor="Aldi",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_D141L100RC, .from_zigbee_count=sizeof(kFz_D141L100RC)/sizeof(kFz_D141L100RC[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::aldi
