// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Develco SMSZB-120 smoke detector — graduated from generated.
// Smoke detector with siren.
//
// Parity fix: generic kFzIasZone emits the bare key "alarm", but z2m's
// fz.ias_smoke_alarm_1_develco publishes "smoke" (zoneStatus bit 0).
// Swap in the typed kFzIasSmokeAlarm (smoke + tamper + battery_low) and
// add the msTemperatureMeasurement channel z2m wires via
// develcoModernExtend.temperature(). kTzWarning (IAS WD) kept.
//
// z2m v26.114.0 / v26.115.0 ("fix temperature"): the device accepts only
// four bindings, so z2m binds just genBinaryInput on the IAS endpoint 35 and
// lets battery (35) and temperature (38) bind through their extends; it adds
// develcoModernExtend.faultStatus (reliability / fault, reported) and
// max_duration 0..600. Bindings here were on endpoint 1, which this device
// does not have, so none of them took. Not ported: zoneStatus reporting
// (v26.115.2 removed it again) and the supervision / restore / test zone bits.
//
// z2m-source: develco.ts #SMSZB-120 — fz.ias_smoke_alarm_1_develco +
//             develcoModernExtend.temperature().
#include "definitions/_generic/_shared.hpp"
#include "definitions/develco/_shared.hpp"

namespace zhc::devices::develco {
namespace {
const FzConverter* const kFz_SMSZB_120[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasSmokeAlarm,
    &::zhc::generic::kFzTemperature,
    &::zhc::develco::kFzDevelcoFaultStatus,
    &::zhc::generic::kFzIasWdMaxDuration,
};
const TzConverter* const kTz_SMSZB_120[] = {
    &::zhc::generic::kTzWarning,
    &::zhc::generic::kTzIasWdMaxDuration,
};
constexpr const char* kReliability[] = { "no_fault_detected", "unreliable_other", "process_error" };
constexpr std::uint8_t kReadZone[] = { 0x10, 0x00, 0x00, 0x00, 0x11, 0x00 };   // iasCieAddr, zoneState, zoneId
constexpr std::uint8_t kReadFault[] = { 0x67, 0x00, 0x6F, 0x00 };              // reliability, statusFlags
constexpr std::uint8_t kReadMaxDuration[] = { 0x00, 0x00 };
constexpr ConfigStep kSteps[] = {
    { ConfigStepOp::Read, 35, 0x0500, 0x00, 0, kReadZone, sizeof(kReadZone), 0 },
    { ConfigStepOp::Read, 35, 0x000F, 0x00, 0, kReadFault, sizeof(kReadFault), 0 },
    { ConfigStepOp::Read, 35, 0x0502, 0x00, 0, kReadMaxDuration, sizeof(kReadMaxDuration), 0 },
};
constexpr const char* kModels_SMSZB_120[] = { "SMSZB-120", "GWA1512_SmokeSensor" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"smoke", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"reliability", ExposeType::Enum, Access::State, nullptr, "Indicates reason if any fault", kReliability, 3},
    {"fault", ExposeType::Binary, Access::State, nullptr, "Indicates whether the device are in fault state", nullptr, 0},
    {"max_duration", ExposeType::Numeric, Access::StateSet, "s", "Max duration in seconds of the alarm", nullptr, 0,
     ExposeCategory::State, 0, 600, 1},
};

// Four bindings at most on this device: genBinaryInput (35), genPowerCfg
// (35), msTemperatureMeasurement (38).
constexpr BindingSpec kAutoBindings[] = {
    {35, 0x000F},
    {35, 0x0001},
    {38, 0x0402},
};
constexpr ReportingSpec kReports[] = {
    {35, 0x000F, 0x0067, 0x30, 0, 65000, 0, 0},    // reliability
    {35, 0x000F, 0x006F, 0x18, 0, 65000, 0, 0},    // statusFlags
    {35, 0x0001, 0x0020, 0x20, 3600, 65000, 10, 0}, // batteryVoltage
    {38, 0x0402, 0x0000, 0x29, 10, 3600, 100, 0},   // temperature
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_SMSZB_120[] = {
    {"Frient","94430"},
    {"Cavius","2103"},
};
extern const PreparedDefinition kDef_SMSZB_120{
    .zigbee_models=kModels_SMSZB_120, .zigbee_models_count=sizeof(kModels_SMSZB_120)/sizeof(kModels_SMSZB_120[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SMSZB-120", .vendor="Develco",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_SMSZB_120, .white_labels_count=sizeof(kWhiteLabels_SMSZB_120)/sizeof(kWhiteLabels_SMSZB_120[0]),
    .from_zigbee=kFz_SMSZB_120, .from_zigbee_count=sizeof(kFz_SMSZB_120)/sizeof(kFz_SMSZB_120[0]),
    .to_zigbee=kTz_SMSZB_120, .to_zigbee_count=sizeof(kTz_SMSZB_120)/sizeof(kTz_SMSZB_120[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .reports=kReports, .reports_count=sizeof(kReports)/sizeof(kReports[0]),
    .config_steps=kSteps, .config_steps_count=sizeof(kSteps)/sizeof(kSteps[0]),
};

}  // namespace zhc::devices::develco
