// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Develco HMSZB-120 temp/humidity sensor — graduated from generated.
// Temperature & humidity sensor.
//
// Parity fix: the generated def wired ONLY kFzBattery, so the two primary
// channels (temperature, humidity) were dead. z2m exposes temperature +
// humidity + battery. Wire the generic msTemperatureMeasurement (0x0402)
// and msRelativeHumidity (0x0405) decoders.
//
// z2m-source: develco.ts #HMSZB-120/-110 — develcoModernExtend.temperature
//             + m.humidity + m.battery.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::develco {
namespace {
const FzConverter* const kFz_HMSZB_120[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzTemperature,
    &::zhc::generic::kFzHumidity,
};

constexpr const char* kModels_HMSZB_120[] = { "HMSZB-110", "HMSZB-120" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0405},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_HMSZB_120[] = {
    {"Frient","HMSZB-120"},
};
extern const PreparedDefinition kDef_HMSZB_120{
    .zigbee_models=kModels_HMSZB_120, .zigbee_models_count=sizeof(kModels_HMSZB_120)/sizeof(kModels_HMSZB_120[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="HMSZB-120", .vendor="Develco",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_HMSZB_120, .white_labels_count=sizeof(kWhiteLabels_HMSZB_120)/sizeof(kWhiteLabels_HMSZB_120[0]),
    .from_zigbee=kFz_HMSZB_120, .from_zigbee_count=sizeof(kFz_HMSZB_120)/sizeof(kFz_HMSZB_120[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::develco
