// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Develco SPLZB-141 smart plug, graduated from the generated copy.
// z2m v26.111.0 (#13224, continuous acFrequency reporting; refactor to
// m.electricityMeter / m.onOff, z2m issue #29548): the plug
// works on endpoint 2 — genOnOff on endpoint 1 fails to set up — so binding
// and reporting go to endpoint 2. The generated copy bound endpoint 1.
// Power plug
// z2m-source: develco.ts #SPLZB-141.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::develco {
namespace {
const FzConverter* const kFz_SPLZB_141[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
    &::zhc::generic::kFzElectricalMeasurement,
};
const TzConverter* const kTz_SPLZB_141[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_SPLZB_141[] = { "SPLZB-141" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {2, 0x0006},
    {2, 0x0702},
    {2, 0x0B04},
};
constexpr ReportingSpec kReports[] = {
    {2, 0x0006, 0x0000, 0x10, 0, 3600, 0, 0},     // onOff
    {2, 0x0B04, 0x050B, 0x29, 5, 3600, 1, 0},     // activePower
    {2, 0x0B04, 0x0508, 0x21, 5, 3600, 1, 0},     // rmsCurrent
    {2, 0x0B04, 0x0505, 0x21, 5, 3600, 1, 0},     // rmsVoltage
    {2, 0x0702, 0x0000, 0x25, 5, 3600, 257, 0},   // currentSummDelivered
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefDevelco_SPLZB_141{
    .zigbee_models=kModels_SPLZB_141, .zigbee_models_count=sizeof(kModels_SPLZB_141)/sizeof(kModels_SPLZB_141[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SPLZB-141", .vendor="Develco",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SPLZB_141, .from_zigbee_count=sizeof(kFz_SPLZB_141)/sizeof(kFz_SPLZB_141[0]),
    .to_zigbee=kTz_SPLZB_141, .to_zigbee_count=sizeof(kTz_SPLZB_141)/sizeof(kTz_SPLZB_141[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
    .reports=kReports, .reports_count=sizeof(kReports)/sizeof(kReports[0]),
};

}  // namespace zhc::devices::develco
