// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Develco HESZB-120 heat/fire detector — graduated from generated.
// Fire detector with siren.
//
// Parity fix: generic kFzIasZone emits the bare key "alarm", but z2m's
// fz.ias_smoke_alarm_1_develco publishes "smoke" (zoneStatus bit 0) —
// Develco routes this heat alarm through the smoke decoder. Swap in the
// typed kFzIasSmokeAlarm (smoke + tamper + battery_low) and add the
// msTemperatureMeasurement channel z2m wires via
// develcoModernExtend.temperature(). kTzWarning (IAS WD) kept.
//
// z2m-source: develco.ts #HESZB-120 — fz.ias_smoke_alarm_1_develco +
//             develcoModernExtend.temperature().
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::develco {
namespace {
const FzConverter* const kFz_HESZB_120[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasSmokeAlarm,
    &::zhc::generic::kFzTemperature,
};
const TzConverter* const kTz_HESZB_120[] = {
    &::zhc::generic::kTzWarning,
};
constexpr const char* kModels_HESZB_120[] = { "HESZB-120" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"smoke", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0500},
};
// --- end auto-generated block ---


constexpr WhiteLabel kWhiteLabels_HESZB_120[] = {
    {"Frient","94431"},
};
extern const PreparedDefinition kDef_HESZB_120{
    .zigbee_models=kModels_HESZB_120, .zigbee_models_count=sizeof(kModels_HESZB_120)/sizeof(kModels_HESZB_120[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="HESZB-120", .vendor="Develco",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=kWhiteLabels_HESZB_120, .white_labels_count=sizeof(kWhiteLabels_HESZB_120)/sizeof(kWhiteLabels_HESZB_120[0]),
    .from_zigbee=kFz_HESZB_120, .from_zigbee_count=sizeof(kFz_HESZB_120)/sizeof(kFz_HESZB_120[0]),
    .to_zigbee=kTz_HESZB_120, .to_zigbee_count=sizeof(kTz_HESZB_120)/sizeof(kTz_HESZB_120[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::develco
