// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Develco SBTZB-110 smart button — graduated from generated.
// Smart button.
//
// Parity fix: this is a BUTTON, not a switch. z2m wires fz.ewelink_action
// (genOnOff command codes repurposed as click types → action="single")
// with NO toZigbee; it exposes action(["single"]). The generated def
// instead lowered kFzOnOff + kTzOnOff and exposed a controllable on/off
// "state", which never matched a real channel. Swap in kFzEwelinkAction,
// drop the on/off TZ, and expose "action".
//
// z2m-source: develco.ts #SBTZB-110 — fz.ewelink_action + e.action.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::develco {
namespace {
const FzConverter* const kFz_SBTZB_110[] = {
    &::zhc::generic::kFzEwelinkAction,
    &::zhc::generic::kFzBattery,
};
constexpr const char* kModels_SBTZB_110[] = { "SBTZB-110" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"action", ExposeType::Enum, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0001},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_SBTZB_110{
    .zigbee_models=kModels_SBTZB_110, .zigbee_models_count=sizeof(kModels_SBTZB_110)/sizeof(kModels_SBTZB_110[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="SBTZB-110", .vendor="Develco",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_SBTZB_110, .from_zigbee_count=sizeof(kFz_SBTZB_110)/sizeof(kFz_SBTZB_110[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::develco
