// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Micromatic ZB250 — electricityMeter 0x0B04 half + power_on_behavior restored.
// Zigbee dimmer for LED.
// z2m-source: micromatic.ts #ZB250 = m.light({configureReporting:true}) + m.electricityMeter().
//
// REAL GAP 1 — metering 0x0B04 half dropped. z2m m.electricityMeter() defaults
// cluster:"both" + electricalMeasurementType:"ac" (modernExtend.ts
// electricityMeter() lines 2392-2406 → genericMeter cluster "both"). That wires
// BOTH fz.metering (seMetering 0x0702) AND fz.electrical_measurement
// (haElectricalMeasurement 0x0B04), and exposes power/voltage/current/energy
// (lines 2214-2236). Crucially power/voltage/current come from 0x0B04 (the AC
// RMS attrs); only energy comes from 0x0702. The Tier-1 auto-port wired only
// kFzMetering (0x0702), dropping the entire 0x0B04 half → no voltage, no current,
// and power only via the 0x0702 InstantaneousDemand fallback. Restored
// kFzElectricalMeasurement + the voltage/current exposes + the 0x0B04 binding.
//
// REAL GAP 2 — power_on_behavior axis dropped. m.light() defaults
// powerOnBehavior=true (modernExtend.ts light() lines 1179-1180), wiring
// fz.power_on_behavior (genOnOff 0x4003 startUpOnOff enum8) + tz.power_on_behavior
// + the enum expose. Restored via kFzPowerOnBehavior / kTzPowerOnBehavior1.
//
// FALSE suspect — color/colorTemp. m.light() is called with neither a color nor
// a colorTemp arg, so the lightingColorCtrl 0x0300 axis is NOT added
// (light() lines 1190-1252 gate the colour fz/tz/exposes on those args). No
// color_temp / color_x / color_y / hue axis exists — asserted absent in the test.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::micromatic {
namespace {
const FzConverter* const kFz_ZB250[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzBrightness,
    &::zhc::generic::kFzPowerOnBehavior,
    &::zhc::generic::kFzMetering,              // seMetering 0x0702 → energy
    &::zhc::generic::kFzElectricalMeasurement, // haElectricalMeasurement 0x0B04 → power/voltage/current
};
const TzConverter* const kTz_ZB250[] = {
    &::zhc::generic::kTzOnOff,
    &::zhc::generic::kTzBrightness,
    &::zhc::generic::kTzPowerOnBehavior1,
};
constexpr const char* kModels_ZB250[] = { "SZ1000" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"brightness", ExposeType::Numeric, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"power_on_behavior", ExposeType::Enum, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "V", nullptr, nullptr, 0},
    {"current", ExposeType::Numeric, Access::State, "A", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0006},
    {1, 0x0008},
    {1, 0x0702},
    {1, 0x0B04},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_ZB250{
    .zigbee_models=kModels_ZB250, .zigbee_models_count=sizeof(kModels_ZB250)/sizeof(kModels_ZB250[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="ZB250", .vendor="Micromatic",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_ZB250, .from_zigbee_count=sizeof(kFz_ZB250)/sizeof(kFz_ZB250[0]),
    .to_zigbee=kTz_ZB250, .to_zigbee_count=sizeof(kTz_ZB250)/sizeof(kTz_ZB250[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::micromatic
