// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Edp PLUG EDP RE:DY — graduated from generated/ to fix bind endpoint.
// re:dy plug
// z2m-source: edp.ts #PLUG EDP RE:DY.
//
// Bug: z2m configures on `device.getEndpoint(85)` and binds genOnOff +
// seMetering there ("re:dy plug uses ep relay"). The auto-port bound on
// endpoint 1 ({1,0x0006}/{1,0x0702}), so the coordinator never bound the
// relay/metering endpoint the device actually reports on → no onOff /
// metering reports flow and state/power/energy stay dead. Repointed both
// bindings to the device's relay endpoint 85. Decode is endpoint-agnostic
// (WILDCARD_ENDPOINT) so the single-endpoint exposes stay bare (no
// endpoint_map). Metering stays 0x0702-only — z2m uses fz.metering, NOT
// fz.electrical_measurement, so there is no 0x0B04 channel to add.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::edp {
namespace {
const FzConverter* const kFz_PLUG_EDP_RE_DY[] = {
    &::zhc::generic::kFzOnOff,
    &::zhc::generic::kFzMetering,
};
const TzConverter* const kTz_PLUG_EDP_RE_DY[] = {
    &::zhc::generic::kTzOnOff,
};
constexpr const char* kModels_PLUG_EDP_RE_DY[] = { "ZB-SmartPlug-1.0.0", "ZB-SmartPlugIR-1.0.0" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"state", ExposeType::Binary, Access::StateSet, nullptr, nullptr, nullptr, 0},
    {"energy", ExposeType::Numeric, Access::State, "kWh", nullptr, nullptr, 0},
    {"power", ExposeType::Numeric, Access::State, "W", nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {85, 0x0006},  // genOnOff   — re:dy relay endpoint (z2m getEndpoint(85))
    {85, 0x0702},  // seMetering — re:dy relay endpoint (z2m getEndpoint(85))
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_PLUG_EDP_RE_DY{
    .zigbee_models=kModels_PLUG_EDP_RE_DY, .zigbee_models_count=sizeof(kModels_PLUG_EDP_RE_DY)/sizeof(kModels_PLUG_EDP_RE_DY[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="PLUG EDP RE:DY", .vendor="Edp",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_PLUG_EDP_RE_DY, .from_zigbee_count=sizeof(kFz_PLUG_EDP_RE_DY)/sizeof(kFz_PLUG_EDP_RE_DY[0]),
    .to_zigbee=kTz_PLUG_EDP_RE_DY, .to_zigbee_count=sizeof(kTz_PLUG_EDP_RE_DY)/sizeof(kTz_PLUG_EDP_RE_DY[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::edp
