// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Hej KKZ-MO021 — hand-maintained parity override.
//
// Graduated from generated/Hej_KKZ_MO021.cpp: the generated def lowered
// the generic kFzIasZone converter — which emits the bare key "alarm" —
// while the expose declares the semantic key "occupancy". With no rename
// layer the primary sensor state never reached the shadow. z2m decodes
// this via fz.ias_occupancy_alarm_1 (zoneStatus bit 0), so the typed
// kFzIasMotionAlarm converter — which emits "occupancy" directly — is at
// parity. Mirrors the heiman HS1MS-EF IAS occupancy port.
// PIR sensor
// z2m-source: hej.ts #KKZ-MO021 (fz.battery, fz.ias_occupancy_alarm_1).
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::hej {
namespace {
const FzConverter* const kFz_KKZ_MO021[] = {
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzIasMotionAlarm,
};

constexpr const char* kModels_KKZ_MO021[] = { "RH3040" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"occupancy", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"tamper", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
    {"battery_low", ExposeType::Binary, Access::State, nullptr, nullptr, nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0500},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDef_KKZ_MO021{
    .zigbee_models=kModels_KKZ_MO021, .zigbee_models_count=sizeof(kModels_KKZ_MO021)/sizeof(kModels_KKZ_MO021[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="KKZ-MO021", .vendor="Hej",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_KKZ_MO021, .from_zigbee_count=sizeof(kFz_KKZ_MO021)/sizeof(kFz_KKZ_MO021[0]),
    .to_zigbee=nullptr, .to_zigbee_count=0,
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::hej
