// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Efekta EFEKTA_TH_POW, graduated from the generated def for
// z2m v26.115.1: dew_point / air_enthalpy / vpd (msTemperatureMeasurement 0x0341 / 0x0343 / 0x0340).
// Temperature and humidity smart monitor with voltage detector
// z2m-source: efekta.ts #EFEKTA_TH_POW.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::efekta {
namespace {
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_TH_POW_reading_interval{ "reading_interval", 0x0201, 0x21, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_TH_POW_reading_interval{
    .key="reading_interval", .cluster="genPowerCfg",
    .cluster_id=0x0001, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_TH_POW_reading_interval };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_TH_POW_high_temperature{ "high_temperature", 0x0221, 0x29, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_TH_POW_high_temperature{
    .key="high_temperature", .cluster="msTemperatureMeasurement",
    .cluster_id=0x0402, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_TH_POW_high_temperature };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_TH_POW_low_temperature{ "low_temperature", 0x0222, 0x29, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_TH_POW_low_temperature{
    .key="low_temperature", .cluster="msTemperatureMeasurement",
    .cluster_id=0x0402, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_TH_POW_low_temperature };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_TH_POW_high_humidity{ "high_humidity", 0x0221, 0x21, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_TH_POW_high_humidity{
    .key="high_humidity", .cluster="msRelativeHumidity",
    .cluster_id=0x0405, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_TH_POW_high_humidity };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_TH_POW_low_humidity{ "low_humidity", 0x0222, 0x21, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_TH_POW_low_humidity{
    .key="low_humidity", .cluster="msRelativeHumidity",
    .cluster_id=0x0405, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_TH_POW_low_humidity };
// z2m m.numeric on msTemperatureMeasurement (int16, scale 100): vpd 0x0340
// (kPa), dew_point 0x0341 (C), air_enthalpy 0x0343 (kJ/kg).
constexpr ::zhc::generic::ZclAttrRow kTempExtraRows[] = {
    { 0x0341, "dew_point", 100 }, { 0x0343, "air_enthalpy", 100 }, { 0x0340, "vpd", 100 },
};
constexpr ::zhc::generic::ZclAttrMap kTempExtraMap{ kTempExtraRows, 3 };
constexpr FzConverter kFzTempExtra = ::zhc::generic::zcl_attr_fz("msTemperatureMeasurement", &kTempExtraMap);
const FzConverter* const kFz_EFEKTA_TH_POW[] = {
    &kFzTempExtra,
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzHumidity,
    &::zhc::generic::kFzTemperature,
};
const TzConverter* const kTz_EFEKTA_TH_POW[] = {
    &kTzWrite_EFEKTA_TH_POW_reading_interval,
    &kTzWrite_EFEKTA_TH_POW_high_temperature,
    &kTzWrite_EFEKTA_TH_POW_low_temperature,
    &kTzWrite_EFEKTA_TH_POW_high_humidity,
    &kTzWrite_EFEKTA_TH_POW_low_humidity,
};
constexpr const char* kModels_EFEKTA_TH_POW[] = { "EFEKTA_TH_POW_E", "EFEKTA_TH_POW_R" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"humidity", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "°C", nullptr, nullptr, 0},
    {"dew_point", ExposeType::Numeric, Access::State, "°C", "Dew point calculated from built-in sensor data", nullptr, 0},
    {"air_enthalpy", ExposeType::Numeric, Access::State, "kJ/kg", "Air enthalpy derived from built-in sensor", nullptr, 0},
    {"vpd", ExposeType::Numeric, Access::State, "kPa", "Vapor Pressure Deficit (VPD) from built-in sensor", nullptr, 0},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0405},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefEfekta_TH_POW{
    .zigbee_models=kModels_EFEKTA_TH_POW, .zigbee_models_count=sizeof(kModels_EFEKTA_TH_POW)/sizeof(kModels_EFEKTA_TH_POW[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="EFEKTA_TH_POW", .vendor="Efekta",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_EFEKTA_TH_POW, .from_zigbee_count=sizeof(kFz_EFEKTA_TH_POW)/sizeof(kFz_EFEKTA_TH_POW[0]),
    .to_zigbee=kTz_EFEKTA_TH_POW, .to_zigbee_count=sizeof(kTz_EFEKTA_TH_POW)/sizeof(kTz_EFEKTA_TH_POW[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::efekta
