// SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
// SPDX-License-Identifier: Apache-2.0
// Tier 2: Efekta EFEKTA_PST_V1, graduated from the generated def for
// z2m v26.115.1: overheating (msPressureMeasurement 0x0020).
// Water, gas smart pressure monitor
// z2m-source: efekta.ts #EFEKTA_PST_V1.
#include "definitions/_generic/_shared.hpp"

namespace zhc::devices::efekta {
namespace {
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_PST_V1_pressure_offset{ "pressure_offset", 0x0210, 0x29, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_PST_V1_pressure_offset{
    .key="pressure_offset", .cluster="msPressureMeasurement",
    .cluster_id=0x0403, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_PST_V1_pressure_offset };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_PST_V1_raw_temperature_calibration{ "raw_temperature_calibration", 0x0008, 0x29, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_PST_V1_raw_temperature_calibration{
    .key="raw_temperature_calibration", .cluster="msTemperatureMeasurement",
    .cluster_id=0x0402, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_PST_V1_raw_temperature_calibration };
constexpr ::zhc::generic::ZclWriteSpec kWriteSpec_EFEKTA_PST_V1_reading_interval{ "reading_interval", 0x0201, 0x28, 0, nullptr, 0 };
constexpr TzConverter kTzWrite_EFEKTA_PST_V1_reading_interval{
    .key="reading_interval", .cluster="genPowerCfg",
    .cluster_id=0x0001, .command_id=0x02,
    .fn=::zhc::generic::tz_zcl_write_attr,
    .user_config=&kWriteSpec_EFEKTA_PST_V1_reading_interval };
// z2m m.enumLookup overheating: msPressureMeasurement 0x0020 (bool),
// published as the words FALSE / TRUE.
constexpr ::zhc::generic::ZclWriteLookup kOverheating[] = { {"FALSE", 0}, {"TRUE", 1} };
constexpr ::zhc::generic::ZclAttrRow kPressureExtraRows[] = { { 0x0020, "overheating", 1, kOverheating, 2 } };
constexpr ::zhc::generic::ZclAttrMap kPressureExtraMap{ kPressureExtraRows, 1 };
constexpr FzConverter kFzPressureExtra = ::zhc::generic::zcl_attr_fz("msPressureMeasurement", &kPressureExtraMap);
const FzConverter* const kFz_EFEKTA_PST_V1[] = {
    &kFzPressureExtra,
    &::zhc::generic::kFzBattery,
    &::zhc::generic::kFzPressure,
    &::zhc::generic::kFzTemperature,
};
const TzConverter* const kTz_EFEKTA_PST_V1[] = {
    &kTzWrite_EFEKTA_PST_V1_pressure_offset,
    &kTzWrite_EFEKTA_PST_V1_raw_temperature_calibration,
    &kTzWrite_EFEKTA_PST_V1_reading_interval,
};
constexpr const char* kModels_EFEKTA_PST_V1[] = { "EFEKTA_PST_V1" };

}  // namespace


// --- auto-generated by emit_expose_bindings.py ---
constexpr const char* kOverheatingLabels[] = { "FALSE", "TRUE" };
constexpr Expose kAutoExposes[] = {
    {"battery", ExposeType::Numeric, Access::State, "%", nullptr, nullptr, 0},
    {"voltage", ExposeType::Numeric, Access::State, "mV", nullptr, nullptr, 0},
    {"pressure", ExposeType::Numeric, Access::State, "hPa", nullptr, nullptr, 0},
    {"temperature", ExposeType::Numeric, Access::State, "C", nullptr, nullptr, 0},
    {"overheating", ExposeType::Enum, Access::State, nullptr, "Sensor overheating detection", kOverheatingLabels, 2},
};

constexpr BindingSpec kAutoBindings[] = {
    {1, 0x0001},
    {1, 0x0402},
    {1, 0x0403},
};
// --- end auto-generated block ---

extern const PreparedDefinition kDefEfekta_PST_V1{
    .zigbee_models=kModels_EFEKTA_PST_V1, .zigbee_models_count=sizeof(kModels_EFEKTA_PST_V1)/sizeof(kModels_EFEKTA_PST_V1[0]),
    .manufacturer_name_prefix=nullptr,
    .manufacturer_names=nullptr, .manufacturer_names_count=0,
    .model="EFEKTA_PST_V1", .vendor="Efekta",
    .meta=nullptr, .exposes=kAutoExposes, .exposes_count=sizeof(kAutoExposes)/sizeof(kAutoExposes[0]),
    .white_labels=nullptr, .white_labels_count=0,
    .from_zigbee=kFz_EFEKTA_PST_V1, .from_zigbee_count=sizeof(kFz_EFEKTA_PST_V1)/sizeof(kFz_EFEKTA_PST_V1[0]),
    .to_zigbee=kTz_EFEKTA_PST_V1, .to_zigbee_count=sizeof(kTz_EFEKTA_PST_V1)/sizeof(kTz_EFEKTA_PST_V1[0]),
    .configure=nullptr, .on_event=nullptr,
.bindings=kAutoBindings,.bindings_count=sizeof(kAutoBindings)/sizeof(kAutoBindings[0]),
};

}  // namespace zhc::devices::efekta
